User-agent: *
Disallow: /resources/downloads/
Disallow: /analysts/includes/
Disallow: /experiments/
Disallow: /events/devsecops-world-tour/executive/
Disallow: /events/events/summit-las-vegas/
Disallow: /handbook/marketing/strategic-marketing/demo/ct-files/mr-approval.html
Disallow: /handbook/marketing/strategic-marketing/demo/ct-files/AutoDevOps-v13.html
Disallow: /handbook/marketing/strategic-marketing/demo/ct-files/gke-setup.html
Disallow: /handbook/ceo/shadow/setalarm.sh
Sitemap: https://about.gitlab.com/sitemap.xml
