User-agent: *
Disallow: /api
Disallow: /api/*
Disallow: /pages/footer
Disallow: /pages/topbar
Disallow: /link/*
Disallow: /signin/*
Disallow: /cdn-cgi/
Disallow: /course/affiliate-revenue-learnworlds
Disallow: /course/success-stories
Disallow: /course/affiliate-marketing
Disallow: /course/practical-seo-course-creators
Disallow: /course/facebook-ads
Disallow: /course/how-to-choose-the-right-video-equipment-for-online-courses
Disallow: /course/learnworlds-daily-demo
Disallow: /course/online-community-membership-site
Disallow: /course/the-ultimate-guide-to-email-marketing
Disallow: /course/designing-interactive-video-for-learning
Disallow: /course/from-passive-to-interactive-learn-how-interactive-videos-can-transform-learning
Disallow: /course/video-based-learning
Disallow: /course/creating-a-course-with-learnworlds
Sitemap: https://academy.learnworlds.com/sitemap.xml