User-agent: *
Disallow: /agqadmin/
Disallow: /wp-admin/
Disallow: /wp-includes/
Disallow: /wp-content/plugins/
Disallow: /wp-content/themes/
Disallow: /tag/
Disallow: /author/
Disallow: /feed/
Disallow: /*/feed/
Disallow: /trackback/
Disallow: /?*
Disallow: /politica-de-privacidad/
Disallow: /aviso-legal/
Allow: /wp-admin/admin-ajax.php
Allow: /wp-content/uploads/
Allow: /*.css$
Allow: /*.js$
Allow: /*.css?*
Allow: /*.js?*
Allow: /wp-content/*/*.css$
Allow: /wp-content/*/*.js$
Allow: /wp-includes/*/*.css$
Allow: /wp-includes/*/*.js$
Allow: /wp-content/*/*.css?*
Allow: /wp-content/*/*.js?*
Allow: /wp-includes/*/*.css?*
Allow: /wp-includes/*/*.js?*

Sitemap: https://agqlabs.cr/sitemap_index.xml