ï»¿User-agent: *
Disallow: /ActiveWidgets/
Disallow: /Ad
Disallow: /ajax
Disallow: /Ajax
Disallow: /API/
Disallow: /App
Disallow: /AutoComplete/
Disallow: /Balloon/
Disallow: /Bin/
Disallow: /ClientTests/
Disallow: /ClumpTemplateUserControls/
Disallow: /ColorPalette/
Disallow: /ComplianceReports/
Disallow: /Cont
Disallow: /Corda/
Disallow: /CoverageWizard/
Disallow: /CR/
Disallow: /Dashboard/
Disallow: /DedupeWizard/
Disallow: /Dem
Disallow: /Distribution/
Disallow: /domtt/
Disallow: /Editor/
Disallow: /EntityHome/
Disallow: /ExportWizard/
Disallow: /GoogleGadgets/
Disallow: /GR/
Disallow: /Haro/
Disallow: /home/
Disallow: /Images/
Disallow: /iPhone/
Disallow: /JobGenericWizard/
Disallow: /js/
Disallow: /JSComponents/
Disallow: /LegacyVocusDateTime/
Disallow: /Local
Disallow: /MainNav/
Disallow: /MS
Disallow: /Noesis
Disallow: /Pick
Disallow: /PM/
Disallow: /PR/
Disallow: /Profile
Disallow: /prweb/
Disallow: /Rest
Disallow: /Sales
Disallow: /SBE
Disallow: /TextboxListDialogs/
Disallow: /UserControls/
Disallow: /View
Disallow: /Vocus
Disallow: /WebPublish/
Disallow: /Wireless/
Disallow: /XR/
Disallow: /xsl