User-agent: *
Allow: /icalendar/
# Disallowed portals are included as Allowed to use noindex strategy: https://developers.google.com/search/docs/advanced/crawling/block-indexing
Allow: /timeslots
Sitemap: https://deloitteus.avature.net/timeslots/sitemap_index.xml
Allow: /docusign
Sitemap: https://deloitteus.avature.net/docusign/sitemap_index.xml
Allow: /careers
Sitemap: https://apply.deloitte.com/careers/sitemap_index.xml
Allow: /EmployeeRecruiting
Sitemap: https://deloitteus.avature.net/EmployeeRecruiting/sitemap_index.xml
Allow: /volunteereventslisting
Sitemap: https://deloitteus.avature.net/volunteereventslisting/sitemap_index.xml
Allow: /onsite
Sitemap: https://deloitteus.avature.net/onsite/sitemap_index.xml
Allow: /eventlisting
Sitemap: https://rsvp.deloitte.com/eventlisting/sitemap_index.xml
Allow: /CustomAgreement
Sitemap: https://deloitteus.avature.net/CustomAgreement/sitemap_index.xml
Allow: /hiringmanager
Sitemap: https://deloitteus.avature.net/hiringmanager/sitemap_index.xml
Allow: /ManagerDocusign
Sitemap: https://deloitteus.avature.net/ManagerDocusign/sitemap_index.xml
Allow: /careersDOT
Sitemap: https://opentalent.deloitte.com/careersDOT/sitemap_index.xml
Allow: /referrals
Sitemap: https://deloitteus.avature.net/referrals/sitemap_index.xml
Allow: /agency
Sitemap: https://agency.deloitte.com/agency/sitemap_index.xml
Allow: /docusignWithSSO
Sitemap: https://deloitteus.avature.net/docusignWithSSO/sitemap_index.xml
Allow: /hiringmanagerusi
Sitemap: https://deloitteus.avature.net/hiringmanagerusi/sitemap_index.xml
Allow: /ManagerDocusignUSI
Sitemap: https://deloitteus.avature.net/ManagerDocusignUSI/sitemap_index.xml
Allow: /