<!doctype html><html lang="en"><head><meta charset="utf-8"/><meta http-equiv="X-UA-Compatible" content="IE=edge"/><meta name="viewport" content="width=device-width,initial-scale=1"/><link rel="icon" href="https://prod-auth0-influencer-login-ui.shopltk.com/favicon.ico"/><link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css"/><title>Creator Login</title><script src="https://prod-auth0-influencer-login-ui.shopltk.com/static/js/config.js"></script><script defer="defer" src="https://prod-auth0-influencer-login-ui.shopltk.com/js/chunk-vendors.e0fcd492.js"></script><script defer="defer" src="https://prod-auth0-influencer-login-ui.shopltk.com/js/app.40450e4c.js"></script><link href="https://prod-auth0-influencer-login-ui.shopltk.com/css/chunk-vendors.846b7433.css" rel="stylesheet"><link href="https://prod-auth0-influencer-login-ui.shopltk.com/css/app.3b6c6e03.css" rel="stylesheet"></head><body><noscript><strong>We're sorry but this site doesn't work properly without JavaScript enabled. Please enable it to continue.</strong></noscript><div id="login-app"></div><script src="https://cdn.auth0.com/js/lock/11.15/lock.min.js"></script><script>// if NOT running local. decode the URI component
      if (!(location.hostname === 'localhost' || location.hostname === '127.0.0.1')) {
        try {
          window.configParams = JSON.parse(
            decodeURIComponent(escape(window.atob("eyJpY29uIjoiaHR0cHM6Ly9zMy5hbWF6b25hd3MuY29tL2NvbGxhYnMuYXNzZXRzLnJld2FyZHN0eWxlLmNvbS9lbWFpbC9MVEtfTG9nb193aGl0ZUAyeC5wbmciLCJhc3NldHNVcmwiOiIiLCJhdXRoMERvbWFpbiI6ImNyZWF0b3ItYXV0aC5zaG9wbHRrLmNvbSIsImF1dGgwVGVuYW50IjoicHJvZC1ycy1pbmZsdWVuY2VyIiwiY2xpZW50Q29uZmlndXJhdGlvbkJhc2VVcmwiOiJodHRwczovL2NyZWF0b3ItYXV0aC5zaG9wbHRrLmNvbS8iLCJjYWxsYmFja09uTG9jYXRpb25IYXNoIjpmYWxzZSwiY2FsbGJhY2tVUkwiOiJodHRwczovL2NyZWF0b3Iuc2hvcGx0ay5jb20vd2ViL2F1dGgvY2FsbGJhY2siLCJjZG4iOiJodHRwczovL2Nkbi5hdXRoMC5jb20vIiwiY2xpZW50SUQiOiJLU2Vua0J5dG5IQmgzNWhJVlVtMW01NFdBR3BMcnRPeiIsImRpY3QiOnsic2lnbmluIjp7InRpdGxlIjoicmV3YXJkc3R5bGUtdjItbGVnYWN5In19LCJleHRyYVBhcmFtcyI6eyJwcm90b2NvbCI6Im9hdXRoMiIsImF1ZGllbmNlIjoiaHR0cHM6Ly9jcmVhdG9yLWFwaS1nYXRld2F5LnNob3BsdGsuY29tL2xlZ2FjeSIsInNjb3BlIjoib3BlbmlkIHByb2ZpbGUgZW1haWwgbHRrLnB1Ymxpc2hlciIsInJlc3BvbnNlX21vZGUiOiJxdWVyeSIsInJlc3BvbnNlX3R5cGUiOiJjb2RlIiwiX2NzcmYiOiJWTWE5NkFvVy02QldFODFrbGk0cno3ekQwYzhuWmFlY1hIMVEiLCJfaW50c3RhdGUiOiJkZXByZWNhdGVkIiwic3RhdGUiOiJoS0ZvMlNCUWVHUjJUMVZ0YTNGNFVqZE5WMWN3YTFkbWNIVmpialV5Y0U4NVNGQjVWcUZ1cFd4dloybHVvM1JwWk5rZ2JXaHBUelZrZWpoSWNsWjJPSFJYTlU4NGJHZEhSM1kyVVdSQmFHSTFWbHFqWTJsazJTQkxVMlZ1YTBKNWRHNUlRbWd6TldoSlZsVnRNVzAxTkZkQlIzQk1jblJQZWcifSwiaW50ZXJuYWxPcHRpb25zIjp7InByb3RvY29sIjoib2F1dGgyIiwiYXVkaWVuY2UiOiJodHRwczovL2NyZWF0b3ItYXBpLWdhdGV3YXkuc2hvcGx0ay5jb20vbGVnYWN5Iiwic2NvcGUiOiJvcGVuaWQgcHJvZmlsZSBlbWFpbCBsdGsucHVibGlzaGVyIiwicmVzcG9uc2VfbW9kZSI6InF1ZXJ5IiwicmVzcG9uc2VfdHlwZSI6ImNvZGUiLCJfY3NyZiI6IlZNYTk2QW9XLTZCV0U4MWtsaTRyejd6RDBjOG5aYWVjWEgxUSIsIl9pbnRzdGF0ZSI6ImRlcHJlY2F0ZWQiLCJzdGF0ZSI6ImhLRm8yU0JRZUdSMlQxVnRhM0Y0VWpkTlYxY3dhMWRtY0hWamJqVXljRTg1U0ZCNVZxRnVwV3h2WjJsdW8zUnBaTmtnYldocFR6VmtlamhJY2xaMk9IUlhOVTg0YkdkSFIzWTJVV1JCYUdJMVZscWpZMmxrMlNCTFUyVnVhMEo1ZEc1SVFtZ3pOV2hKVmxWdE1XMDFORmRCUjNCTWNuUlBlZyJ9LCJ3aWRnZXRVcmwiOiJodHRwczovL2Nkbi5hdXRoMC5jb20vdzIvYXV0aDAtd2lkZ2V0LTUuMi5taW4uanMiLCJpc1RoaXJkUGFydHlDbGllbnQiOmZhbHNlLCJhdXRob3JpemF0aW9uU2VydmVyIjp7InVybCI6Imh0dHBzOi8vY3JlYXRvci1hdXRoLnNob3BsdGsuY29tIiwiaXNzdWVyIjoiaHR0cHM6Ly9jcmVhdG9yLWF1dGguc2hvcGx0ay5jb20vIn0sImNvbG9ycyI6eyJwYWdlX2JhY2tncm91bmQiOiIjMDAwMDAwIiwicHJpbWFyeSI6IiNlYTUzMjMifX0=")))
          );
        } catch (err) {
          console.error('failed to parse config params: ' + JSON.stringify(err));
        }
      }</script><script src="https://cdn.auth0.com/js/auth0/9.2/auth0.min.js"></script><script src="https://cdn.auth0.com/js/polyfills/1.0/object-assign.min.js"></script></body></html>