Sitemap: https://azure.microsoft.com/robotsitemap-en-us/
Sitemap: https://azure.microsoft.com/robotsitemap-cs-cz/
Sitemap: https://azure.microsoft.com/robotsitemap-da-dk/
Sitemap: https://azure.microsoft.com/robotsitemap-de-de/
Sitemap: https://azure.microsoft.com/robotsitemap-en-au/
Sitemap: https://azure.microsoft.com/robotsitemap-en-ca/
Sitemap: https://azure.microsoft.com/robotsitemap-en-in/
Sitemap: https://azure.microsoft.com/robotsitemap-en-gb/
Sitemap: https://azure.microsoft.com/robotsitemap-es-es/
Sitemap: https://azure.microsoft.com/robotsitemap-es-mx/
Sitemap: https://azure.microsoft.com/robotsitemap-fr-fr/
Sitemap: https://azure.microsoft.com/robotsitemap-fr-ca/
Sitemap: https://azure.microsoft.com/robotsitemap-id-id/
Sitemap: https://azure.microsoft.com/robotsitemap-it-it/
Sitemap: https://azure.microsoft.com/robotsitemap-hu-hu/
Sitemap: https://azure.microsoft.com/robotsitemap-nb-no/
Sitemap: https://azure.microsoft.com/robotsitemap-nl-nl/
Sitemap: https://azure.microsoft.com/robotsitemap-pl-pl/
Sitemap: https://azure.microsoft.com/robotsitemap-pt-br/
Sitemap: https://azure.microsoft.com/robotsitemap-pt-pt/
Sitemap: https://azure.microsoft.com/robotsitemap-sv-se/
Sitemap: https://azure.microsoft.com/robotsitemap-tr-tr/
Sitemap: https://azure.microsoft.com/robotsitemap-ru-ru/
Sitemap: https://azure.microsoft.com/robotsitemap-ja-jp/
Sitemap: https://azure.microsoft.com/robotsitemap-ko-kr/
Sitemap: https://azure.microsoft.com/robotsitemap-zh-cn/
Sitemap: https://azure.microsoft.com/robotsitemap-zh-tw/
Sitemap: https://azure.microsoft.com/en-us/blog/sitemap_index.xml
Sitemap: https://azure.microsoft.com/de-de/blog/sitemap_index.xml
Sitemap: https://azure.microsoft.com/es-es/blog/sitemap_index.xml
Sitemap: https://azure.microsoft.com/fr-fr/blog/sitemap_index.xml
Sitemap: https://azure.microsoft.com/ja-jp/blog/sitemap_index.xml
User-agent: *
Disallow: /*/searchresults/
Disallow: /*/search/?q=*
Disallow: /*/patterns/
Disallow: /api/
Disallow: /debug/
Disallow: /di-ag/
Disallow: /global-infrastructure/services/get-async/