User-agent: *
Disallow: /wt-assets/static-files/mktg-analytics
Disallow: /_hcms/preview/
Disallow: /_hcms/iplookup
Disallow: /_hcms/perf
Disallow: /hs/manage-preferences/
Disallow: *?portalId=
Disallow: *?inpageEditorUI=
Disallow: *?cssPath=
Disallow: *?_health_check_=
Disallow: *?_preview=
Disallow: *?benderPackage=
Disallow: *?preview_key=
Disallow: *?staticVersion=
Disallow: *?cacheBurst=
Disallow: *?tc_deviceCategory=
Disallow: *?isPreview=
Disallow: *?preview_theme=
Disallow: *?cos=
Disallow: /marketing/inbound-vs-outbound-marketing
Disallow: /marketing/6-pasos-iniciales
Disallow: /marketing/inbound-marketing
Disallow: /marketing/el-equipo-para-una-estrategia-de-inbound-marketing
Disallow: /marketing/3-errores-en-tu-estrategia-de-ventas-que-debes-dejar-de-cometer-hoy
Disallow: /marketing/7-claves-para-una-campaña-de-email-marketing-exitosa
Disallow: /marketing/100-trucos-para-posicionar-tu-web-en-google-como-un-campeon
Disallow: /marketing/7-consejos-de-diseno-para-conseguir-mas-visitas-en-tu-sitio
Disallow: /marketing/outbound-vs-inbound-quien-ganara-la-batalla
Disallow: /marketing/generacion-de-leads-con-twitter-ads-tweets-promocionados-vs-lead-generation-cards
Disallow: /marketing/la-rutina-diaria-de-inbound-marketing

Disallow: /hs/preferences-center/
