User-agent: *
Disallow: /search
Disallow: */1000$
Disallow: /epdf/
Disallow: tab=
Disallow: /about/institutional-support/membership/
Disallow: /about/membership/members/
Disallow: /about/oa-funding-and-policy-support/
Disallow: /*/*/*/sharedit
Sitemap: https://bmcdigitalhealth.biomedcentral.com/sitemap.xml