
User-agent: *
Allow: /
Allow: /s      # allow all
Disallow: /s/article/Lodgment-rates-and-thresholds-guide-2018-19
Disallow: /s/article/Lodgment-rates-and-thresholds-guide-2019-20
Disallow: /s/article/Short-term-cash-flow-error-message
Disallow: /s/article/Update-bank-connection
Disallow: /s/article/Access-the-Xero-Assistance-Programme-for-mental-health-support
Disallow: /s/article/Xero-releases-archive
Disallow: /s/article/Generate-and-file-a-GST-return
Disallow: /s/article/Navigation-bar-shows-new-options 
Disallow: /s/article/Security-noticeboard
Disallow: /s/article/Add-a-bill
Disallow: /s/article/Send-invoices
Disallow: /s/article/Connect-to-your-bank
Disallow: /s/article/Stripe-App-direct-feeds
Disallow: /s/article/ATO-mandate-changes-and-how-they-affect-you
Disallow: /s/article/Xero-Tax-releases-archive
Disallow: /s/article/Partner-products-releases-archive
Disallow: /s/article/Set-up-payroll-and-manage-employees-AU
Disallow: /s/article/Set-up-payroll-and-manage-employees-UK
Disallow: /s/article/Set-up-payroll-and-manage-employees-NZ
Disallow: /s/article/Set-up-payroll-and-manage-employees-ROW
Disallow: /s/article/Set-up-payroll-and-manage-employees-US
Disallow: /s/article/Lodgment-rates-and-thresholds-guide-2023-24
Disallow: /s/article/Lodgment-rates-and-thresholds-guide-2020-21
Disallow: /s/article/Lodgment-rates-and-thresholds-guide-2021-22
Disallow: /s/article/Lodgment-rates-and-thresholds-guide-2022-23
Disallow: /s/article/Import-bank-transactions-using-the-new-experience
Disallow: /s/article/Connect-Xero-HQ-to-Workpapers
Disallow: /s/article/Set-up-and-manage-your-clients-UK
Disallow: /s/article/Xero-bureau-plans
Disallow: /s/article/TRAINING-About-Xero-CA-TRAINING
Disallow: /s/article/Troubleshoot-filing-issues-with-the-GST-return
Disallow: /s/article/Access-Xero-through-Azets-Cozone
Disallow: /s/article/Changes-to-fixed-assets
Disallow: /s/article/About-fixed-assets-compliance-GL
Disallow: /s/article/About-fixed-assets-compliance-AU
Disallow: /s/article/About-fixed-assets-compliance-CA
Disallow: /s/article/About-fixed-assets-compliance-SG
Disallow: /s/article/About-fixed-assets-compliance
Disallow: /s/article/About-fixed-assets-compliance-US
Disallow: /s/article/Payroll-manager
Disallow: /s/article/Pay-bills-using-Xero-Pay-with-BILL
Disallow: /login*
Disallow: /s/login/ 
Disallow: /s/feed/*
Disallow: /s/user/*
Disallow: /s/guides
Disallow: /s/test
Disallow: /OIDCRedirect*
Disallow: /s/contact-support
Disallow: /s/start-a-discussion 
Disallow: /s/topic/0TO1N0000017kmaWAA/reconciling-transactions-business
Disallow: /s/topic/0TO1N0000017kmpWAA/bank-accounts-feeds-business
Disallow: /s/topic/0TO1N0000017kn4WAA/payroll-employees-business
Disallow: /s/topic/0TO1N0000017knJWAQ/invoices-quotes-business
Disallow: /s/topic/0TO1N0000017knYWAQ/invoices-quotes-practice
Disallow: /s/topic/0TO1N0000017kniWAA/bills-purchase-orders-expenses-business
Disallow: /s/topic/0TO1N0000017knxWAA/reporting-tracking-business
Disallow: /s/topic/0TO1N0000017knyWAA/reporting-tracking-practice
Disallow: /s/topic/0TO1N0000017koHWAQ/project-management-business
Disallow: /s/topic/0TO1N0000017koIWAQ/project-management-practice
Disallow: /s/topic/0TO1N0000017koWWAQ/practice-management-practice
Disallow: /s/topic/0TO1N0000017kolWAA/inventory-business
Disallow: /s/topic/0TO1N0000017kovWAA/accounting-tasks-business
Disallow: /s/topic/0TO1N0000017kpAWAQ/contacts-clients-communication-practice
Disallow: /s/topic/0TO1N0000017koQWAQ/contacts-clients-communication-business
Disallow: /s/topic/0TO1N0000017kpPWAQ/giving-people-access-to-xero-business
Disallow: /s/topic/0TO1N0000017kpUWAQ/tax-filing-business
Disallow: /s/topic/0TO1N0000017kpVWAQ/tax-filing-practice
Disallow: /s/topic/0TO1N0000017kptWAA/your-xero-account-business
Disallow: /s/topic/0TO1N0000017kpuWAA/your-xero-account-practice
Disallow: /s/topic/0TO1N0000017kq8WAA/importing-exporting-data-business
Disallow: /s/topic/0TO1N0000017kq9WAA/importing-exporting-data-practice
Disallow: /s/topic/0TO1N0000017kqGWAQ/support-security-updates-business
Disallow: /s/topic/0TO1N0000017kqHWAQ/support-security-updates-practice
Disallow: /s/topic/0TO1N0000017kqSWAQ/connected-apps-services-business
Disallow: /s/topic/0TO1N0000017kqTWAQ/connected-apps-services-practice
Disallow: /s/topic/0TO1N0000017kqhWAA/fixed-assets-business
Disallow: /s/question/0D53m00009MSyiyCAD/detail
Disallow: /s/training-plan/a471N000000mDTWQA2/fasttrack-xero-advisor-certification-assessment
Disallow: /s/training-plan/a471N000000mEliQAE/fasttrack-payroll-certification-assessment

Sitemap: https://central.xero.com/s/sitemap.xml