User-agent:*
Disallow:/*?from=
Disallow:/*?utm_source=
Disallow:/*?fromSource=
Disallow:/*?utm_Source=
Disallow:/*?fromsource=
Disallow:/*?packageId=
Disallow:/*?idx=
Disallow:/*?page=
Disallow:/*?type=
Disallow:/login
Disallow:/register
Disallow:/services/ajax
Disallow:/services/sync
Disallow:/*?lang=en
Disallow:/info/
Disallow:/search/
Disallow:/developer/search
Disallow:/developer/article/old/
Disallow:/developer/beta/article/
