User-agent: *
Crawl-delay: 5
Sitemap: https://community.macmillanlearning.com/sitemap.xml
Disallow: /t5/forums/forumtopicprintpage
Disallow: /t5/ideas/ideaprintpage
Disallow: /t5/blogs/blogarticleprintpage
Disallow: /t5/tkb/allarticlesprintpage
Disallow: /t5/tkb/articleprintpage
Disallow: /t5/contests/contestprintpage
Disallow: /t5/media/gallerypage/tab/all/
Disallow: /t5/media/gallerypage/tab/all?
Disallow: /t5/media/gallerypage/tab/all$
Disallow: /t5/media/gallerypage/*/tab/all/
Disallow: /t5/media/gallerypage/*/tab/all?
Disallow: /t5/media/gallerypage/*/tab/all$
Disallow: /t5/media/v*/gallerypage/tab/all/
Disallow: /t5/media/v*/gallerypage/tab/all?
Disallow: /t5/media/v*/gallerypage/tab/all$
Disallow: /t5/media/v*/gallerypage/*/tab/all/
Disallow: /t5/media/v*/gallerypage/*/tab/all?
Disallow: /t5/media/v*/gallerypage/*/tab/all$
Disallow: /t5/help/faqpage
Disallow: /vmvig64562/rss
Disallow: /t5/forums/usersonlinepage
Disallow: /t5/forums/recentpostspage
Disallow: /*?t:ac=
Disallow: /*&t:ac=
Disallow: /t5/util/componentrenderpage
Disallow: /*:lightboxrendercomponent?
Disallow: /*:lightboxrendercomponent&
Disallow: /*:lightboxrendercomponent/
Disallow: /*?ticket=
Disallow: /*&ticket=
Disallow: /t5/tkb/articlehistorypage
Disallow: /t5/forums/replypage
Disallow: /t5/forums/postpage
Disallow: /t5/notes/composepage
Disallow: /t5/notes/privatenotespage/tab/compose
Disallow: /t5/notes/v1_1/privatenotespage/tab/compose
Disallow: /t5/notifications/notifymoderatorpage
Disallow: /*nobounce
Disallow: /auth/
Disallow: /plugins/common/feature/oauth/
Disallow: /plugins/common/feature/oauth2sso/
Disallow: /plugins/common/feature/saml/
Disallow: /plugins/common/feature/openidconnectsso/
Disallow: /plugins/common/feature/openidsso/
Disallow: /t5/contentarchivals/
Disallow: /t5/occasions/createoccasionpage
Disallow: /t5/occasions/editoccasionpage
Disallow: /t5/blogs/blogworkflowpage
Disallow: /t5/tkb/workflowpage
Disallow: /t5/kudos/userpage/user-id/*/tab/
Disallow: /t5/kudos/messagepage/board-id/*/message-id/*/tab/
Disallow: /*kudosbuttonv2.kudoentity
Disallow: /t5/forums/tagdetailpage/tag-cloud-grouping/message/tag-cloud-style/recent/message-scope/core-node/board-id/*
Disallow: /t5/forums/tagdetailpage/tag-cloud-grouping/message/tag-cloud-style/frequent/message-scope/core-node/board-id/*
Disallow: /t5/forums/tagdetailpage/tag-cloud-grouping/message/tag-cloud-style/recent/message-scope/core-node/category-id/*
Disallow: /t5/forums/tagdetailpage/tag-cloud-grouping/message/tag-cloud-style/recent/message-scope/core-node/grouphub-id/*
Disallow: /t5/forums/tagdetailpage/tag-cloud-grouping/user/tag-cloud-style/frequent/message-scope/core-node/board-id/*
Disallow: /t5/forums/tagdetailpage/tag-cloud-grouping/user/tag-cloud-style/frequent/message-scope/core-node/category-id/*
Disallow: /t5/forums/tagdetailpage/tag-cloud-grouping/user/tag-cloud-style/leaderboard/message-scope/core-node/*
Disallow: /t5/user/viewprofilepage/*
Disallow: /t5/badges/userbadgespage/user-id/*
Disallow: /t5/media/*
Disallow: /t5/tag/*/tg-p/tag-id/*/category-id/*

