User-agent: *

Disallow:  /ws
Disallow:  /discount
Disallow:  /account_api
Disallow:  /api
Disallow:  /admin
Disallow:  /campaigns
Disallow:  /connections
Disallow:  /contacts
Disallow:  /conversations
Disallow:  /groups
Disallow:  /listener
Disallow:  /key
Disallow:  /maintenance
Disallow:  /messages
Disallow:  /messaging
Disallow:  /migrator
Disallow:  /pagenotfound
Disallow:  /people
Disallow:  /settings
Disallow:  /unittest
