Sitemap: https://www.oregonlive.com/arc/outboundfeeds/rss-latest/?outputType=xml
Sitemap: https://www.oregonlive.com/arc/outboundfeeds/sitemap-index/?outputType=xml
Sitemap: https://www.oregonlive.com/arc/outboundfeeds/news-sitemap-index/?outputType=xml
Sitemap: https://www.oregonlive.com/recommendations/sitemap.xml

User-agent: Google-Extended
Disallow: /

User-agent: GPTBot
Disallow: /
 
User-agent: CCBot
Disallow: /

User-agent: ChatGPT-User
Disallow: /

User-agent: Amazonbot
Disallow: /

User-agent: FacebookBot
Disallow: /

User-agent: anthropic-ai
Disallow: /

User-agent: Claude-web
Disallow: /

User-agent: cohere-ai
Disallow: /

User-agent: Omgilibot
Disallow: /

User-Agent: PerplexityBot
Disallow: /

User-agent: Bingbot
Disallow: /home-beta/
Disallow: /test/
Disallow: /preview/
Disallow: /staging/
Disallow: /clients/
Disallow: /auctions/
Disallow: /cgi-bin/
Disallow: /printer/
Disallow: /*/print.html*
Disallow: /*/print.ssf*
Disallow: /landingpages/
Disallow: /oil-spill-reports/
Disallow: /premium/
Disallow: /contests/scrape/
Disallow: /dhtml/
Disallow: /oregonian-test/
Disallow: /opinion/index.ssf/2011/01/bring_osu_to_portland_educatio.html
Disallow: /puzzles-palace/
Disallow: /pacific-northwest-news/index.ssf/2010/10/woodburn_police_ask_for_help_in_locating_two_runaway_teens.html
Disallow: /toprailapp/
Disallow: /newsletters/thank_you.html
Disallow: /*mt-preview-*
Disallow: /portland/2016/12/who_is_portlands_mysterious_li.html
Disallow: /today/2013/07/school_official_blames_sleepin.html
Disallow: /opinion/2018/06/when_fathers_day_cards_dont_qu.html
Disallow: /beaverton/2010/11/recapping_the_states_case_in_the_beaverton_murder_trial.html
Disallow: /portland/2011/01/portland_woman_upset_by_attack.html
Disallow: /crime/2020/11/new-mexico-man-who-drove-back-and-forth-past-home-of-ex-wife-in-portland-after-making-online-threats-found-guilty-of-stalking-and-cyberstalking.html
Disallow: /clackamascounty/2012/04/former_clackamas_county_sherif_1.html
Disallow: /portland/2017/01/lincoln_high_school_student_ac.html
Disallow: /portland/2017/01/lincoln_high_school_student_ar.html

User-agent: Googlebot
Disallow: /home-beta/
Disallow: /test/
Disallow: /preview/
Disallow: /staging/
Disallow: /clients/
Disallow: /auctions/
Disallow: /cgi-bin/
Disallow: /printer/
Disallow: /*/print.html*
Disallow: /*/print.ssf*
Disallow: /landingpages/
Disallow: /oil-spill-reports/
Disallow: /premium/
Disallow: /contests/scrape/
Disallow: /dhtml/
Disallow: /oregonian-test/
Disallow: /opinion/index.ssf/2011/01/bring_osu_to_portland_educatio.html
Disallow: /puzzles-palace/
Disallow: /pacific-northwest-news/index.ssf/2010/10/woodburn_police_ask_for_help_in_locating_two_runaway_teens.html
Disallow: /toprailapp/
Disallow: /closures/index.ssf?other
Disallow: /closures/*.ssf?*
Disallow: /newsletters/thank_you.html
Disallow: /*mt-preview-*
Disallow: /portland/2016/12/who_is_portlands_mysterious_li.html
Disallow: /today/2013/07/school_official_blames_sleepin.html
Disallow: /opinion/2018/06/when_fathers_day_cards_dont_qu.html
Disallow: /beaverton/2010/11/recapping_the_states_case_in_the_beaverton_murder_trial.html
Disallow: /portland/2011/01/portland_woman_upset_by_attack.html
Disallow: /crime/2020/11/new-mexico-man-who-drove-back-and-forth-past-home-of-ex-wife-in-portland-after-making-online-threats-found-guilty-of-stalking-and-cyberstalking.html
Disallow: /clackamascounty/2012/04/former_clackamas_county_sherif_1.html
Disallow: /portland/2017/01/lincoln_high_school_student_ac.html
Disallow: /portland/2017/01/lincoln_high_school_student_ar.html

User-agent: ia_archiver
Disallow: /home-beta/
Disallow: /test/
Disallow: /preview/
Disallow: /staging/
Disallow: /clients/
Disallow: /auctions/
Disallow: /cgi-bin/
Disallow: /printer/
Disallow: /*/print.html*
Disallow: /*/print.ssf*
Disallow: /landingpages/
Disallow: /oil-spill-reports/
Disallow: /premium/
Disallow: /contests/scrape/
Disallow: /dhtml/
Disallow: /oregonian-test/
Disallow: /opinion/index.ssf/2011/01/bring_osu_to_portland_educatio.html
Disallow: /puzzles-palace/
Disallow: /pacific-northwest-news/index.ssf/2010/10/woodburn_police_ask_for_help_in_locating_two_runaway_teens.html
Disallow: /toprailapp/
Disallow: /closures/index.ssf?other
Disallow: /closures/*.ssf?*
Disallow: /newsletters/thank_you.html
Disallow: /*mt-preview-*
Disallow: /portland/2016/12/who_is_portlands_mysterious_li.html
Disallow: /today/2013/07/school_official_blames_sleepin.html
Disallow: /opinion/2018/06/when_fathers_day_cards_dont_qu.html
Disallow: /beaverton/2010/11/recapping_the_states_case_in_the_beaverton_murder_trial.html
Disallow: /crime/2020/11/new-mexico-man-who-drove-back-and-forth-past-home-of-ex-wife-in-portland-after-making-online-threats-found-guilty-of-stalking-and-cyberstalking.html
Disallow: /clackamascounty/2012/04/former_clackamas_county_sherif_1.html
Disallow: /portland/2017/01/lincoln_high_school_student_ac.html
Disallow: /portland/2017/01/lincoln_high_school_student_ar.html

User-agent: proximic
Disallow: /home-beta/
Disallow: /test/
Disallow: /portland/2016/12/who_is_portlands_mysterious_li.html
Disallow: /opinion/2018/06/when_fathers_day_cards_dont_qu.html
Disallow: /beaverton/2010/11/recapping_the_states_case_in_the_beaverton_murder_trial.html

User-agent: Slurp
Disallow: /home-beta/
Disallow: /test/
Disallow: /preview/
Disallow: /staging/
Disallow: /clients/
Disallow: /auctions/
Disallow: /cgi-bin/
Disallow: /printer/
Disallow: /*/print.html*
Disallow: /*/print.ssf*
Disallow: /landingpages/
Disallow: /oil-spill-reports/
Disallow: /premium/
Disallow: /contests/scrape/
Disallow: /dhtml/
Disallow: /oregonian-test/
Disallow: /opinion/index.ssf/2011/01/bring_osu_to_portland_educatio.html
Disallow: /puzzles-palace/
Disallow: /pacific-northwest-news/index.ssf/2010/10/woodburn_police_ask_for_help_in_locating_two_runaway_teens.html
Disallow: /toprailapp/
Disallow: /newsletters/thank_you.html
Disallow: /*mt-preview-*
Disallow: /portland/2016/12/who_is_portlands_mysterious_li.html
Disallow: /today/2013/07/school_official_blames_sleepin.html
Disallow: /opinion/2018/06/when_fathers_day_cards_dont_qu.html
Disallow: /beaverton/2010/11/recapping_the_states_case_in_the_beaverton_murder_trial.html
Disallow: /portland/2011/01/portland_woman_upset_by_attack.html
Disallow: /crime/2020/11/new-mexico-man-who-drove-back-and-forth-past-home-of-ex-wife-in-portland-after-making-online-threats-found-guilty-of-stalking-and-cyberstalking.html
Disallow: /clackamascounty/2012/04/former_clackamas_county_sherif_1.html
Disallow: /portland/2017/01/lincoln_high_school_student_ac.html
Disallow: /portland/2017/01/lincoln_high_school_student_ar.html

User-agent: Twitterbot
Disallow: /home-beta/
Disallow: /test/
Disallow: /preview/
Disallow: /staging/
Disallow: /clients/
Disallow: /auctions/
Disallow: /cgi-bin/
Disallow: /printer/
Disallow: /*/print.html*
Disallow: /*/print.ssf*
Disallow: /landingpages/
Disallow: /oil-spill-reports/
Disallow: /premium/
Disallow: /contests/scrape/
Disallow: /dhtml/
Disallow: /oregonian-test/
Disallow: /opinion/index.ssf/2011/01/bring_osu_to_portland_educatio.html
Disallow: /puzzles-palace/
Disallow: /pacific-northwest-news/index.ssf/2010/10/woodburn_police_ask_for_help_in_locating_two_runaway_teens.html
Disallow: /toprailapp/
Disallow: /newsletters/thank_you.html
Disallow: /*mt-preview-*
Disallow: /portland/2016/12/who_is_portlands_mysterious_li.html
Disallow: /today/2013/07/school_official_blames_sleepin.html
Disallow: /opinion/2018/06/when_fathers_day_cards_dont_qu.html
Disallow: /beaverton/2010/11/recapping_the_states_case_in_the_beaverton_murder_trial.html
Disallow: /crime/2020/11/new-mexico-man-who-drove-back-and-forth-past-home-of-ex-wife-in-portland-after-making-online-threats-found-guilty-of-stalking-and-cyberstalking.html
Disallow: /clackamascounty/2012/04/former_clackamas_county_sherif_1.html
Disallow: /portland/2017/01/lincoln_high_school_student_ac.html
Disallow: /portland/2017/01/lincoln_high_school_student_ar.html

User-agent: *
Disallow: /digitalsubscription/imagedownload/

User-agent: *
Disallow: /for-you-parsely/
Disallow: /for-you-blueconic/

