User-Agent: *
Allow: /HigherLogic/System/DownloadDocument.ashx
Allow: /HigherLogic/System/DownloadDocumentFile.ashx
Allow: /higherlogic/system/downloaddocument.ashx
Allow: /higherlogic/system/downloaddocumentfile.ashx
Disallow: /ScriptResource.axd  
Disallow: /WebResource.axd 
Disallow: /*.axd$
Disallow: /*/SearchLibrary
Disallow: /*/searchlibrary
Disallow: /*/PrintMessage
Disallow: /*/printmessage
Disallow: /HigherLogic/
Disallow: /higherlogic/
Disallow: /*/RSS
Disallow: /*/rss
Disallow: /*postreply*
Disallow: /*postamessage*
Disallow: /*postmessage*
Disallow: /*forwardmessages*
Disallow: /apps/group_public/calendar.php