User-agent: GPTBot
Disallow: /
User-agent: ChatGPT-User
Disallow: /
User-agent: CCBot
Disallow: /
User-agent: anthropic-ai
Disallow: /
User-agent: TextBulkerBot
Disallow: /

Sitemap: https://corporate.ovhcloud.com/asia/corporate.ovhcloud.com_en-142_sitemap.xml
Sitemap: https://corporate.ovhcloud.com/de/corporate.ovhcloud.com_de_sitemap.xml
Sitemap: https://corporate.ovhcloud.com/en-au/corporate.ovhcloud.com_en-au_sitemap.xml
Sitemap: https://corporate.ovhcloud.com/en-ca/corporate.ovhcloud.com_en-ca_sitemap.xml
Sitemap: https://corporate.ovhcloud.com/en-gb/corporate.ovhcloud.com_en-gb_sitemap.xml
Sitemap: https://corporate.ovhcloud.com/en-ie/corporate.ovhcloud.com_en-ie_sitemap.xml
Sitemap: https://corporate.ovhcloud.com/en-in/corporate.ovhcloud.com_en-in_sitemap.xml
Sitemap: https://corporate.ovhcloud.com/en-sg/corporate.ovhcloud.com_en-sg_sitemap.xml
Sitemap: https://corporate.ovhcloud.com/en/corporate.ovhcloud.com_en_sitemap.xml
Sitemap: https://corporate.ovhcloud.com/es-es/corporate.ovhcloud.com_es_sitemap.xml
Sitemap: https://corporate.ovhcloud.com/es/corporate.ovhcloud.com_es-419_sitemap.xml
Sitemap: https://corporate.ovhcloud.com/fr-ca/corporate.ovhcloud.com_fr-ca_sitemap.xml
Sitemap: https://corporate.ovhcloud.com/fr-ma/corporate.ovhcloud.com_fr-ma_sitemap.xml
Sitemap: https://corporate.ovhcloud.com/fr-sn/corporate.ovhcloud.com_fr-sn_sitemap.xml
Sitemap: https://corporate.ovhcloud.com/fr-tn/corporate.ovhcloud.com_fr-tn_sitemap.xml
Sitemap: https://corporate.ovhcloud.com/fr/corporate.ovhcloud.com_fr_sitemap.xml
Sitemap: https://corporate.ovhcloud.com/it/corporate.ovhcloud.com_it_sitemap.xml
Sitemap: https://corporate.ovhcloud.com/nl/corporate.ovhcloud.com_nl_sitemap.xml
Sitemap: https://corporate.ovhcloud.com/pl/corporate.ovhcloud.com_pl_sitemap.xml
Sitemap: https://corporate.ovhcloud.com/pt/corporate.ovhcloud.com_pt-pt_sitemap.xml