Sitemap: https://customers.smartrecruiters.com/sitemapindex.xml
Sitemap: https://customers.smartrecruiters.com/kb/sitemap-index.xml
User-agent: *
Disallow: /entry/
Disallow: /messages/
Disallow: /profile/comments/
Disallow: /profile/discussions/
Disallow: /search/
Disallow: /sso/
Disallow: /sso
