User-agent: *
Disallow: /cordova
Allow: /
Allow: /android
Allow: /ios
Allow: /react-native
Allow: /flutter
Sitemap: https://developer.onewelcome.com/sitemap.txt
Sitemap: https://developer.onewelcome.com/android/sitemap.txt
Sitemap: https://developer.onewelcome.com/ios/sitemap.txt
Sitemap: https://developer.onewelcome.com/react-native/sitemap.txt
Sitemap: https://developer.onewelcome.com/flutter/sitemap.txt
Sitemap: https://developer.onewelcome.com/cordova/sitemap.txt