User-agent: *
Disallow: /*/adyen
Disallow: /*/aib-af
Disallow: /*/aib-bf
Disallow: /*/amex-express-checkout
Disallow: /*/apac
Disallow: /*/archive
Disallow: /*/braintree/articles/au/change-your-bank-account/
Disallow: /*/braintree/articles/au/chargebacks-retrievals-prearbs/
Disallow: /*/braintree/articles/au/overview/
Disallow: /*/braintree/articles/au/pricing-fees/
Disallow: /*/braintree/articles/au/reconciliation/
Disallow: /*/braintree/articles/au/statements/
Disallow: /*/braintree/articles/au/transactions/
Disallow: /*/braintree/articles/au/transactions/accepted-payment-methods/
Disallow: /*/braintree/articles/au/transactions/descriptors/
Disallow: /*/braintree/articles/au/settlement-funding-timeline/
Disallow: /*/braintree/articles/guides/single-sign-on-sso/
Disallow: /*/br
Disallow: /*/braintree/docs/guides/apple-pay/decrypted-server-side/
Disallow: /*/braintree/docs/guides/apple-pay/provision-for-decrypted/
Disallow: /*/braintree/docs/guides/barcode-scanning/
Disallow: /*/braintree/docs/guides/credit-cards/submit-for-partial-settlement/
Disallow: /*/braintree/docs/guides/disputes/paypal-disputes/
Disallow: /*/braintree/docs/guides/examples/
Disallow: /*/braintree/docs/guides/extend/forward-api/braintree-api-forwarding/
Disallow: /*/braintree/docs/guides/facebook-login/
Disallow: /*/braintree/docs/guides/hosted-fields/upgrading-from-custom/
Disallow: /*/braintree/docs/guides/initial-theming-and-configuration/
Disallow: /*/braintree/docs/guides/installation-without-cocoapods/
Disallow: /*/braintree/docs/guides/launch-checklist/
Disallow: /*/braintree/docs/guides/local-payment-methods/client-side-smart/
Disallow: /*/braintree/docs/guides/masterpass/client-side/
Disallow: /*/braintree/docs/guides/overview/
Disallow: /*/braintree/docs/guides/paypal/paypal-credit/
Disallow: /*/braintree/docs/guides/paypal-commerce-delegate/
Disallow: /*/braintree/docs/guides/product-cards/
Disallow: /*/braintree/docs/guides/setup/
Disallow: /*/braintree/docs/guides/url-specs/
Disallow: /*/braintree/docs/guides/venmo-one-touch/
Disallow: /*/braintree/docs/guidesvenmo/submit-for-partial-settlement
Disallow: /*/braintree/docs/reference/general/airline-itinerary-data
Disallow: /*/braintree/docs/reference/general/association-filtering
Disallow: /*/braintree/docs/reference/general/level-2-and-3-processing
Disallow: /*/braintree/docs/reference/general/network-tokenization/
Disallow: /*/braintree/docs/reference/general/webhooks/local-payment-methods/
Disallow: /*/braintree/docs/reference/general/paypal-advanced-options/payee/
Disallow: /*/braintree/docs/reference/general/paypal-advanced-options/paypal-order/
Disallow: /*/braintree/docs/reference/general/lodging-data
Disallow: /*/braintree/docs/start/checkout-ui-comparison
Disallow: /*/braintree/docs/test-pages/main
Disallow: /*/braintree-marketplace/
Disallow: /*/chase
Disallow: /*/elo
Disallow: /*/express-checkout
Disallow: /*/functions
Disallow: /*/hipercard-and-hiper
Disallow: /*/limited-release
Disallow: /*/mass-pay
Disallow: /*/mobile
Disallow: /*/moneris
Disallow: /*/nab
Disallow: /*/paypal-commerce-channel-api
Disallow: /*/paypal-commerce-ios
Disallow: /*/permissions-service
Disallow: /*/reference/request/credit-card-verification/create/
Disallow: /*/reference/request/transaction/update-details/
Disallow: /*/reference/response/transaction-level-fee-report-row/
Disallow: /*/reference/response/amex-express-checkout-card/
Disallow: /*/webapps/
Disallow: /*/wells-flat
Disallow: /*/wells-ic
Sitemap: https://www.example.com/sitemap.xml
Host: https://developer.paypal.com
