# --------------------------------------------------
# Robots.txt file for https://www.manageengine.com
# Author:  Webmaster
# Last Updated Date: 12/07/2022
# --------------------------------------------------

User-Agent: *
Disallow: /cgi-bin/
Disallow: /products/jmx_studio/42112542/
Disallow: /products/jmx_studio/52914950/
Disallow: /products/jmx_studio/93763334.html
Disallow: /license/
Disallow: /licensing/
Disallow: /linkchecker/
Disallow: /products/service-desk/pricing-od.html
Disallow: /wifimanager/
Disallow: /qengine/
Disallow: /ims/
Disallow: /mspcenterlite/
Disallow: /ems/images/tools/
Disallow: /facilities-desk/
Disallow: /msp-center/
Disallow: /vqmanager/
Disallow: /wireless-network-management/
Disallow: /security-manager/
Disallow: /LB-monitoring.html
Disallow: /desktop-management-msp/help/
Disallow: /store/opstor.html
Disallow: /partner-portal/
Disallow: /static/
Disallow: /digital-risk-analyzer/help/
Disallow: /domain-risk-analyzer/help/
Disallow: /data-security/download-confirm.html
Disallow: /products/desktop-central/download_confirm.html
Disallow: /products/desktop-central/mdm-samsung-knox.html
Disallow: /products/desktop-central/get-quote-thanks.html
Disallow: /products/service-desk/download_confirm.html
Disallow: /products/service-desk/hdi15offer.html
Disallow: /products/service-desk/index7.html
Disallow: /products/service-desk/test-download.html
Disallow: /products/service-desk/get-quote-thanks.html
Disallow: /products/service-desk/get-quote1.html
Disallow: /products/service-desk/need-features-thanks.html
Disallow: /products/service-desk/request-support-thanks.html
Disallow: /products/service-desk/uninstall-feedback-thanks.html
Disallow: /products/security-manager/download-confirm.html
Disallow: /products/security-manager/need-fetures-thanks.html
Disallow: /products/security-manager/request-support-thanks.html
Disallow: /products/security-manager/get-quote-thanks.html
Disallow: /products/device-expert/download-confirm.html
Disallow: /products/device-expert/need-fetures-thanks.html
Disallow: /products/device-expert/request-support-thanks.html
Disallow: /products/device-expert/get-quote-thanks.html
Disallow: /products/passwordmanagerpro/download_confirm.html
Disallow: /products/passwordmanagerpro/need-fetures-thanks.html
Disallow: /products/active-directory-audit/download_confirm.html
Disallow: /products/active-directory-audit/need-features-thanks.html
Disallow: /products/active-directory-audit/request-support-thanks.html
Disallow: /products/active-directory-audit/get-quote-thanks.html
Disallow: /products/ad-manager/download_confirm.html
Disallow: /products/ad-manager/need-features-thanks.html
Disallow: /products/ad-manager/request-support-thanks.html
Disallow: /products/ad-manager/get-quote-thanks.html
Disallow: /products/ad-manager/index2.html
Disallow: /products/asset-explorer/download_confirm.html
Disallow: /products/eventlog/download_confirm.html
Disallow: /products/eventlog/request-support-thanks.html
Disallow: /products/eventlog/need-feature-thanks.html
Disallow: /products/eventlog/get-quote-thankyou.html
Disallow: /products/exchange-reports/need-features-thanks.html
Disallow: /products/exchange-reports/request-support-thanks.html
Disallow: /products/exchange-reports/download_confirm.html
Disallow: /products/exchange-reports/get-quote-thanks.html
Disallow: /products/self-service-password/request-support-thanks.html
Disallow: /products/self-service-password/need-features-thanks.html
Disallow: /products/self-service-password/download_confirm.html
Disallow: /products/self-service-password/get-quote-thanks.html
Disallow: /products/service-desk-msp/request-support-thanks.html
Disallow: /products/service-desk-msp/need-features-thanks.html
Disallow: /products/msp-center/get-quote-thanks.html
Disallow: /products/msp-center/need-features-thanks.html
Disallow: /products/msp-center/download-confirm.html
Disallow: /products/asset-explorer/need-features-thanks.html
Disallow: /products/asset-explorer/request-support-thanks.html
Disallow: /products/asset-explorer/get-quote-thanks.html
Disallow: /it360/request-support-thanks.html
Disallow: /it360/download_confirm.html
Disallow: /it360/get-quote-thanks.html
Disallow: /products/opstor/download_confirm.html
Disallow: /products/opstor/get-quote-thanks.html
Disallow: /products/desktop-central/create-ios-apns-certificate.html
Disallow: /products/ad-manager1/
Disallow: /products/active-directory-audit1/
Disallow: /news/netezza-partners-with-adventnet.html
Disallow: /news/msp-resellers-in-UK.html
Disallow: /sdp-addon-offer.html
Disallow: /products/service-desk1/
Disallow: /products/service-desk2/
Disallow: /products/desktop-central1/
Disallow: /products/self-service-password1/
Disallow: /_appmgmt.html
Disallow: /products/desktop-central/mdm-pre-defined-user-roles.html 
Disallow: /products/device-expert/license-registration.html
Disallow: /products/service-desk/readme-9.0.html
Disallow: /products/service-desk/license-registration.html
Disallow: /products/service-desk-msp/license-registration.html
Disallow: /products/eventlog/license-registration.html
Disallow: /products/opstor/license-registration.html
Disallow: /products/support-center/license-registration.html
Disallow: /products/os-deployer/license-registration.html
Disallow: /products/asset-explorer/license-registration.html
Disallow: /products/security-manager/license-registration.html
Disallow: /products/desktop-central/license-registration.html
Disallow: /products/service-desk/comparison-confirm.html
Disallow: /products/service-desk/servicedesk-plus-itil.html
Disallow: /index1.html
Disallow: /index2.html
Disallow: /products/service-desk/share-vacation-pics-win.html
Disallow: /products/service-desk/vacation-pics-gallery.html
Disallow: /products/service-desk/upload-vacation-pics.html
Disallow: /community/
Disallow: /opstor-old/
Disallow: /products/service-desk/upgrade-free-edition.html
Disallow: /products/service-desk/beta-readme-9.0.html
Disallow: /products/service-desk/sdp-beta.html
Disallow: /products/passwordmanagerpro/index1.html
Disallow: /products/service-desk/giant-leap-it.html
Disallow: /products/free-windows-tools/download1.html
Disallow: /products/opstor/download1.html
Disallow: /products/service-desk/download1.html
Disallow: /free-ping-tool/free-ping-tool-index1.html
Disallow: /free-ping-tool/free-ping-tool-index2.html
Disallow: /dcim/index.html
Disallow: /products/service-desk-msp/free-it-help-desk-sdp-msp.html
Disallow: /products/service-desk/Pink15offer.html
Disallow: /it360/get-quote.html
Disallow: /it360-msp/get-quote.html
Disallow: /products/service-desk/index-plan.html
Disallow: /products/service-desk/desktop-central-plugin-confirm.html
Disallow: /products/service-desk/servicedesk-plus-year-end-offer.html
Disallow: /products/service-desk/request-download.html
Disallow: /products/service-desk/index16.html
Disallow: /products/service-desk/sign_up.html
Disallow: /testpage.html
Disallow: /products/service-desk-msp/whats-new-servicedeskplus-msp-9.0.html
Disallow: /signup-user.html
Disallow: /signup-user-thanks.html
Disallow: /products/support-center/advanced-analytics.html
Disallow: /reports/
Disallow: /complimentary-product-license.html
Disallow: /community/community-survey.html
Disallow: /ems/events/
Disallow: /products/service-desk/importance-service-catalogue.pptx
Disallow: /products/service-desk/service-catalog-presentation.zip
Disallow: /products/service-desk-mobile/
Disallow: /products/service-desk/standard-free-thanks.html
Disallow: /events/2012/australia/
Disallow: /web-double-optin-confirmation.html
Disallow: /privacy.html
Disallow: /privacy/privacy.html
Disallow: /privacy/cookie-policy.html
Disallow: /privacy/zoho-group.html
Disallow: /privacy/sub-processors.html
Disallow: /restricted-domains.txt
Disallow: /products/service-desk/sdp-free-thanks.html
Disallow: /products/service-desk-msp/sdpmsp-free-thanks.html
Disallow: /products/active-directory-audit/user-behavior-analytics-ebook.pdf
Disallow: /products/active-directory-audit/user-behavior-analytics-guide.pdf
Disallow: /data-security/pdf/insider-threat-management-handbook.pdf
Disallow: /analytics-plus/docs/e-book-on-the-secret-to-creating-powerful-dashboards.pdf
Disallow: /analytics-plus/docs/e-book-on-10-must-have-reports-for-help-desk-manager.pdf
Disallow: /analytics-plus/docs/e-book-on-5-revenue-metrics-every-msp-should-track.pdf
Disallow: /analytics-plus/docs/choosing-the-right-chart-for-your-it-data.pdf
Disallow: /analytics-plus/docs/e-book-seven-reasons-your-help-desk-needs-analytics.pdf
Disallow: /analytics-plus/docs/e-book-6-ways-analytics-can-facilitate-proactive-it-operations-management.pdf
Disallow: /analytics-plus/docs/e-book-on-implement_analytics.pdf
Disallow: /analytics-plus/docs/e-book-on-5-cost-saving-opportunities-asset-life-cycle.pdf
Disallow: /analytics-plus/docs/ebook_resolve_your_helpdesk_biggest_challenges_with_analytics.pdf
Disallow: /analytics-plus/docs/e-book-on-seven-missing-metrics.pdf
Disallow: /analytics-plus/docs/e-book-data-democratization-guide.pdf
Disallow: /analytics-plus/docs/ebook_5_ways_to_create_a_chaos-free_noc.pdf
Disallow: /analytics-plus/docs/e-book-10-secret-strategies-to-supercharge-it-reporting.pdf
Disallow: /sdp-sign/
Disallow: /products/os-deployer/download_confirm.html
Disallow: /network-monitoring/netherlands-vabi-casestudy.pdf
Disallow: /network-monitoring/the-building-company.pdf
Disallow: /network-monitoring/basics-of-network-monitoring-ebook.pdf
Disallow: /network-monitoring/help/what-is-dpi.html
Disallow: /network-monitoring/help/understanding-dpi-in-opmanager.html
Disallow: /network-monitoring/help/configuration-dpi.html
Disallow: /network-monitoring/help/inventory-2-dpi.html
Disallow: /network-monitoring/help/reports-dpi.html
Disallow: /network-monitoring/help/affiliates.html
Disallow: /network-monitoring-msp/network-performance-monitoring.html
Disallow: /network-monitoring-msp/network-device-monitoring.html
Disallow: /network-monitoring-msp/agent-based-monitoring.html
Disallow: /network-monitoring-msp/availability-monitoring.html
Disallow: /network-monitoring-msp/network-uptime-monitoring.html
Disallow: /network-monitoring-msp/network-packet-loss-monitoring.html
Disallow: /network-monitoring-msp/network-activity-monitoring.html
Disallow: /network-monitoring-msp/interface-monitoring.html
Disallow: /network-monitoring-msp/network-testing-tools.html
Disallow: /network-monitoring-msp/network-assessment-tools.html
Disallow: /network-monitoring-msp/lan-management.html
Disallow: /network-monitoring-msp/hardware-monitoring.html
Disallow: /network-monitoring-msp/disk-space-monitor.html
Disallow: /network-monitoring-msp/cpu-monitoring.html
Disallow: /network-monitoring-msp/uptime-monitoring.html
Disallow: /network-monitoring-msp/cpu-usage-monitor.html
Disallow: /network-monitoring-msp/cpu-temperature-monitor.html
Disallow: /network-monitoring-msp/cpu-memory-disk.html
Disallow: /network-monitoring-msp/memory-monitoring.html
Disallow: /network-monitoring-msp/router-monitoring.html
Disallow: /network-monitoring-msp/switch-monitoring.html
Disallow: /network-monitoring-msp/switch-management-software.html
Disallow: /network-monitoring-msp/ethernet-monitoring.html
Disallow: /network-monitoring-msp/url-monitoring.html
Disallow: /network-monitoring-msp/lan-monitoring.html
Disallow: /network-monitoring-msp/ip-sla-monitoring.html
Disallow: /network-monitoring-msp/configure-wan-monitoring.html
Disallow: /network-monitoring-msp/wan-management.html
Disallow: /network-monitoring-msp/voip-monitor.html
Disallow: /network-monitoring-msp/network-latency-monitoring.html
Disallow: /network-monitoring-msp/system-performance-monitoring.html
Disallow: /network-monitoring-msp/load-balancer-monitoring.html
Disallow: /network-monitoring-msp/vpn-monitoring.html
Disallow: /network-monitoring-msp/wmi-monitoring.html
Disallow: /network-monitoring-msp/windows-process-monitor.html
Disallow: /network-monitoring-msp/wireless-network-monitoring.html
Disallow: /network-monitoring-msp/wlc-monitoring.html
Disallow: /network-monitoring-msp/ups-monitoring.html
Disallow: /network-monitoring-msp/printer-monitoring.html
Disallow: /network-monitoring-msp/network-printer-management.html
Disallow: /network-monitoring-msp/network-device-discovery.html
Disallow: /network-monitoring-msp/cisco-monitoring.html
Disallow: /network-monitoring-msp/cisco-meraki-monitoring.html
Disallow: /network-monitoring-msp/cisco-ucs-monitoring.html
Disallow: /network-monitoring-msp/cisco-port-monitor.html
Disallow: /network-monitoring-msp/cisco-switch-stack-monitoring.html
Disallow: /network-monitoring-msp/ibm-monitoring.html
Disallow: /network-monitoring-msp/syslog-monitoring.html
Disallow: /network-monitoring-msp/ipmi-monitoring.html
Disallow: /network-monitoring-msp/snmp-trap-monitor.html
Disallow: /network-monitoring-msp/3com-switch-port-monitoring.html
Disallow: /network-monitoring-msp/fortigate-firewall-performance-monitoring.html
Disallow: /network-monitoring-msp/juniper-network-monitoring.html
Disallow: /network-monitoring-msp/noc-monitoring.html
Disallow: /network-monitoring-msp/server-monitoring.html
Disallow: /network-monitoring-msp/server-uptime-monitoring.html
Disallow: /network-monitoring-msp/windows-server-monitoring.html
Disallow: /network-monitoring-msp/server-health-monitor.html
Disallow: /network-monitoring-msp/server-log-management-software.html
Disallow: /network-monitoring-msp/systems-management.html
Disallow: /network-monitoring-msp/hyper-v-management-tools.html
Disallow: /network-monitoring-msp/vmware-monitoring.html
Disallow: /network-monitoring-msp/vmware-esx-host-monitoring.html
Disallow: /network-monitoring-msp/virtual-machine-monitoring.html
Disallow: /network-monitoring-msp/virtual-network-management.html
Disallow: /network-monitoring-msp/vmware-esxi-monitoring-tools.html
Disallow: /network-monitoring-msp/vsphere-performance-monitoring.html
Disallow: /network-monitoring-msp/hyperv-monitoring.html
Disallow: /network-monitoring-msp/hyper-v-performance-monitoring.html
Disallow: /network-monitoring-msp/citrix-xenserver-monitoring.html
Disallow: /network-monitoring-msp/nutanix-monitoring.html
Disallow: /network-monitoring-msp/hyperconverged-infrastructure.html
Disallow: /network-monitoring-msp/virtualization-monitoring-dashboard.html
Disallow: /network-monitoring-msp/operating-system-monitoring.html
Disallow: /network-monitoring-msp/windows-network-monitor.html
Disallow: /network-monitoring-msp/linux-network-monitor.html
Disallow: /network-monitoring-msp/dell-server-monitoring.html
Disallow: /network-monitoring-msp/hp-server-monitoring.html
Disallow: /network-monitoring-msp/eventlog-monitoring.html
Disallow: /network-monitoring-msp/exchange-monitoring.html
Disallow: /network-monitoring-msp/file-folder-monitor.html
Disallow: /network-monitoring-msp/ftp-monitoring.html
Disallow: /network-monitoring-msp/windows-service-monitoring.html
Disallow: /network-monitoring-msp/service-monitoring.html
Disallow: /network-monitoring-msp/process-monitoring.html
Disallow: /network-monitoring-msp/network-mapping.html
Disallow: /network-monitoring-msp/network-planning.html
Disallow: /network-monitoring-msp/network-diagram-software.html
Disallow: /network-monitoring-msp/grouping-network-elements.html
Disallow: /network-monitoring-msp/custom-network-map.html
Disallow: /network-monitoring-msp/network-management-console.html
Disallow: /network-monitoring-msp/network-discovery-tool.html
Disallow: /network-monitoring-msp/network-topology-software.html
Disallow: /network-monitoring-msp/network-visualization.html
Disallow: /network-monitoring-msp/fault-monitoring.html
Disallow: /network-monitoring-msp/network-automation.html
Disallow: /network-monitoring-msp/troubleshooting-network-issues.html
Disallow: /network-monitoring-msp/it-workflow-automation.html
Disallow: /network-monitoring-msp/network-troubleshooting-tools.html
Disallow: /network-monitoring-msp/align-it-to-business.html
Disallow: /network-monitoring-msp/data-center-monitoring.html
Disallow: /network-monitoring-msp/datacenter-management.html
Disallow: /network-monitoring-msp/data-center-networking.html
Disallow: /network-monitoring-msp/datacenter-visual-modeling.html
Disallow: /network-monitoring-msp/san-monitoring.html
Disallow: /network-monitoring-msp/storage-monitoring.html
Disallow: /network-monitoring-msp/storage-raid-management.html
Disallow: /network-monitoring-msp/tape-library-management.html
Disallow: /network-monitoring-msp/storage-capacity-forecasting-planning.html
Disallow: /network-monitoring-msp/san-switch-management.html
Disallow: /network-monitoring-msp/netapp-monitoring.html
Disallow: /network-monitoring-msp/dell-storage-monitoring.html
Disallow: /network-monitoring-msp/ibm-storage-monitoring.html
Disallow: /network-monitoring-msp/network-reporting.html
Disallow: /network-monitoring-msp/network-performance-reporting.html
Disallow: /network-monitoring-msp/network-reports.html
Disallow: /network-monitoring-msp/cisco-aci-monitoring.html
Disallow: /network-monitoring-msp/wireless-monitoring.html
Disallow: /network-monitoring-msp/network-monitoring-alerts.html
Disallow: /products/oputils/demo/opmanager-plugin/opmanager-oputils-plugin.html
Disallow: /products/oputils/demo/ip-address-manager/ip-address-management-demo.html
Disallow: /products/service-desk/cloud/service-desk-database-plans.html
Disallow: /products/service-desk/download-confirm.html
Disallow: /products/oputils/product-roadmap.html
Disallow: /products/desktop-central/iframe-doc.html
Disallow: /products/desktop-central/bugfix-details.html
Disallow: /products/desktop-central/fix-details.html
Disallow: /products/desktop-central/secure-your-endpoints.html
Disallow: /products/desktop-central/checksum-validation.html
Disallow: /products/desktop-central/batch-file-exit-code.html
Disallow: /products/desktop-central/cis-benchmark.html
Disallow: /products/desktop-central/cis-compliance.html
Disallow: /products/desktop-central/get-quote-test.html
Disallow: /products/desktop-central/secure-endpoints.html
Disallow: /products/desktop-central/cve-2021-44515.html
Disallow: /remote-monitoring-management/monitoring/howto.html
Disallow: /remote-monitoring-management/monitoring/faq.html
Disallow: /products/service-desk-msp/download_confirm.html
Disallow: /products/service-desk-msp/fsm-thanks.html
Disallow: /products/service-desk-msp/msp-guide-thanks.html
Disallow: /products/service-desk-msp/demo-thanks.html
Disallow: /products/service-desk-msp/download-thanks.html
Disallow: /products/service-desk-msp/host-ventura-thanks.html
Disallow: /products/service-desk-msp/msp-services.html
Disallow: /products/service-desk-msp/ai-msp-helpdesk.html
Disallow: /products/service-desk-msp/webinar-thanks.html
Disallow: /products/service-desk-msp/get-quote-thanks.html
Disallow: /products/os-deployer/disk-imaging-cdn-test.html
Disallow: /log-management/cybersecurity-outlook-2022.pdf
Disallow: /creativetest/

Sitemap: https://www.manageengine.com/sitemap.xml
