User-agent: GPTBot
Disallow: /
User-agent: ChatGPT-User
Disallow: /
User-agent: CCBot
Disallow: /
User-agent: anthropic-ai
Disallow: /
User-agent: TextBulkerBot
Disallow: /

Sitemap: https://eco.ovhcloud.com/asia/eco.ovhcloud.com_en-142_sitemap.xml
Sitemap: https://eco.ovhcloud.com/de/eco.ovhcloud.com_de_sitemap.xml
Sitemap: https://eco.ovhcloud.com/en-au/eco.ovhcloud.com_en-au_sitemap.xml
Sitemap: https://eco.ovhcloud.com/en-ca/eco.ovhcloud.com_en-ca_sitemap.xml
Sitemap: https://eco.ovhcloud.com/en-gb/eco.ovhcloud.com_en-gb_sitemap.xml
Sitemap: https://eco.ovhcloud.com/en-ie/eco.ovhcloud.com_en-ie_sitemap.xml
Sitemap: https://eco.ovhcloud.com/en-in/eco.ovhcloud.com_en-in_sitemap.xml
Sitemap: https://eco.ovhcloud.com/en-sg/eco.ovhcloud.com_en-sg_sitemap.xml
Sitemap: https://eco.ovhcloud.com/en/eco.ovhcloud.com_en_sitemap.xml
Sitemap: https://eco.ovhcloud.com/es-es/eco.ovhcloud.com_es_sitemap.xml
Sitemap: https://eco.ovhcloud.com/es/eco.ovhcloud.com_es-419_sitemap.xml
Sitemap: https://eco.ovhcloud.com/fr-ca/eco.ovhcloud.com_fr-ca_sitemap.xml
Sitemap: https://eco.ovhcloud.com/fr-ma/eco.ovhcloud.com_fr-ma_sitemap.xml
Sitemap: https://eco.ovhcloud.com/fr-sn/eco.ovhcloud.com_fr-sn_sitemap.xml
Sitemap: https://eco.ovhcloud.com/fr-tn/eco.ovhcloud.com_fr-tn_sitemap.xml
Sitemap: https://eco.ovhcloud.com/fr/eco.ovhcloud.com_fr_sitemap.xml
Sitemap: https://eco.ovhcloud.com/it/eco.ovhcloud.com_it_sitemap.xml
Sitemap: https://eco.ovhcloud.com/nl/eco.ovhcloud.com_nl_sitemap.xml
Sitemap: https://eco.ovhcloud.com/pl/eco.ovhcloud.com_pl_sitemap.xml
Sitemap: https://eco.ovhcloud.com/pt/eco.ovhcloud.com_pt-pt_sitemap.xml