User-agent: *
crawl-delay: 10
# Directories
Disallow: /modules/
Disallow: /themes/
Disallow: /hold
Disallow: /core
Disallow: /digital/
Disallow: /training
Disallow: /thanks-for-your-business/
Disallow: /sites/default/files/webform/
Disallow: /sites/default/files/remit/power/rss/
Disallow: /sites/default/files/remit/gas/rss/
Disallow: /media-centre/asset/download/
Disallow: /spire_thirdlight_browser
# Files
Disallow: /core/CHANGELOG.txt
Disallow: /cron.php
Disallow: /core/INSTALL.mysql.txt
Disallow: /core/INSTALL.pgsql.txt
Disallow: /core/INSTALL.sqlite.txt
Disallow: /core/install.php
Disallow: /core/INSTALL.txt
Disallow: /core/LICENSE.txt
Disallow: /core/MAINTAINERS.txt
Disallow: /README.txt
Disallow: /update.php
Disallow: /core/UPDATE.txt
Disallow: /xmlrpc.php
Disallow: /web.config
Disallow: /images/flash/careers/graduates/template4_flash/scripts/expressInstall.swf
# Paths (clean URLs)
Disallow: /admin/
Disallow: /comment/reply/
Disallow: /filter/tips
Disallow: /node/add/
Disallow: /search/
Disallow: /user/
Disallow: /user/register
Disallow: /user/password
Disallow: /user/login
Disallow: /user/logout
Disallow: /media/oembed
Disallow: /*/media/oembed
Disallow: /media_colourbox/
Disallow: /media_colorbox/
Disallow: /search-results
Disallow: /wp-login.php
Disallow: /energy/transparency
Disallow: /energy/transparency
# Paths (no clean URLs)
Disallow: /index.php/admin/
Disallow: /index.php/comment/reply/
Disallow: /index.php/filter/tips
Disallow: /index.php/node/add/
Disallow: /index.php/search/
Disallow: /index.php/user/password
Disallow: /index.php/user/register
Disallow: /index.php/user/login
Disallow: /index.php/user/logout
Disallow: /index.php/media/oembed
Disallow: /index.php/*/media/oembed
Disallow: /?q=admin/
Disallow: /?q=comment/reply/
Disallow: /?q=filter/tips
Disallow: /?q=node/add/
Disallow: /?q=search/
Disallow: /?q=user/
Disallow: /?q=user/password
Disallow: /?q=user/register
Disallow: /?q=user/login
Disallow: /?q=user/logout
Disallow: /ga-virtual/
Disallow: /for-home/help-support/*?steps=
Disallow: /for-home/help-support/*?*&steps=
Disallow: /for-home/help-centre/*?steps=
Disallow: /for-home/help-centre/*?*&steps=
Disallow: /home/help-centre/*?steps=
Disallow: /home/help-centre/*?*&steps=
Disallow: /help-support/*?steps=
Disallow: /help-support/*?*&steps=
Disallow: /help-support/payments-and-billing$
Disallow: /help-support/meters-and-meter-reading$
Disallow: /help-support/help-topics$
Disallow: /help-support/help-payment-thats-due$
Disallow: /help-support/help-recent-payment$
Disallow: /help-support/your-payments-and-billing$
Disallow: /help-support/help-accessing-myaccount$
Disallow: /help-support/change-my-personal-or-account-details$
Disallow: /help-support/managing-your-energy-plan-and-your-myaccount$
Disallow: /help-support/waiting-current-data-or-lost-connection$
Disallow: /help-support/incorrect-time$
Disallow: /help-support/showing-9999$
Disallow: /help-support/chameleon-3-home-display$
Disallow: /help-support/geo-trio-home-display$
Disallow: /help-support/other-home-displays-eg-accessible-geo-trio$
Disallow: /help-support/ive-got-damaged-or-faulty-home-display$
Disallow: /help-support/help-damaged-or-faulty-meters$
Disallow: /help-support/help-meter-readings$
Disallow: /help-support/help-prepayment-or-payg-meter-problems$
Disallow: /help-support/your-meter-and-meter-readings$
Disallow: /help-support/power-cuts-and-emergency-contacts$
Disallow: /help-support/add-utrn-your-home-display$
Disallow: /help-support/add-utrn-your-meter$
Disallow: /help-support/my-top-hasnt-reached-my-meter-how-do-i-add-my-utrn$
Disallow: /help-support/home-display$
Disallow: /help-support/meter$
Disallow: /help-support/how-do-i-activate-my-emergency-credit$
Disallow: /help-support/help-your-meter-including-smart-pay-you-go$
Disallow: /help-support/help-if-youve-lost-your-energy-supply$
Disallow: /help-support/your-smart-home-devices$
Disallow: /help-support/your-boiler-heater-or-insulation$
Disallow: /help-support/struggling-pay$
Disallow: /help-support/troubleshoot$
Disallow: /help-support/how-can-we-help-you$
Disallow: /help-support/your-smart-pay-you-go-meter$
Disallow: /help-support/contact-us-0$
Disallow: /help-support/reduce-energy-costs$
Disallow: /help-support/do-your-prices-go-1-october-2022$
Disallow: /help-support/copy-do-your-prices-go-1-october-2022$
Disallow: /help-support/no-3$
Disallow: /help-support/no-0-0$
Disallow: /help-support/yes-2$
Disallow: /help-support/do-i-need-give-meter-reading-july$
Disallow: /help-support/copy-other-home-displays-eg-accessible-geo-trio$
Disallow: /help-support/smartview-home-display$
Disallow: /help-support/meters-and-meter-readings$
Disallow: /help-support/smart-pay-you-go$
Disallow: /help-support/smart-pay-you-go-0$
Disallow: /help-support/how-use-your-smart-pay-you-go-meter$
Disallow: /help-support/emergency-credit-smart-payg$
Disallow: /help-support/non-disconnection-times-smart-payg$
Disallow: /help-support/prepayment-meters-not-smart$
Disallow: /help-support/top-ups-and-credits$
Disallow: /help-support/topping-2$
Disallow: /help-support/adding-credit-manually-when-top-fails$
Disallow: /help-support/switching-supplier-payg$
Disallow: /help-support/how-use-my-prepayment-meter$
Disallow: /help-support/topping-key-and-card$
Disallow: /help-support/emergency-credit$
Disallow: /help-support/debt-my-meter$
Disallow: /help-support/non-disconnection-hours$
Disallow: /help-support/smart-meters$
Disallow: /help-support/how-change-move-or-exchange-meter$
Disallow: /help-support/yes-10$
Disallow: /help-support/meter-readings-0$
Disallow: /help-support/when-give-meter-readings$
Disallow: /help-support/yes-12$
Disallow: /help-support/gas$
Disallow: /help-support/when-give-meter-readings-0$
Disallow: /help-support/no-12$
Disallow: /help-support/electricity$
Disallow: /help-support/gas-0$
Disallow: /help-support/my-meter-identity-and-supply-number$
Disallow: /help-support/electricity-0$
Disallow: /help-support/i-cant-get-my-energy-back$
Disallow: /help-support/electricity-meter$
Disallow: /help-support/gas-meter$
Disallow: /help-support/no-2-0$
Disallow: /help-support/electricity-1$
Disallow: /help-support/i-cant-get-my-energy-back-0$
Disallow: /help-support/getting-reconnected$
Disallow: /help-support/how-read-my-meter$
Disallow: /help-support/what-happens-after-you-get-my-meter-reading$
Disallow: /help-support/when-do-i-give-my-final-meter-readings$
Disallow: /help-support/right-one-says-reconnect$
Disallow: /help-support/white$
Disallow: /help-support/electricity-meter-0$
Disallow: /help-support/right-marked-arrows-or-k1-and-k2$
Disallow: /help-support/left-or-under-screen$
Disallow: /help-support/two-grey-buttons$
Disallow: /help-support/two-grey-buttons-0$
Disallow: /help-support/three-grey-buttons$
Disallow: /help-support/green-and-white-b$
Disallow: /help-support/top-card$
Disallow: /help-support/green-and-grey-b$
Disallow: /help-support/green-and-black-b$
Disallow: /help-support/1-blue-and-1-orange-b$
Disallow: /help-support/1-orange-and-2-blue$
Disallow: /help-support/keypad$
Disallow: /help-support/white-0$
Disallow: /help-support/different-colours$
Disallow: /help-support/grey$
Disallow: /help-support/how-give-smart-meter-reading$
Disallow: /help-support/different-colours-0$
Disallow: /help-support/smart-pay-you-go-meter$
Disallow: /help-support/yes-1-0$
Disallow: /help-support/electricity-2$
Disallow: /help-support/top-not-worked-how-add-credit-manually$
Disallow: /help-support/no-0$
Disallow: /help-support/gas-1$
Disallow: /help-support/topping-0$
Disallow: /help-support/yes$
Disallow: /help-support/no-4$
Disallow: /help-support/electricity-3$
Disallow: /help-support/gas-2$
Disallow: /help-support/i-cant-get-my-energy-back-1$
Disallow: /help-support/disconnection-no-energy-supply$
Disallow: /help-support/i-topped-still-no-supply$
Disallow: /help-support/emergency-credit-0$
Disallow: /help-support/yes-i-have-home-device$
Disallow: /help-support/use-emergency-credit$
Disallow: /help-support/electricity-4$
Disallow: /help-support/no-i-dont-have-home-device$
Disallow: /help-support/gas-3$
Disallow: /help-support/faulty-or-damaged-meter$
Disallow: /help-support/meter-readings-1$
Disallow: /help-support/chameleon-3$
Disallow: /help-support/geo-trio$
Disallow: /help-support/other$
Disallow: /help-support/faulty-or-damaged-home-display-0$
Disallow: /help-support/smart-home-display-or-device$
Disallow: /help-support/faulty-or-damaged-home-display$
Disallow: /help-support/yes-1$
Disallow: /help-support/meter-readings-2$
Disallow: /help-support/no-1$
Disallow: /help-support/faulty-or-damaged-home-display-smart$
Disallow: /help-support/meter-and-meter-readings$
Disallow: /help-support/faulty-or-damaged-meter-0$
Disallow: /help-support/faulty-or-damaged-meter-1$
Disallow: /help-support/electricity-5$
Disallow: /help-support/emergency-credit-1$
Disallow: /help-support/prepayment-meter-not-smart$
Disallow: /help-support/gas-4$
Disallow: /help-support/electricity-6$
Disallow: /help-support/gas-5$
Disallow: /help-support/no-energy-supply$
Disallow: /help-support/electricity-7$
Disallow: /help-support/yes-5$
Disallow: /help-support/gas-6$
Disallow: /help-support/faulty-or-damaged-meter-2$
Disallow: /help-support/electricity-key$
Disallow: /help-support/gas-card$
Disallow: /help-support/top-key-or-card$
Disallow: /help-support/need-use-emergency-credit$
Disallow: /help-support/topped-still-no-supply$
Disallow: /help-support/electricity-8$
Disallow: /help-support/gas-7$
Disallow: /help-support/topping$
Disallow: /help-support/how-do-i-get-it$
Disallow: /help-support/how-it-works-0$
Disallow: /help-support/england-or-wales$
Disallow: /help-support/warm-home-discount-faq$
Disallow: /help-support/direct-debit-or-cash-cheque$
Disallow: /help-support/smart-payg-0$
Disallow: /help-support/prepayment-0$
Disallow: /help-support/yes-0$
Disallow: /help-support/no-2$
Disallow: /help-support/fix-problem$
Disallow: /help-support/how-it-gets-paid-and-when$
Disallow: /help-support/how-it-works$
Disallow: /help-support/scotland$
Disallow: /help-support/smart-payg$
Disallow: /help-support/fix-problem-0$
Disallow: /help-support/prepay$
Disallow: /help-support/direct-debit-cash-or-cheque$
Disallow: /help-support/no-energy-supply-or-disconnection$
Disallow: /help-support/electricity-supply$
Disallow: /help-support/yes-7$
Disallow: /help-support/no-8$
Disallow: /help-support/yes-8$
Disallow: /help-support/yes-9$
Disallow: /help-support/something-else$
Disallow: /help-support/smart-pay-you-go-1$
Disallow: /help-support/prepayment-not-smart$
Disallow: /help-support/no-9$
Disallow: /help-support/gas-supply$
Disallow: /help-support/no-10$
Disallow: /help-support/something-else-0$
Disallow: /help-support/prepayment-not-smart-0$
Disallow: /help-support/no-11$
Disallow: /help-support/digital$
Disallow: /help-support/electronic$
Disallow: /help-support/gas-meter-0$
Disallow: /help-support/no$
Disallow: /help-support/smart-meter-or-home-device$
Disallow: /help-support/no-13$
Disallow: /help-support/reduce-my-energy-use$
Disallow: /help-support/get-financial-aid-edf-support-fund$
Disallow: /help-support/reduce-my-energy-bills$
Disallow: /help-support/paying-my-bills$
Disallow: /help-support/get-financial-help-and-advice$
Disallow: /help-support/find-out-what-happens-if-i-dont-pay$
Disallow: /help-support/check-im-getting-all-right-benefits$
Disallow: /help-support/help-pay-and-manage-your-bills$
Disallow: /help-support/managing-my-money-and-bills$
Disallow: /help-support/debt$
Disallow: /help-support/get-help-money-debt-or-bills$
Disallow: /help-support/energy-grants-and-financial-support$
Disallow: /help-support/ebss-400-energy-discount-closes-30th-june-2023$
Disallow: /help-support/government-energy-price-guarantee$
Disallow: /help-support/debt-support-or-help-manage-bills$
Disallow: /help-support/yes-3$
Disallow: /help-support/get-support-debt-and-extra-needs$
Disallow: /help-support/manage-or-pay-bills-after-bereavement$
Disallow: /help-support/extra-support-and-personal-assistance$
Disallow: /help-support/do-i-need-apply$
Disallow: /help-support/what-happens-when-switch-supplier$
Disallow: /help-support/what-happens-when-move-home$
Disallow: /help-support/budget-direct-debit-account-number-starts-67-0$
Disallow: /help-support/bills$
Disallow: /help-support/bills-and-statements$
Disallow: /help-support/understanding-my-bill$
Disallow: /help-support/qr-code-my-bill$
Disallow: /help-support/estimated-bills$
Disallow: /help-support/final-bills$
Disallow: /help-support/when-i-get-my-final-bill$
Disallow: /help-support/paying-my-final-bill$
Disallow: /help-support/direct-debit-whole-amount-account-number-starts-67-0$
Disallow: /help-support/understanding-my-bill-0$
Disallow: /help-support/estimated-bills-0$
Disallow: /help-support/card-cash-or-cheque$
Disallow: /help-support/understanding-my-bill-1$
Disallow: /help-support/estimated-bills-1$
Disallow: /help-support/final-bills-0$
Disallow: /help-support/statements-smart-pay-you-go$
Disallow: /help-support/statements-prepayment-not-smart$
Disallow: /help-support/how-it-works-1$
Disallow: /help-support/budget-direct-debit-account-number-starts-67$
Disallow: /help-support/direct-debit-1$
Disallow: /help-support/payments$
Disallow: /help-support/set-and-first-payments$
Disallow: /help-support/made-me$
Disallow: /help-support/changes-my-payments$
Disallow: /help-support/direct-debit-and-moving-home$
Disallow: /help-support/missed-payments$
Disallow: /help-support/cancellation-and-refunds$
Disallow: /help-support/get-refund$
Disallow: /help-support/how-it-works-2$
Disallow: /help-support/direct-debit-whole-amount-account-number-starts-67$
Disallow: /help-support/set-and-first-payments-0$
Disallow: /help-support/cancellation-and-refunds-0$
Disallow: /help-support/get-refund-0$
Disallow: /help-support/card-cash-or-cheque-how-it-works$
Disallow: /help-support/card-cash-or-cheque-0$
Disallow: /help-support/overdue-payments$
Disallow: /help-support/debt-repayment$
Disallow: /help-support/made-edf$
Disallow: /help-support/why-does-it-change$
Disallow: /help-support/my-tariff-prices$
Disallow: /help-support/yes-4$
Disallow: /help-support/tariffs-0$
Disallow: /help-support/tariffs-and-changing-tariff$
Disallow: /help-support/early-exit-fees$
Disallow: /help-support/my-multi-rate-tariff-eg-economy-7$
Disallow: /help-support/how-tariffs-work$
Disallow: /help-support/no-5$
Disallow: /help-support/id-new-tariff$
Disallow: /help-support/how-and-when-change-tariff$
Disallow: /help-support/yes-6$
Disallow: /help-support/changing-tariff$
Disallow: /help-support/copy-help-pay-and-manage-your-bills$
Disallow: /help-support/ofgem-price-cap$
Disallow: /help-support/price-caps-and-energy-price-guarantee$
Disallow: /help-support/thinking-about-switching-edf$
Disallow: /help-support/switching-edf$
Disallow: /help-support/switching-supplier$
Disallow: /help-support/switch-after-my-cooling-period$
Disallow: /help-support/process-switching-edf$
Disallow: /help-support/when-i-give-meter-readings$
Disallow: /help-support/what-do-if-i-have-problem-my-switch$
Disallow: /help-support/switch-within-my-cooling-period$
Disallow: /help-support/switching-another-supplier$
Disallow: /help-support/leaving-edf$
Disallow: /help-support/closing-my-account$
Disallow: /help-support/tariffs-and-quotes$
Disallow: /help-support/moving$
Disallow: /help-support/moving-home-0$
Disallow: /help-support/yes-11$
Disallow: /help-support/getting-new-tariff$
Disallow: /help-support/no-6$
Disallow: /help-support/my-first-payments-or-top-ups$
Disallow: /help-support/first-meter-reading$
Disallow: /help-support/how-do-i-read-my-meter$
Disallow: /help-support/no-energy-supply-0$
Disallow: /help-support/which-meter-mine$
Disallow: /help-support/my-meter$
Disallow: /help-support/how-my-meter-works$
Disallow: /help-support/faulty-or-damaged-meter-3$
Disallow: /help-support/traditional-not-smart$
Disallow: /help-support/smart$
Disallow: /help-support/energy-rented-property$
Disallow: /help-support/moving-out$
Disallow: /help-support/final-bills-refunds-and-debt$
Disallow: /help-support/smart-payg-1$
Disallow: /help-support/prepayment-not-smart-1$
Disallow: /help-support/no-7$
Disallow: /help-support/making-extra-payment$
Disallow: /help-support/budget-direct-debit-regular-monthly-payments-0$
Disallow: /help-support/budget-direct-debit-regular-monthly-payments-1$
Disallow: /help-support/card-cash-or-cheque-monthly$
Disallow: /help-support/direct-debit-whole-amount-exact-monthly-payments-0$
Disallow: /help-support/im-changing-supplier$
Disallow: /help-support/direct-debit-whole-amount-exact-monthly-payments-1$
Disallow: /help-support/budget-direct-debit-my-account-number-starts-67$
Disallow: /help-support/direct-debit-whole-amount-my-account-number-starts-67$
Disallow: /help-support/smart-pay-you-go-2$
Disallow: /help-support/smart-meter$
Disallow: /help-support/prepayment-meter-non-smart$
Disallow: /help-support/how-change-my-meter-type$
Disallow: /help-support/no-14$
Disallow: /help-support/how-i-get-refund$
Disallow: /help-support/how-use-my-prepayment-meter-0$
Disallow: /help-support/set-and-login$
Disallow: /help-support/my-energy-hub$
Disallow: /help-support/myaccount-0$
Disallow: /help-support/bills-and-payments-0$
Disallow: /help-support/set-and-log$
Disallow: /help-support/app$
Disallow: /help-support/myaccount-and-app$
Disallow: /help-support/tariffs-and-changing-tariff-0$
Disallow: /help-support/final-bills-1$
Disallow: /help-support/using-your-prepayment-meter-0$
Disallow: /help-support/topping-your-electricity-meter$
Disallow: /help-support/emergency-credit-2$
Disallow: /help-support/debt-my-electricity-meter$
Disallow: /help-support/electricity-prepayment-meters$
Disallow: /help-support/debt-my-gas-meter$
Disallow: /help-support/emergency-credit-3$
Disallow: /help-support/topping-your-gas-meter$
Disallow: /help-support/using-your-prepayment-meter$
Disallow: /help-support/gas-prepayment-meters$
Disallow: /help-support/moving-0$
Disallow: /help-support/moving-out-0$
Disallow: /help-support/moving-home-or-switching-supplier$
Disallow: /help-support/refunds-prepayment-meter$
Disallow: /help-support/switching-supplier-0$
Disallow: /help-support/prepayment-meters-not-smart-0$
Disallow: /help-support/how-avoid-running-out-credit$
Disallow: /help-support/getting-started-pay-you-go$
Sitemap: https://www.edfenergy.com/sitemap.xml