User-agent: GPTBot
Disallow: /
User-agent: ChatGPT-User
Disallow: /
User-agent: CCBot
Disallow: /
User-agent: anthropic-ai
Disallow: /
User-agent: TextBulkerBot
Disallow: /

Sitemap: https://events.ovhcloud.com/asia/events.ovhcloud.com_en-142_sitemap.xml
Sitemap: https://events.ovhcloud.com/de/events.ovhcloud.com_de_sitemap.xml
Sitemap: https://events.ovhcloud.com/en-au/events.ovhcloud.com_en-au_sitemap.xml
Sitemap: https://events.ovhcloud.com/en-ca/events.ovhcloud.com_en-ca_sitemap.xml
Sitemap: https://events.ovhcloud.com/en-gb/events.ovhcloud.com_en-gb_sitemap.xml
Sitemap: https://events.ovhcloud.com/en-ie/events.ovhcloud.com_en-ie_sitemap.xml
Sitemap: https://events.ovhcloud.com/en-in/events.ovhcloud.com_en-in_sitemap.xml
Sitemap: https://events.ovhcloud.com/en-sg/events.ovhcloud.com_en-sg_sitemap.xml
Sitemap: https://events.ovhcloud.com/en/events.ovhcloud.com_en_sitemap.xml
Sitemap: https://events.ovhcloud.com/es-es/events.ovhcloud.com_es_sitemap.xml
Sitemap: https://events.ovhcloud.com/es/events.ovhcloud.com_es-419_sitemap.xml
Sitemap: https://events.ovhcloud.com/fr-ca/events.ovhcloud.com_fr-ca_sitemap.xml
Sitemap: https://events.ovhcloud.com/fr-ma/events.ovhcloud.com_fr-ma_sitemap.xml
Sitemap: https://events.ovhcloud.com/fr-sn/events.ovhcloud.com_fr-sn_sitemap.xml
Sitemap: https://events.ovhcloud.com/fr-tn/events.ovhcloud.com_fr-tn_sitemap.xml
Sitemap: https://events.ovhcloud.com/fr/events.ovhcloud.com_fr_sitemap.xml
Sitemap: https://events.ovhcloud.com/it/events.ovhcloud.com_it_sitemap.xml
Sitemap: https://events.ovhcloud.com/nl/events.ovhcloud.com_nl_sitemap.xml
Sitemap: https://events.ovhcloud.com/pl/events.ovhcloud.com_pl_sitemap.xml
Sitemap: https://events.ovhcloud.com/pt/events.ovhcloud.com_pt-pt_sitemap.xml
