User-Agent: *
Disallow: /mojefixly
Disallow: /autoryzacja
Disallow: /profil/*/dodaj-opinie
Disallow: /api
Disallow: /niezbednik/wp-admin
Disallow: /blog/wp-admin
Disallow: /blog/*?s=
Disallow: /blog/*author/
Disallow: /blog/*page/
Disallow: /niezbednik/*?s=
Disallow: /niezbednik/*author/
Disallow: /niezbednik/*page/
Disallow: /c/
Disallow: /blog//xmlrpc.php
Disallow: /blog/xmlrpc.php
Disallow: /niezbednik/xmlrpc.php
Sitemap: https://fixly.pl/sitemap.xml
