User-agent: *
Allow: */assets/Affiliate-Sweden/*
Allow: */assets/Affiliate-France/*
Disallow: /admin
Disallow: /assets
Disallow: */assets/Affiliate-Netherlands/_resampled/*
Disallow: */assets/Flaggen/*
Disallow: */assets/Great-Place-to-Work-Nederland/*
Disallow: */assets/Uploads/_resampled/*
Disallow: /forum/*
Disallow: /Security/*

Disallow: /gptw-ticket/javascript/jquery.form.min.js
Disallow: /gptw-ticket/css/gptw-ticket.css?m=1580984584
Disallow: /silverstripe-dsgvo-cookies/css/cookies.css?m=1622190353
Disallow: /silverstripe-dsgvo-cookies/js/cookies.js?m=1622190353
Disallow: /themes/gptw/css/bootstrap-select.min.css?m=1627911632
Disallow: /themes/gptw/css/bootstrap.min.css
Disallow: /themes/gptw/css/colorGradients.css?m=1630501082
Disallow: /themes/gptw/css/font-awesome.min.css?m=1627911632
Disallow: /themes/gptw/css/form.css?m=1557151890
Disallow: /themes/gptw/css/layout.css?m=1639578621
Disallow: /themes/gptw/css/owl.carousel.min.css?m=1608555807
Disallow: /themes/gptw/css/responsive.css?m=1633689246
Disallow: /themes/gptw/css/simpleResp.css?m=1608555807
Disallow: /themes/gptw/css/typography.css?m=1612436502
Disallow: /themes/gptw/css/workplace.css?m=1642515788
Disallow: /themes/gptw/images/icon_download.png
Disallow: /themes/gptw/images/icon-mail.png
Disallow: /themes/gptw/images/location-icon2.png
Disallow: /themes/gptw/images/search_for_company.png
Disallow: /themes/gptw/images/social/email.png
Disallow: /themes/gptw/images/social/gray_email.png
Disallow: /themes/gptw/images/social/gray_socialfacebook.png
Disallow: /themes/gptw/images/social/gray_socialinstagram.png
Disallow: /themes/gptw/images/social/gray_sociallinkedin.png
Disallow: /themes/gptw/images/social/gray_socialtwitter.png
Disallow: /themes/gptw/images/social/gray_socialxing.png
Disallow: /themes/gptw/images/social/gray_socialyoutube.png
Disallow: /themes/gptw/images/social/socialfacebook.png
Disallow: /themes/gptw/images/social/socialinstagram.png
Disallow: /themes/gptw/images/social/sociallinkedin.png
Disallow: /themes/gptw/images/social/socialtwitter.png
Disallow: /themes/gptw/images/social/socialxing.png
Disallow: /themes/gptw/images/social/socialyoutube.png
Disallow: /themes/gptw/images/sociallinkedinteam.png
Disallow: /themes/gptw/javascript/animate-css/animate.min.css
Disallow: /themes/gptw/javascript/bootstrap-select.min.js?m=1627911636
Disallow: /themes/gptw/javascript/bootstrap337/bootstrap.min.js
Disallow: /themes/gptw/javascript/bxslider/jquery.bxslider.css
Disallow: /themes/gptw/javascript/bxslider/jquery.bxslider.min.js
Disallow: /themes/gptw/javascript/jquery-ui/1.12.1/jquery-ui.min.css
Disallow: /themes/gptw/javascript/jquery-ui/1.12.1/jquery-ui.min.js
Disallow: /themes/gptw/javascript/jscroll/jquery.jscroll.js
Disallow: /themes/gptw/javascript/main.js
Disallow: /themes/gptw/javascript/matchHeight/jquery.matchHeight.js
Disallow: /themes/gptw/javascript/owl/owl.carousel.min.js?m=1608555812
Disallow: /themes/gptw/javascript/readmore/readmore.min.js
Disallow: /themes/gptw/javascript/TeaserAspectRatio.js?m=1593766406
Disallow: /themes/gptw/javascript/wow/wow.min.js