User-agent: *
Disallow: /hubfs/
Disallow: *.pdf
Disallow: /hubfs/terms-and-conditions/General-Terms-and-Conditions-v1.pdf
Disallow: /hubfs/terms-and-conditions/Affiliate-Marketing-Program-Terms-v1.pdf
Disallow: /hubfs/terms-and-conditions/Display-Data-Matching-Service-Terms-v1.pdf
Disallow: /hubfs/terms-and-conditions/Search-Program-Terms-v1.pdf
Disallow: /hubfs/terms-and-conditions/Display-Channel-Partner-Terms-and-Conditions-v1.pdf
Disallow: /hubfs/terms-and-conditions/General-Terms-and-Conditions-for-Agencies-v1.pdf
Disallow: /hubfs/terms-and-conditions/Influencer-Marketing-Program-Terms-v1.pdf
Disallow: /hubfs/terms-and-conditions/General-Data-Protection-Regulation-Addendum-v1.pdf 
Disallow: /hubfs/General-Terms-and-Conditions-v1.1:2019.pdf
Disallow: /hubfs/General-Terms-and-Conditions-for-Agencies-v1.1:2019.pdf
Disallow: /hubfs/terms-and-conditions/Data-Partner-Agreement-Terms-v1-2019.pdf
Disallow: /hubfs/terms-and-conditions/Accelerate-Marketing-Program-Terms-v1-2019.pdf
Disallow: /hubfs/Accelerate-Marketing-Program-Terms-v1-1-FEB2020.pdf
Disallow: /hubfs/Data-Partner-Agreement-Terms-v1-1-FEB2020.pdf
Disallow: /hubfs/Influencer-Marketing-Program-Terms-v1-1-FEB2020.pdf
Disallow: /hubfs/Display-Channel-Partner-Agreement-v1-1-FEB2020.pdf
Disallow: /hubfs/Search-Program-Terms-v1-1-FEB2020.pdf
Disallow: /hubfs/Display-Data-Matching-Online-Terms-v1-1-FEB2020.pdf
Disallow: /hubfs/Affiliate-Marketing-Program-Terms-v1-1-FEB2020.pdf
Disallow: /hubfs/General-Data-Protection-Regulation-Addendum-v1-1-FEB2020.pdf
Disallow: /hubfs/General-Data-Protection-Regulation-Addendum-v1-1-FEB2020.pdf
Disallow: /hubfs/General-Terms-and-Conditions-for-Agencies-v1-2-FEB2020.pdf
Disallow: /_hcms/preview/
Disallow: /hs/manage-preferences/
Disallow: /hs/preferences-center/
