User-agent: *
Allow: /
Disallow: /user/login
Disallow: /user/logout
Disallow: /layout/set/print
Disallow: /layout/set/popup
Disallow: /Media
Disallow: /Contenus-Additionnels
Disallow: /Enquetes
Disallow: /Liens-teleservices
Disallow: /content/search
Disallow: /content/advancedsearch
Disallow: /En-cours-d-activite/Obligations-legales-et-comptables/Mesures-de-gel-de-fonds/Procedure-de-gel-des-fonds-et-des-ressources-economiques
Disallow: /En-cours-d-activite/Obligations-legales-et-comptables/Mesures-de-gel-de-fonds/Decisions-ministerielles
Disallow: /En-cours-d-activite/Obligations-legales-et-comptables/Mesures-de-gel-de-fonds/Procedures-de-deblocage-ou-d-utilisation-des-fonds-et-des-ressources-economiques-geles
Disallow: /En-cours-d-activite/Obligations-legales-et-comptables/Mesures-de-gel-de-fonds/Recours-a-l-encontre-d-une-mesure-de-gel-des-fonds-et-des-ressources-economiques
Crawl-delay: 10