User-agent: *
Allow: /
Disallow: *?id=search

Sitemap: https://help.ovhcloud.com/sitemap-asia.xml
Sitemap: https://help.ovhcloud.com/sitemap-de.xml
Sitemap: https://help.ovhcloud.com/sitemap-en-au.xml
Sitemap: https://help.ovhcloud.com/sitemap-en-ca.xml
Sitemap: https://help.ovhcloud.com/sitemap-en-gb.xml
Sitemap: https://help.ovhcloud.com/sitemap-en-ie.xml
Sitemap: https://help.ovhcloud.com/sitemap-en-sg.xml
Sitemap: https://help.ovhcloud.com/sitemap-en.xml
Sitemap: https://help.ovhcloud.com/sitemap-es-es.xml
Sitemap: https://help.ovhcloud.com/sitemap-es.xml
Sitemap: https://help.ovhcloud.com/sitemap-fr-ca.xml
Sitemap: https://help.ovhcloud.com/sitemap-fr-ma.xml
Sitemap: https://help.ovhcloud.com/sitemap-fr.xml
Sitemap: https://help.ovhcloud.com/sitemap-fr-sn.xml
Sitemap: https://help.ovhcloud.com/sitemap-fr-tn.xml
Sitemap: https://help.ovhcloud.com/sitemap-it.xml
Sitemap: https://help.ovhcloud.com/sitemap-pl.xml
Sitemap: https://help.ovhcloud.com/sitemap-pt.xml
Sitemap: https://help.ovhcloud.com/sitemap-en-in.xml