User-agent: *
Disallow: /revolutionising-additive-manufacturing-webinar
Disallow: /revolutionising-additive-manufacturing-webinar-thank-you
Disallow: /en/internal-referral
Disallow: /subscription-preferences
Disallow: /en/product-release-webinar-fabulous-freya
Disallow: /en/product-release-webinar-fabulous-freya-thank-you
Disallow: /agile-hardwar-development-webinar
Disallow: /agile-hardwar-development-webinar-thank-you
Disallow: /robust-topology-optimisation-for-sustainability-at-scale-in-automotive-webinar
Disallow: /robust-topology-optimisation-for-sustainability-at-scale-in-automotive-webinar-thank-you
Disallow: /efficient-topology-reconstruction-for-cad
Disallow: /efficient-topology-reconstruction-for-cad-thank-you
Disallow: /product-release-webinar-synera-23.05-geeky-gaia
Disallow: /product-release-webinar-synera-23.05-geeky-gaia-thank-you
Disallow: /on-demand-synera-23.05-geeky-gaia-webinar
Disallow: /revolutionising-automotive-design-webinar
Disallow: /revolutionising-automotive-design-webinar-thank-you
Disallow: /streamlining-battery-pack-design-webinar
Disallow: /streamlining-battery-pack-design-webinar-thank-you
Disallow: /en/thank-you-for-your-subscription
Disallow: /synera-23.08-heroic-horus-webinar
Disallow: /synera-23.08-heroic-horus-webinar-thank-you
Disallow: /cost-engineering-webinar
Disallow: /cost-engineering-webinar-thank-you
Disallow: /champion-symposium
Disallow: /en/contact-event

Disallow: /_hcms/preview/
Disallow: /hs/manage-preferences/
Disallow: /hs/preferences-center/
