User-agent: *
Disallow: /playerivoox_e
Disallow: /playeriVoox_e
Disallow: /player_e
Disallow: /player_n
Disallow: /player_ri
Disallow: /playerChannel_b
Disallow: /playerList_b
Disallow: /radio_er
Disallow: /editar_nk
Disallow: /editar_nb
Disallow: /escuchas_ml
Disallow: /followers_vl
Disallow: /lista-programas_ng
Disallow: /*_am_
Disallow: /*_md_
Disallow: /*_mn_
Disallow: /*_mm_
Disallow: /*_rk_
Disallow: /*_rq_
Disallow: /*_ru_
Disallow: /*_th_
Disallow: /*_v1_
Disallow: /*_wc_
Disallow: /*_5b_
Disallow: /*_a8_listener_
Disallow: /*ajx-
Disallow: /*_in.html
Disallow: /blog/cgi-bin/
Disallow: /blog/wp-admin/
Disallow: /blog/*/?*
Disallow: /blog/index.php
Disallow: /blog/xmlrpc.php
Disallow: /*_f9*.html

User-agent: ClaudeBot
Disallow: /

User-agent: anthropic-ai
Disallow: /

User-agent: Claude-Web
Disallow: /