User-agent: *
Disallow: */phenomtrack.min.js
Disallow: */socialAut
Disallow: */iauth  
Disallow: */chatbot
Disallow: */jobcart
Disallow: */apply
Disallow: */applythankyou
Disallow: */px-widgets
Disallow: */lifeatphenom
Disallow: */workingatphenom
Disallow: */chatbot
Disallow: */pxhomelead
Disallow: */pxhomeapplicant
Disallow: */pxhomequalifiedlead
Disallow: */pxhomevisitor
Disallow: */pxhomestranger


Sitemap: https://jobs.hilton.com/apac/ar/sitemap_index.xml
Sitemap: https://jobs.hilton.com/apac/en/sitemap_index.xml
Sitemap: https://jobs.hilton.com/apac/tr/sitemap_index.xml
Sitemap: https://jobs.hilton.com/latam/ru/sitemap_index.xml
Sitemap: https://jobs.hilton.com/latam/ptbr/sitemap_index.xml
Sitemap: https://jobs.hilton.com/emea/fr/sitemap_index.xml
Sitemap: https://jobs.hilton.com/emea/ru/sitemap_index.xml
Sitemap: https://jobs.hilton.com/us/es/sitemap_index.xml
Sitemap: https://jobs.hilton.com/apac/zh/sitemap_index.xml
Sitemap: https://jobs.hilton.com/apac/ru/sitemap_index.xml
Sitemap: https://jobs.hilton.com/us/it/sitemap_index.xml
Sitemap: https://jobs.hilton.com/latam/it/sitemap_index.xml
Sitemap: https://jobs.hilton.com/latam/fr/sitemap_index.xml
Sitemap: https://jobs.hilton.com/latam/tr/sitemap_index.xml
Sitemap: https://jobs.hilton.com/emea/tr/sitemap_index.xml
Sitemap: https://jobs.hilton.com/emea/pt/sitemap_index.xml
Sitemap: https://jobs.hilton.com/latam/de/sitemap_index.xml
Sitemap: https://jobs.hilton.com/emea/es/sitemap_index.xml
Sitemap: https://jobs.hilton.com/us/pt/sitemap_index.xml
Sitemap: https://jobs.hilton.com/latam/zh/sitemap_index.xml
Sitemap: https://jobs.hilton.com/apac/it/sitemap_index.xml
Sitemap: https://jobs.hilton.com/latam/ar/sitemap_index.xml
Sitemap: https://jobs.hilton.com/us/ar/sitemap_index.xml
Sitemap: https://jobs.hilton.com/apac/ptbr/sitemap_index.xml
Sitemap: https://jobs.hilton.com/emea/de/sitemap_index.xml
Sitemap: https://jobs.hilton.com/us/fr/sitemap_index.xml
Sitemap: https://jobs.hilton.com/emea/it/sitemap_index.xml
Sitemap: https://jobs.hilton.com/us/ru/sitemap_index.xml
Sitemap: https://jobs.hilton.com/us/zh/sitemap_index.xml
Sitemap: https://jobs.hilton.com/us/tr/sitemap_index.xml
Sitemap: https://jobs.hilton.com/apac/pt/sitemap_index.xml
Sitemap: https://jobs.hilton.com/us/de/sitemap_index.xml
Sitemap: https://jobs.hilton.com/apac/de/sitemap_index.xml
Sitemap: https://jobs.hilton.com/apac/es/sitemap_index.xml
Sitemap: https://jobs.hilton.com/us/ptbr/sitemap_index.xml
Sitemap: https://jobs.hilton.com/emea/ptbr/sitemap_index.xml
Sitemap: https://jobs.hilton.com/us/en/sitemap_index.xml
Sitemap: https://jobs.hilton.com/latam/es/sitemap_index.xml
Sitemap: https://jobs.hilton.com/latam/pt/sitemap_index.xml
Sitemap: https://jobs.hilton.com/apac/ja/sitemap_index.xml
Sitemap: https://jobs.hilton.com/emea/ar/sitemap_index.xml
Sitemap: https://jobs.hilton.com/apac/fr/sitemap_index.xml
Sitemap: https://jobs.hilton.com/latam/en/sitemap_index.xml
Sitemap: https://jobs.hilton.com/emea/zh/sitemap_index.xml
Sitemap: https://jobs.hilton.com/emea/en/sitemap_index.xml