User-agent: *
Disallow: /core/
Disallow: /profiles/
Disallow: /README.txt
Disallow: /web.config
Disallow: /admin/
Disallow: /comment/reply/
Disallow: /filter/tips
Disallow: /node/add/
Disallow: /search/
Disallow: /user/register/
Disallow: /user/password/
Disallow: /user/login/
Disallow: /user/logout/
Disallow: /index.php/admin/
Disallow: /index.php/comment/reply/
Disallow: /index.php/filter/tips
Disallow: /index.php/node/add/
Disallow: /index.php/search/
Disallow: /index.php/user/password/
Disallow: /index.php/user/register/
Disallow: /index.php/user/login/
Disallow: /index.php/user/logout/
Disallow: /fr/
Disallow: /fr-ca/
Disallow: /fr-ma/
Disallow: /fr-tn/
Disallow: /fr-sn/
Disallow: /en-gb/
Disallow: /en-ca/
Disallow: /en-ie/
Disallow: /en-sg/
Disallow: /asia/
Disallow: /en-au/
Disallow: /es/
Disallow: /es-es/
Disallow: /it/
Disallow: /de/
Disallow: /pl/
Disallow: /pt/
Disallow: /nl/
User-agent: GPTBot
Disallow: /
User-agent: ChatGPT-User
Disallow: /
User-agent: CCBot
Disallow: /
User-agent: anthropic-ai
Disallow: /
User-agent: TextBulkerBot
Disallow: /

Sitemap: https://labs.ovhcloud.com/asia/labs.ovhcloud.com_en-142_sitemap.xml
Sitemap: https://labs.ovhcloud.com/de/labs.ovhcloud.com_de_sitemap.xml
Sitemap: https://labs.ovhcloud.com/en-au/labs.ovhcloud.com_en-au_sitemap.xml
Sitemap: https://labs.ovhcloud.com/en-ca/labs.ovhcloud.com_en-ca_sitemap.xml
Sitemap: https://labs.ovhcloud.com/en-gb/labs.ovhcloud.com_en-gb_sitemap.xml
Sitemap: https://labs.ovhcloud.com/en-ie/labs.ovhcloud.com_en-ie_sitemap.xml
Sitemap: https://labs.ovhcloud.com/en-sg/labs.ovhcloud.com_en-sg_sitemap.xml
Sitemap: https://labs.ovhcloud.com/en/labs.ovhcloud.com_en_sitemap.xml
Sitemap: https://labs.ovhcloud.com/es-es/labs.ovhcloud.com_es_sitemap.xml
Sitemap: https://labs.ovhcloud.com/es/labs.ovhcloud.com_es-419_sitemap.xml
Sitemap: https://labs.ovhcloud.com/fr-ca/labs.ovhcloud.com_fr-ca_sitemap.xml
Sitemap: https://labs.ovhcloud.com/fr-ma/labs.ovhcloud.com_fr-ma_sitemap.xml
Sitemap: https://labs.ovhcloud.com/fr-sn/labs.ovhcloud.com_fr-sn_sitemap.xml
Sitemap: https://labs.ovhcloud.com/fr-tn/labs.ovhcloud.com_fr-tn_sitemap.xml
Sitemap: https://labs.ovhcloud.com/fr/labs.ovhcloud.com_fr_sitemap.xml
Sitemap: https://labs.ovhcloud.com/it/labs.ovhcloud.com_it_sitemap.xml
Sitemap: https://labs.ovhcloud.com/nl/labs.ovhcloud.com_nl_sitemap.xml
Sitemap: https://labs.ovhcloud.com/pl/labs.ovhcloud.com_pl_sitemap.xml
Sitemap: https://labs.ovhcloud.com/pt/labs.ovhcloud.com_pt-pt_sitemap.xml