User-agent: *
Disallow: /th/service/line-family-club-poc
Disallow: /*.preview$
Disallow: /th-en/business-case-study/eventstickers
Disallow: /th/service/line-ads/discount-coupon-for-new-2023?utm_source=line&utm_medium=lineforbusiness&utm_campaign=banner
Disallow: /th/service/line-ads/discount-coupon-for-new-2023?utm_source=FB&utm_medium=CPC&utm_campaign=LAP_selfserve&utm_content=adcoupon-jan
Disallow: /th/service/line-ads/discount-coupon-for-new-2023??utm_source=internal&utm_medium=oa&utm_campaign=LAP_selfserve&utm_content=adcoupon-mar
Disallow: /th/service/line-account-connect/customer-connect/1000
Disallow: /th/service/line-ads/discount-coupon-for-new-2023?utm_source=LINE for Business&utm_campaign=First Banner
Disallow: /th/service/line-ads/discount-coupon-for-new-2023?utm_source=line&utm_medium=websitebanner&utm_campaign=discountnew
Disallow: /th/line-oa-store/apps/zwiz-ai
Disallow: /th/tutorials/line-oa/line-oa/ai-response
Disallow: /th-en/line-oa-store/apps/botnoi-sme-platform
Disallow: /th/monthlyplancampaign-mar2023?utm_source=KOL&utm_medium=sentangsedtee
Disallow: /th-en/tutorials/line-ads/1000
Disallow: /th/tutorials/line-oa/line-oa/timeline
Disallow: /th/oa-call/1000
Disallow: /th/case-study/success-Esso/1000
Disallow: /th/news/20220204_6/1000
Disallow: /th/service/profile/1000
Disallow: /th-en/case-study/success-starbucks/1000
Disallow: /th/helpcenter/line-oa/manual/premiumid/1000
Disallow: /th/helpcenter/businessmanager/1000
Disallow: /th/tutorials/line-oa/1000
Disallow: /th/line-oa-store/apps/botnoi-sme-platform/1000
Disallow: /th/business-case-study/MyCustomer-1st-party-data/1000
Disallow: /th/service/sponsored-stickers/1000
Disallow: /th-en/service/linepoints/1000
Disallow: /th-en/line-oa-store/1000
Disallow: /th-en/service/businessmanager/1000
Disallow: /th/news/20220525_1/1000
Disallow: /th/tutorials/line-oa/line-oa/richmessage/1000
Disallow: /th-en/line-certified-coach//1000
Disallow: /th/business-case-study/LINE-OA-Performance-Insight/1000
Disallow: /th-en/service/line-ads/1000
Disallow: /th/business-case-study/chat-commerce/1000
Disallow: /th-en/helpcenter/line-oa/1000
Disallow: /th/partner//1000
Disallow: /th/voombizcontest/1000
Disallow: /th-en/business-case-study/bestlineoafeatures/1000
Disallow: /th/news/20201109_1/1000
Disallow: /th-en/service/line-tv
Disallow: /th/service/line-official-
Disallow: /th-en/case-study/success-case-revealed
Disallow: /th/service/Linepoints
Disallow: /th/service/line-a
Disallow: /th-en/case-study/itdix-fingadget
Disallow: /th-en/line-oa-store/apps/arcm-chatbot
Disallow: /th/line-oa-store/apps/arcm-chatbot
Disallow: /th-en/service/line-account-connect/
Disallow: /th/line-oa-store/apps/salesbear
Disallow: /th/contact-partner-offer/
Disallow: /th/how-to-use-com
Disallow: /th/line-oa-store/apps/ex10-crm
Disallow: /th-en/service/mycustomer
Disallow: /th/service/line-oa-
Disallow: /th/service/line-idol
Disallow: /th-en/line-oa-store/apps/yellowreward
Disallow: /th-en/line-oa-store/apps/salesbear
Disallow: /th/service/line-ads-
Disallow: /th/service/line-oa-features2
Disallow: /th-en/line-oa-store/how-to-use
Disallow: /th-en/service/line-oa-
Disallow: /th/line-oa-store/apps/yellowreward
Disallow: /th/line-oa-store/apps/zwiz-ai-enterprise
Disallow: /th/line-oa-store/apps/botnoi-sme-platform
Disallow: /th/thai-addresses/
Disallow: /th/how-to-use-com.inews.android
Disallow: /th/game/business/com
Disallow: /th-en/line-oa-store/apps/ex10-crm
Disallow: /th/case-study/korat-waterland
Disallow: /th-en/case-study/success-chaba-nail
Disallow: /th/line-official-account/com.0
Disallow: /th/line-oa-store/terms-of-service
Disallow: /th-en/lineadsplatform
Disallow: /th/lineadsplatform
Disallow: /th/line-oa-store/how-to-use
Disallow: /th/case-study/maguro-sushi
Disallow: /th/line-oa-store/apps/devio-connext
Disallow: /th/common-page/431aa610-55a4-426d-847c-a99184fa7124
Disallow: /api/forms/oa-store-contact
Disallow: /th/service/line-ads/discount-coupon-2022
Disallow: /th/service/lineoafeatures
Disallow: /th/partner/line-ads-platform
Disallow: /th/service/line-account-connect/gain-friends-ads
Disallow: /th-en/line-oa-store/apps/devio-connext
Disallow: /th/01HSDE5NPRB6RC947DBMRYGGZG