<!doctype html>
<html>
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1"/>
    <title>LMS</title>

    <link rel="icon" type="image/svg" href="/16_16.svg" sizes="16x16">
    <link rel="icon" type="image/svg" href="/32_32.svg" sizes="32x32">
    <link rel="icon" type="image/svg" href="/48_48.svg" sizes="48x48">
    <link rel="icon" type="image/svg" href="/64_64.svg" sizes="64x64">
    <link rel="icon" type="image/svg" href="/128_128.svg" sizes="128x128">
    <link rel="icon" type="image/svg" href="/144_144.svg" sizes="144x144">
    <link rel="icon" type="image/svg" href="/150_150.svg" sizes="150x150">
    <link rel="icon" type="image/svg" href="/180_180.svg" sizes="180x180">
    <link rel="icon" type="image/svg" href="/192_192.svg" sizes="192x192">
    <link rel="icon" type="image/svg" href="/512_512.svg" sizes="512x512">
    <link rel="icon" type="image/png" href="/favicon.png" sizes="512x512">
    <link rel="icon" type="image/png" href="/favicon_128.png" sizes="128x128">

    <script type="module" crossorigin src="/assets/index-B9I9QqYw.js"></script>
    <link rel="stylesheet" crossorigin href="/assets/index-DRwFlDHs.css">
  </head>
  <body style="margin: 0">
    <div id="app"></div>
    <div class="popup-portal"></div>
  </body>
</html>
