User-agent: *
Disallow: /entry/
Disallow: /messages/
Disallow: /profile/comments/
Disallow: /profile/discussions/
Disallow: /search/
Disallow: /sso/
Disallow: /sso
Disallow: /home/leaving/
Disallow: /home/leaving
Disallow: /profile/
Disallow: /profile
