User-agent: GPTBot
Disallow: /
User-Agent: *
Disallow: /manage-profiles
Disallow: /settings/
Disallow: /migration
Disallow: /video-data-sharing
Disallow: /logout
Disallow: /connect
Disallow: /create-account/connect
Disallow: /oauth
Disallow: /reset-password
Disallow: /vudu
Disallow: /provider/connect/vudu
Disallow: /cookie
Disallow: /person*
Disallow: /shared-list/*
Sitemap: https://moviesanywhere.com/sitemap.xml
