User-agent: *
Disallow: /api/
Disallow: /sprk/
Disallow: /account/
Disallow: /download-ebook
Disallow: /end-to-end-sale-assistance
Disallow: /end-to-end-tenant-search-assistance
Disallow: /guaranteed-rent-out
Disallow: /guaranteed-sale
Disallow: /home-interiors-terms-and-conditions
Disallow: /housing-packers-and-movers-terms-and-conditions
Disallow: /housing-rental-furniture-terms-and-conditions
Disallow: /jackpot-multi2
Disallow: /jackpot-multi3
Disallow: /jackpot-pool
Disallow: /jackpot-result
Disallow: /jackpot-result2
Disallow: /jackpot-result3
Disallow: /jackpotwinmulti
Disallow: /ld-big-win-1
Disallow: /ldbigwinner2
Disallow: /legal-services-terms-and-conditions
Disallow: /listing-form-v2
Disallow: /moneyback-opt-out-success
Disallow: /owner-discount
Disallow: /owner-feedback
Disallow: /ownerfeedback
Disallow: /personal-loan
Disallow: /post-owner-listing-e2e-assistance
Disallow: /post-owner-listing-guaranteed-rentout
Disallow: /post-owner-listing-pay-zero-brokerage
Disallow: /post-owner-listing-rent-out-best-price
Disallow: /post-seller-listing-e2e-assistance-sale
Disallow: /post-seller-listing-guaranteed-sale
Disallow: /post-seller-listing-sell-fast-best-price
Disallow: /property-valuation-sell-at-right-price
Disallow: /property-valuation-sell-at-right-price-form
Disallow: /proptiger/referral
Disallow: /rent-out-property-fast-at-best-price
Disallow: /repost-successful
Disallow: /repost-unsubscribe
Disallow: /resultpgv2
Disallow: /rm-assist-tenant-verfication-discount20
Disallow: /sell-fast-and-at-best-price
Disallow: /solar-rooftop-terms-and-conditions
Disallow: /tenant-verification-nid
Disallow: /terms-and-conditions-housing-bonito-designs
Disallow: /terms-and-conditions-housing-home-lane
Disallow: /terms-and-conditions-housing-livspace
Disallow: /test
Disallow: /thank-you
Disallow: /zero-brokerage-tenant-search
Sitemap: https://new.housing.com/sitemap.xml
