User-agent: *
Disallow: /
Disallow: /search?
Disallow: /search/?
Disallow: /__i/
Allow: /$
Allow: /?
Allow: /nwshp$
Allow: /news$
Allow: /news/$
Allow: /news/?gl=
Allow: /news/?hl=
Allow: /news/?ned=
Allow: /about$
Allow: /about?
Allow: /about/
Allow: /topics/
Allow: /publications/
Allow: /stories/
Allow: /swg/
Allow: /covid19/

User-agent: Googlebot
Disallow: /topics/
Disallow: /publications/
Disallow: /stories/
Disallow: /articles/
Disallow: /rss/
Disallow: /atom/
