User-agent: *
Crawl-delay: 5
Disallow: .atom$

Sitemap: https://newsroom.feverup.com/es-AR/sitemap.xml
Sitemap: https://newsroom.feverup.com/en-AU/sitemap.xml
Sitemap: https://newsroom.feverup.com/en-BE/sitemap.xml
Sitemap: https://newsroom.feverup.com/pt-BR/sitemap.xml
Sitemap: https://newsroom.feverup.com/en-CA/sitemap.xml
Sitemap: https://newsroom.feverup.com/es-CL/sitemap.xml
Sitemap: https://newsroom.feverup.com/en-DK/sitemap.xml
Sitemap: https://newsroom.feverup.com/de-DE/sitemap.xml
Sitemap: https://newsroom.feverup.com/es-ES/sitemap.xml
Sitemap: https://newsroom.feverup.com/fr-FR/sitemap.xml
Sitemap: https://newsroom.feverup.com/en-IE/sitemap.xml
Sitemap: https://newsroom.feverup.com/it-IT/sitemap.xml
Sitemap: https://newsroom.feverup.com/es-MX/sitemap.xml
Sitemap: https://newsroom.feverup.com/nl-NL/sitemap.xml
Sitemap: https://newsroom.feverup.com/en-NZ/sitemap.xml
Sitemap: https://newsroom.feverup.com/pt-PT/sitemap.xml
Sitemap: https://newsroom.feverup.com/en-CH/sitemap.xml
Sitemap: https://newsroom.feverup.com/en-SG/sitemap.xml
Sitemap: https://newsroom.feverup.com/en-SE/sitemap.xml
Sitemap: https://newsroom.feverup.com/en-GB/sitemap.xml
Sitemap: https://newsroom.feverup.com/en-US/sitemap.xml
Sitemap: https://newsroom.feverup.com/de-AT-AT/sitemap.xml
Sitemap: https://newsroom.feverup.com/en-AE/sitemap.xml
Sitemap: https://newsroom.feverup.com/en-IN/sitemap.xml
Sitemap: https://newsroom.feverup.com/ja-JP/sitemap.xml
Sitemap: https://newsroom.feverup.com/ko-KR/sitemap.xml