User-Agent: *
Disallow: /*/reservation/
Disallow: /*/profil/
Disallow: /*/cancellation/
Disallow: /*/fh/
Disallow: /*.pdf
Disallow: /*.mini
Disallow: /security-certificate/
Disallow: /ssr*
Disallow: /identification/
Disallow: /express/
Disallow: /ficheHotel/
Disallow: /*.do
Disallow: /*.action
Disallow: /*/mini.shtml
Disallow: /newsletter/
Disallow: /geo/
