User-agent: *
Disallow: /wp-admin/
Disallow: /wp-content/plugins/
Disallow: /wp-includes
Disallow: /wp-includes/
Disallow: /wp-login.php
Disallow: /master-content-repo/
Disallow: *?s=
Disallow: *?archive-year=
Disallow: *?tax=
Disallow: */gating-form/
Disallow: */gated-downloads/
Disallow: */jobs/careers-apply/
Disallow: *?*topic
Disallow: *?*country
Disallow: *?*language
Disallow: *?*orderby
Disallow: *?*category
Disallow: *?*status
User-agent: Yandex
Disallow: /wp-admin/
Disallow: /wp-content/plugins/
Disallow: /wp-includes
Disallow: /wp-includes/
Disallow: /wp-login.php
Disallow: /master-content-repo/
Disallow: */gating-form/
Disallow: */gated-downloads/
Disallow: */jobs/careers-apply/
Disallow: *?topic&location
Disallow: */wp-json/
Disallow: */feed/
Clean-param: utm_campaign&utm_medium&utm_source&utm_term&openstat&gclid&status&category&orderby&language&country&topic&s&tax&archive-year&location&crs-title&isnews&id&enquiry-type
Sitemap: https://nttdata-solutions.com/uk/sitemap_index.xml
Sitemap: https://nttdata-solutions.com/de/sitemap_index.xml
Sitemap: https://nttdata-solutions.com/us/sitemap_index.xml
Sitemap: https://nttdata-solutions.com/no/sitemap_index.xml
Sitemap: https://nttdata-solutions.com/se/sitemap_index.xml
Sitemap: https://nttdata-solutions.com/dk/sitemap_index.xml
Sitemap: https://nttdata-solutions.com/tr/sitemap_index.xml
Sitemap: https://nttdata-solutions.com/pl/sitemap_index.xml
Sitemap: https://nttdata-solutions.com/es/sitemap_index.xml
Sitemap: https://nttdata-solutions.com/fr/sitemap_index.xml
Sitemap: https://nttdata-solutions.com/hu/sitemap_index.xml
Sitemap: https://nttdata-solutions.com/sk/sitemap_index.xml
Sitemap: https://nttdata-solutions.com/cz/sitemap_index.xml
Sitemap: https://nttdata-solutions.com/bnl/sitemap_index.xml
Sitemap: https://nttdata-solutions.com/my/sitemap_index.xml
Sitemap: https://nttdata-solutions.com/ch/sitemap_index.xml
Sitemap: https://nttdata-solutions.com/in-en/sitemap_index.xml
Sitemap: https://nttdata-solutions.com/qa-en/sitemap_index.xml
Sitemap: https://nttdata-solutions.com/ae-en/sitemap_index.xml
Sitemap: https://nttdata-solutions.com/fi/sitemap_index.xml
Sitemap: https://nttdata-solutions.com/br-en/sitemap_index.xml
Sitemap: https://nttdata-solutions.com/au/sitemap_index.xml
Sitemap: https://nttdata-solutions.com/sg-en/sitemap_index.xml
Sitemap: https://nttdata-solutions.com/id-en/sitemap_index.xml
Sitemap: https://nttdata-solutions.com/br/sitemap_index.xml
Sitemap: https://nttdata-solutions.com/th/sitemap_index.xml
Sitemap: https://nttdata-solutions.com/bg-en/sitemap_index.xml
