User-agent: GPTBot
Disallow: /
User-agent: ChatGPT-User
Disallow: /
User-agent: CCBot
Disallow: /
User-agent: anthropic-ai
Disallow: /
User-agent: TextBulkerBot
Disallow: /

Sitemap: https://opentrustedcloud.ovhcloud.com/asia/opentrustedcloud.ovhcloud.com_en-142_sitemap.xml
Sitemap: https://opentrustedcloud.ovhcloud.com/de/opentrustedcloud.ovhcloud.com_de_sitemap.xml
Sitemap: https://opentrustedcloud.ovhcloud.com/en-au/opentrustedcloud.ovhcloud.com_en-au_sitemap.xml
Sitemap: https://opentrustedcloud.ovhcloud.com/en-ca/opentrustedcloud.ovhcloud.com_en-ca_sitemap.xml
Sitemap: https://opentrustedcloud.ovhcloud.com/en-gb/opentrustedcloud.ovhcloud.com_en-gb_sitemap.xml
Sitemap: https://opentrustedcloud.ovhcloud.com/en-ie/opentrustedcloud.ovhcloud.com_en-ie_sitemap.xml
Sitemap: https://opentrustedcloud.ovhcloud.com/en-in/opentrustedcloud.ovhcloud.com_en-in_sitemap.xml
Sitemap: https://opentrustedcloud.ovhcloud.com/en-sg/opentrustedcloud.ovhcloud.com_en-sg_sitemap.xml
Sitemap: https://opentrustedcloud.ovhcloud.com/en/opentrustedcloud.ovhcloud.com_en_sitemap.xml
Sitemap: https://opentrustedcloud.ovhcloud.com/es-es/opentrustedcloud.ovhcloud.com_es_sitemap.xml
Sitemap: https://opentrustedcloud.ovhcloud.com/es/opentrustedcloud.ovhcloud.com_es-419_sitemap.xml
Sitemap: https://opentrustedcloud.ovhcloud.com/fr-ca/opentrustedcloud.ovhcloud.com_fr-ca_sitemap.xml
Sitemap: https://opentrustedcloud.ovhcloud.com/fr-ma/opentrustedcloud.ovhcloud.com_fr-ma_sitemap.xml
Sitemap: https://opentrustedcloud.ovhcloud.com/fr-sn/opentrustedcloud.ovhcloud.com_fr-sn_sitemap.xml
Sitemap: https://opentrustedcloud.ovhcloud.com/fr-tn/opentrustedcloud.ovhcloud.com_fr-tn_sitemap.xml
Sitemap: https://opentrustedcloud.ovhcloud.com/fr/opentrustedcloud.ovhcloud.com_fr_sitemap.xml
Sitemap: https://opentrustedcloud.ovhcloud.com/it/opentrustedcloud.ovhcloud.com_it_sitemap.xml
Sitemap: https://opentrustedcloud.ovhcloud.com/nl/opentrustedcloud.ovhcloud.com_nl_sitemap.xml
Sitemap: https://opentrustedcloud.ovhcloud.com/pl/opentrustedcloud.ovhcloud.com_pl_sitemap.xml
Sitemap: https://opentrustedcloud.ovhcloud.com/pt/opentrustedcloud.ovhcloud.com_pt-pt_sitemap.xml