User-Agent: *
Disallow: /*
Allow: /wwopen/appStore
Allow: /wwopen/industryCase
Allow: /wwopen/help
Allow: /wwopen/helpguide
Allow: /wwopen/sass
Allow: /wwopen/custom
Allow: /wwopen/support
Allow: /wwopen/reward
Allow: /wwopen/hardware
Allow: /wwopen/server
Allow: /wwopen/manual
Allow: /wwopen/third/register
Allow: /wwopen/jsapidemo
Allow: /wwopen/jsapisign
Allow: /wwopen/devtool
Allow: /community
Allow: /devtool
Allow: /help
Allow: /api
Allow: /app
Allow: /$