User-agent: *
Crawl-delay: 30
Disallow: /*?*offset=
Disallow: /wp-admin
Disallow: /wp-content/cache
Disallow: /trackback
Disallow: */trackback
Disallow: /*~*
Disallow: /*~
Allow: /wp-admin/admin-ajax.php