User-agent: GPTBot
Disallow: /
User-agent: ChatGPT-User
Disallow: /
User-agent: CCBot
Disallow: /
User-agent: anthropic-ai
Disallow: /
User-agent: TextBulkerBot
Disallow: /

Sitemap: https://partner.ovhcloud.com/asia/partner.ovhcloud.com_en-142_sitemap.xml
Sitemap: https://partner.ovhcloud.com/de/partner.ovhcloud.com_de_sitemap.xml
Sitemap: https://partner.ovhcloud.com/en-au/partner.ovhcloud.com_en-au_sitemap.xml
Sitemap: https://partner.ovhcloud.com/en-ca/partner.ovhcloud.com_en-ca_sitemap.xml
Sitemap: https://partner.ovhcloud.com/en-gb/partner.ovhcloud.com_en-gb_sitemap.xml
Sitemap: https://partner.ovhcloud.com/en-ie/partner.ovhcloud.com_en-ie_sitemap.xml
Sitemap: https://partner.ovhcloud.com/en-in/partner.ovhcloud.com_en-in_sitemap.xml
Sitemap: https://partner.ovhcloud.com/en-sg/partner.ovhcloud.com_en-sg_sitemap.xml
Sitemap: https://partner.ovhcloud.com/en/partner.ovhcloud.com_en_sitemap.xml
Sitemap: https://partner.ovhcloud.com/es-es/partner.ovhcloud.com_es_sitemap.xml
Sitemap: https://partner.ovhcloud.com/es/partner.ovhcloud.com_es-419_sitemap.xml
Sitemap: https://partner.ovhcloud.com/fr-ca/partner.ovhcloud.com_fr-ca_sitemap.xml
Sitemap: https://partner.ovhcloud.com/fr-ma/partner.ovhcloud.com_fr-ma_sitemap.xml
Sitemap: https://partner.ovhcloud.com/fr-sn/partner.ovhcloud.com_fr-sn_sitemap.xml
Sitemap: https://partner.ovhcloud.com/fr-tn/partner.ovhcloud.com_fr-tn_sitemap.xml
Sitemap: https://partner.ovhcloud.com/fr/partner.ovhcloud.com_fr_sitemap.xml
Sitemap: https://partner.ovhcloud.com/it/partner.ovhcloud.com_it_sitemap.xml
Sitemap: https://partner.ovhcloud.com/nl/partner.ovhcloud.com_nl_sitemap.xml
Sitemap: https://partner.ovhcloud.com/pl/partner.ovhcloud.com_pl_sitemap.xml
Sitemap: https://partner.ovhcloud.com/pt/partner.ovhcloud.com_pt-pt_sitemap.xml