User-agent: *
Disallow: /_hcms/iplookup
Disallow: /_hcms/perf
Disallow: *?portalId=
Disallow: *?inpageEditorUI=
Disallow: *?cssPath=
Disallow: *?_health_check_=
Disallow: *?_preview=
Disallow: *?benderPackage=
Disallow: *?preview_key=
Disallow: *?staticVersion=
Disallow: *?cacheBurst=
Disallow: *?tc_deviceCategory=
Disallow: *?isPreview=
Disallow: *?preview_theme=
Disallow: *?cos=
Disallow: /_hcms/preview/
Disallow: /hs/manage-preferences/
Disallow: /hs/preferences-center/
