
<!doctype html>
<html lang="en">
<head>
<link rel="icon" href="/favicon.ico" type="image/x-icon" />
<link href="https://fonts.googleapis.com/css2?family=Poppins:ital,wght@0,100;0,200;0,300;0,400;0,500;0,600;0,700;0,800;1,100;1,200;1,300;1,400;1,500;1,600;1,700;1,800&display=swap" rel="stylesheet">
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous"><script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
<link rel="stylesheet" href="https://www.icims.com/wp-content/themes/icims4/static/css/main.css" type="text/css" /></head>
<body class="error404 logged-in admin-bar no-customize-support icims lang-us"><div class="float-margin" style="height:auto; padding: 25px 8vw; "><img alt="iCIMS logo" src="https://www.icims.com/wp-content/themes/icims4/src/img/icims-logo-r.svg" style="height: 45px"></div><div class="module module-text-image image-transparent spacing-Default bg-custom bg-lt-blue"><div class="container"><div class="row"><div class="background-color-box left bg-custom bg-lt-blue"></div><div class="background-color-box right bg-custom bg-blue"></div><div class="col-md-6 image-box left bg-custom bg-lt-blue"><img src="https://www.icims.com/wp-content/uploads/2020/09/error.png" /><noscript><img src="https://www.icims.com/wp-content/uploads/2020/09/error.png" alt="" /></noscript></div><div class="col-md-6 right bg-custom bg-blue"><p><span style="font-weight: 400;"></span>https://quebec-nttdata.icims.com/<br/>If you believe this is in error, please contact the HR department of the organization you were attempting to apply to.<br/><br/>For other job seeker related questions, please see our <a class="bg-blue" href="https://icims.help/candidate-faq" target="_blank">FAQ here</a>.</span></p></div></div></div></div><div class="module module-full-width-cta spacing-Default bg-custom bg-offwhite "><div class="container"><div class="row"><div class="col-md-12"><h2 class="h1">More about iCIMS</h2><div class="text-cta-box link"><a href="https://care.icims.com/s/" target="" class="text-cta">Visit the Community site</a></div><div class="text-cta-box link"><a href="https://www.icims.com/" target="" class="text-cta">Learn about the Talent Cloud</a></div><span class="sh-link-space"></span><div class="text-cta-box link"><a href="https://www.icims.com/company/corporate-newsroom/news/" target="" class="text-cta">Get the latest news and insights</a></div><span class="sh-link-space"></span><div class="text-cta-box link"><a href="https://careers.icims.com/careers-home/" target="" class="text-cta">View our open jobs</a></div><span class="sh-link-space"></span></div></div></div></div></body></html>
