Sitemap: https://rakuten.wd1.myworkdayjobs.com/RakutenShopStyle/siteMap.xml
Sitemap: https://rakuten.wd1.myworkdayjobs.com/RakutenAsia/siteMap.xml
Sitemap: https://rakuten.wd1.myworkdayjobs.com/Kobo/siteMap.xml
Sitemap: https://rakuten.wd1.myworkdayjobs.com/RakutenGames/siteMap.xml
Sitemap: https://rakuten.wd1.myworkdayjobs.com/RakutenMobile/siteMap.xml
Sitemap: https://rakuten.wd1.myworkdayjobs.com/RakutenPayment/siteMap.xml
Sitemap: https://rakuten.wd1.myworkdayjobs.com/RakutenRewards/siteMap.xml
Sitemap: https://rakuten.wd1.myworkdayjobs.com/RakutenVikiSingapore/siteMap.xml
Sitemap: https://rakuten.wd1.myworkdayjobs.com/RakutenAmericas/siteMap.xml
Sitemap: https://rakuten.wd1.myworkdayjobs.com/RakutenInc/siteMap.xml
Sitemap: https://rakuten.wd1.myworkdayjobs.com/Cartera/siteMap.xml
Sitemap: https://rakuten.wd1.myworkdayjobs.com/RakutenReady/siteMap.xml
Sitemap: https://rakuten.wd1.myworkdayjobs.com/RakutenAdvertising/siteMap.xml
Sitemap: https://rakuten.wd1.myworkdayjobs.com/RakutenTV/siteMap.xml
Sitemap: https://rakuten.wd1.myworkdayjobs.com/RakutenEurope/siteMap.xml
Sitemap: https://rakuten.wd1.myworkdayjobs.com/RakutenSuperLogistics/siteMap.xml
Sitemap: https://rakuten.wd1.myworkdayjobs.com/KonMari/siteMap.xml
Sitemap: https://rakuten.wd1.myworkdayjobs.com/RakutenSymphony/siteMap.xml
Sitemap: https://rakuten.wd1.myworkdayjobs.com/UniversityRecruitment/siteMap.xml
Sitemap: https://rakuten.wd1.myworkdayjobs.com/RakutenSuperLogisticsJA/siteMap.xml
Sitemap: https://rakuten.wd1.myworkdayjobs.com/RakutenInsuranceGroup/siteMap.xml
Sitemap: https://rakuten.wd1.myworkdayjobs.com/RakutenFrance/siteMap.xml
Sitemap: https://rakuten.wd1.myworkdayjobs.com/RakutenEUTD/siteMap.xml
Sitemap: https://rakuten.wd1.myworkdayjobs.com/RakutenDX/siteMap.xml
Sitemap: https://rakuten.wd1.myworkdayjobs.com/Collective_Voice_a_Rakuten_Company/siteMap.xml
Sitemap: https://rakuten.wd1.myworkdayjobs.com/RakutenSymphonyJapan/siteMap.xml
Sitemap: https://rakuten.wd1.myworkdayjobs.com/RakutenTotalSolutions/siteMap.xml

User-agent: *
Allow: /RakutenShopStyle/
Allow: /RakutenAsia/
Allow: /Kobo/
Allow: /RakutenGames/
Allow: /RakutenMobile/
Allow: /RakutenPayment/
Allow: /RakutenRewards/
Allow: /RakutenVikiSingapore/
Allow: /RakutenAmericas/
Allow: /RakutenInc/
Allow: /Cartera/
Allow: /RakutenReady/
Allow: /RakutenAdvertising/
Allow: /RakutenTV/
Allow: /RakutenEurope/
Allow: /RakutenSuperLogistics/
Allow: /KonMari/
Allow: /RakutenSymphony/
Allow: /UniversityRecruitment/
Allow: /RakutenSuperLogisticsJA/
Allow: /RakutenInsuranceGroup/
Allow: /RakutenFrance/
Allow: /RakutenEUTD/
Allow: /RakutenDX/
Allow: /Collective_Voice_a_Rakuten_Company/
Allow: /RakutenSymphonyJapan/
Allow: /RakutenTotalSolutions/
Disallow: /refreshFacet/