User-agent: *
Disallow: /wishlist
Disallow: /Account-StartRegister
Disallow: /Account-Unsubscribe
Disallow: /Account-Profile
Disallow: /cart
Disallow: /Search-Results
Disallow: /*prefv*
Disallow: /*prefn*
Disallow: /shipping
Disallow: /UID-Login
Sitemap: https://www.rewards.sony.com/sitemap_index.xml