User-Agent: *
Disallow: /wp-admin/
Disallow: /archives/
Disallow: /wp-*
Allow: /wp-content/uploads/
Disallow: /comments/feed/
Disallow: /readme.html
Allow: /*.css
Allow: /*.js
Allow: /*.woff
Allow: /*.woff2
Allow: /*.ttf
Allow: /*.png
Allow: /*.jpg
Allow: /*.gif
Allow: /*.svg
Allow: /*.php
Allow: /*.pdf
Sitemap: https://seguraviudas.com/sitemap_index.xml