User-agent: *
Disallow: /wp-admin/
Disallow: /nowawycena
Disallow: */feed*
Allow: /blog/feedback-co-to-jest-i-jak-zbierac-go-od-klientow/
Allow: /wp-admin/admin-ajax.php
Disallow: */lp/
Disallow: *?trk
Disallow: *?tag
Disallow: *?nocache
Disallow: /wp-config.php
Disallow: *?author
Disallow: */addtoany
Disallow: */tag
Disallow: */app/webroot
Disallow: /Opinie
Disallow: */Nagrody
Disallow: *?aam-media
Disallow: /page/3/
Disallow: /lasery
Disallow: /nikon
Disallow: /dewalt
Disallow: /dalmierz
Disallow: /niwelator
Disallow: /poziomic
Disallow: /okulary
Disallow: /wykrywacze
Disallow: /cst-berger
Disallow: /bosch
Disallow: /adaptery
Disallow: /products
Disallow: /statywy
Disallow: /leica
Disallow: /do-wnetrz
Disallow: /na-zewnatrz
Disallow: /blog/2014/
Disallow: /blog/2015/
Disallow: /blog/2016/
Disallow: /blog/2017/
Disallow: /blog/2018/
Disallow: /blog/2019/
Disallow: /blog/2020/
Disallow: /blog/2021/
Disallow: /blog/2022/
Disallow: /blog/2023/
Disallow: ?et
Disallow: *?mode
Disallow: */node_modules/
Disallow: /1*.htm
Disallow: /2*.htm
Disallow: /3*.htm
Disallow: /4*.htm
Disallow: /5*.htm
Disallow: /6*.htm
Disallow: /7*.htm
Disallow: /8*.htm
Disallow: /9*.htm
Disallow: /speaker/
Disallow: */index.php?*.htm
Disallow: /opinie-klientow/
Disallow: /search/
Disallow: *?s=
Disallow: */admin.php$