User-agent: * 
Allow: / 
Allow: /countries 
Allow: /pt-pt 
Allow: /en-pt 
Allow: /de-de 
Allow: /es-es 
Allow: /no-no 
Allow: /hu-hu 
Allow: /en-hu 
Allow: /fr-lu 
Disallow: /*-rms/ 
Disallow: /car/option?* 
Disallow: /car/overview?* 
Disallow: /car/delivery?* 
Disallow: /car/insurance?* 
Disallow: /car/personalinformation?* 
Disallow: /car/order?*