User-Agent: *
Disallow: /get-pdf
Disallow: /get-all-pdf
Disallow: /get-wallet
Disallow: /get-google-wallet
Disallow: /ticket/
Disallow: /transaction/
Disallow: /support/
Disallow: /result/
Sitemap: https://vivenu.com/third/sitemap.xml