User-agent: GPTBot
Disallow: /
User-agent: ChatGPT-User
Disallow: /
User-agent: CCBot
Disallow: /
User-agent: anthropic-ai
Disallow: /
User-agent: TextBulkerBot
Disallow: /

Sitemap: https://startup.ovhcloud.com/asia/startup.ovhcloud.com_en-142_sitemap.xml
Sitemap: https://startup.ovhcloud.com/de/startup.ovhcloud.com_de_sitemap.xml
Sitemap: https://startup.ovhcloud.com/en-au/startup.ovhcloud.com_en-au_sitemap.xml
Sitemap: https://startup.ovhcloud.com/en-ca/startup.ovhcloud.com_en-ca_sitemap.xml
Sitemap: https://startup.ovhcloud.com/en-gb/startup.ovhcloud.com_en-gb_sitemap.xml
Sitemap: https://startup.ovhcloud.com/en-ie/startup.ovhcloud.com_en-ie_sitemap.xml
Sitemap: https://startup.ovhcloud.com/en-in/startup.ovhcloud.com_en-in_sitemap.xml
Sitemap: https://startup.ovhcloud.com/en-sg/startup.ovhcloud.com_en-sg_sitemap.xml
Sitemap: https://startup.ovhcloud.com/en/startup.ovhcloud.com_en_sitemap.xml
Sitemap: https://startup.ovhcloud.com/es-es/startup.ovhcloud.com_es_sitemap.xml
Sitemap: https://startup.ovhcloud.com/es/startup.ovhcloud.com_es-419_sitemap.xml
Sitemap: https://startup.ovhcloud.com/fr-ca/startup.ovhcloud.com_fr-ca_sitemap.xml
Sitemap: https://startup.ovhcloud.com/fr-ma/startup.ovhcloud.com_fr-ma_sitemap.xml
Sitemap: https://startup.ovhcloud.com/fr-sn/startup.ovhcloud.com_fr-sn_sitemap.xml
Sitemap: https://startup.ovhcloud.com/fr-tn/startup.ovhcloud.com_fr-tn_sitemap.xml
Sitemap: https://startup.ovhcloud.com/fr/startup.ovhcloud.com_fr_sitemap.xml
Sitemap: https://startup.ovhcloud.com/it/startup.ovhcloud.com_it_sitemap.xml
Sitemap: https://startup.ovhcloud.com/nl/startup.ovhcloud.com_nl_sitemap.xml
Sitemap: https://startup.ovhcloud.com/pl/startup.ovhcloud.com_pl_sitemap.xml
Sitemap: https://startup.ovhcloud.com/pt/startup.ovhcloud.com_pt-pt_sitemap.xml