User-agent: * 
Disallow: /actions
Disallow: /api
Disallow: /assets
Disallow: /css
Disallow: /cms
Disallow: /consortia
Disallow: /ebooks
Disallow: /find
Disallow: /json
Disallow: /php
Disallow: /settings
Disallow: /ssi
Disallow: /widgets