User-agent: *
Disallow: /en/confirm.html
Disallow: /de/confirm.html
Disallow: /en/confirmthanks.html
Disallow: /de/confirmthanks.html
Disallow: /en/error404.html
Disallow: /de/error404.html
Disallow: /en/unsubscribe.html
Disallow: /de/unsubscribe.html
Disallow: /en/video.html
Disallow: /de/video.html
Disallow: /en/privacy.html
Disallow: /de/privacy.html
Disallow: /en/terms.html
Disallow: /de/terms.html
Disallow: /en/coupon.html
Disallow: /de/coupon.html

Disallow: /blog/scanbot-7-major-update-featuring-industry-leading-filters/themes2x/
Disallow: /blog/how-scanbot-can-guide-you-through-tax-season/scanbot-organize-folders/
Disallow: /blog/scanbot-7-major-update-featuring-industry-leading-filters/medium-head2x/
Disallow: /blog/5-features-that-will-maximize-your-productivity-in-the-upcoming-semester/student-using-scanbot/
Disallow: /blog/scanbot-7-major-update-featuring-industry-leading-filters/iphone-and-documents2x/
Disallow: /blog/scanbot-scanner-app-fax-ios-android-clouds-search/download_android/
Disallow: /blog/5-additional-features-that-will-make-you-more-productive/scanbot-iphone/
Disallow: /blog/how-scanbot-can-guide-you-through-tax-season/scanbot-encryption/
Disallow: /blog/scanbot-scanner-app-fax-ios-android-clouds-search/scanbot_icons/
Disallow: /blog/scanbot-7-major-update-featuring-industry-leading-filters/datev2x/
Disallow: /blog/scanbot-scanner-app-fax-ios-android-clouds-search/download_ios/
Disallow: /blog/how-scanbot-can-guide-you-through-tax-season/scanbot-taxi-bill/
Disallow: /blog/scanbot-for-android-6-5-is-here/scanbot-for-android-6-5/
Disallow: /blog/scanbot-scanner-app-fax-ios-android-clouds-search/head_fax/
Disallow: /blog/the-scanbot-6-release-a-result-of-your-feedback/scanbot-6/
Disallow: /blog/use-scanbot-instead-phones-camera-app/automatic-scanning/
Disallow: /blog/todoist-meets-scanbot/todoist-integration-15-06-13-217/
Disallow: /blog/use-scanbot-instead-phones-camera-app/download_android-2/
Disallow: /blog/imessage-extension-for-scanbot-5-2/scanbot-imessage-extension/
Disallow: /blog/scanbot-scanner-app-fax-ios-android-clouds-search/newclouds/
Disallow: /blog/scanbot-for-android-6-5-is-here/scanbot-on-android-devices/
Disallow: /blog/keep-surfaces-clutter-free/honey-were-home-master-bedroom-81/
Disallow: /blog/how-scanbot-can-guide-you-through-tax-season/scanbot-clouds/
Disallow: /blog/keep-surfaces-clutter-free/cheryl-winn-boujnida-66160-2/
Disallow: /blog/todoist-meets-scanbot/todoist-integration-15-11-29-405/
Disallow: /blog/todoist-meets-scanbot/todoist-integration-15-02-00-549/
Disallow: /blog/scanbot-scanner-app-fax-ios-android-clouds-search/fax/
Disallow: /blog/how-scanbot-can-guide-you-through-tax-season/scanbot-taxes/
Disallow: /blog/use-scanbot-instead-phones-camera-app/download_ios-2/
Disallow: /blog/scanbot-scanner-app-fax-ios-android-clouds-search/group-7/
Disallow: /blog/use-scanbot-instead-phones-camera-app/camera-teaser/
Disallow: /blog/scanbot-for-android-6-5-is-here/merging-and-cloning/
Disallow: /blog/scanbot-6-our-biggest-release-yet/scanbot-6-teaser/
Disallow: /blog/keep-surfaces-clutter-free/cheryl-winn-boujnida-66160/
Disallow: /blog/imessage-extension-for-scanbot-5-2/scanbot-ios-10/
Disallow: /blog/use-scanbot-instead-phones-camera-app/artboard-2/
Disallow: /blog/use-scanbot-instead-phones-camera-app/color-filters/
Disallow: /blog/8-things-you-might-not-know-about-scanbot/8-things/
Disallow: /blog/your-presents-have-arrived/scanbot-user-feedback/
Disallow: /blog/english-version/scanbot-education-business-pro/
Disallow: /blog/scanbot-the-case-for-privacy/scanbot-privacy/
Disallow: /blog/why-do-i-have-to-pay-for-pro-features/iphone/
Disallow: /blog/why-do-i-have-to-pay-for-pro-features/no-ads/
Disallow: /blog/keep-surfaces-clutter-free/ofice/
Disallow: /blog/why-do-i-have-to-pay-for-pro-features/nl_share2x/
Disallow: /blog/keep-surfaces-clutter-free/dining-table/
Disallow: /blog/why-do-i-have-to-pay-for-pro-features/no-ads_en/
Disallow: /blog/scanbot-for-lawyers/scanbot-editing/
Disallow: /blog/why-do-i-have-to-pay-for-pro-features/bonn/
Disallow: /blog/use-scanbot-instead-phones-camera-app/head/
Disallow: /blog/scanbot-for-android-6-5-is-here/google-drive/
Disallow: /blog/your-presents-have-arrived/scanbot-present-box/
Disallow: /blog/todoist-meets-scanbot/todoist-integration/
Disallow: /blog/keep-surfaces-clutter-free/kitchen/
Disallow: /blog/scanbot-for-lawyers/scanbot-reminders/
Disallow: /blog/your-presents-have-arrived/thank-you/
Disallow: /blog/scanbot-for-lawyers/scanbot-for-lawyers-2/
Disallow: /blog/scanbot-for-lawyers/scanbot-sharing/
Disallow: /blog/scanbot-for-lawyers/scanbot-multi-page/
Disallow: /blog/scanbot-for-lawyers/scanbot-touch-id/
Disallow: /blog/scanbot-integration-with-google-docs-on-android-add-on/scanbot-integration-android/
Disallow: /blog/scanbot-for-lawyers/scanbot-tags/
