User-agent: *
Allow: /
Disallow: /includes/
Disallow: /infinity/
Disallow: /landing/
Disallow: /500apps
Disallow: /clanding
Disallow: /clanding
Disallow: /compare-1
Disallow: /compare
Disallow: /compare1
Disallow: /competitor-landing
Disallow: /competitors
Disallow: /index-2
Disallow: /landingc
Disallow: /pricing-block-1
Disallow: /pricing-block-2
Disallow: /pricing-block-3
Disallow: /adwords-1
Disallow: /agile-crm
Disallow: /compare-block
Disallow: /ebooks
Disallow: /e-books-summary
Disallow: /find-someone's-email-by-name
Disallow: /finder-pricing
Disallow: /finder-slider
Disallow: /sinner-compare-2
Disallow: /inner-compare-new
Disallow: /inner-compare
Disallow: /inner-ebooks
Disallow: /integration-summary
Disallow: /feature-summary
Disallow: /knowledge-page-home
Disallow: /kp-home
Disallow: /test-safari
Disallow: /test
Disallow: /top-three-block
Disallow: /500apps-block-3
Disallow: /500apps-home-overview
Disallow: /blog-home-summary-inner
Disallow: /blog-home-summary
Disallow: /blog-rhs
Disallow: /features-test
Disallow: /header
Disallow: /home-feature
Disallow: /home-new-2
Disallow: /home-new
Disallow: /knowledge-page-lhs
Disallow: /kp-inner-summary
Disallow: /pricing-1
Disallow: /pricing-block
Disallow: /pricing-feature
Disallow: /pricing-new1
Disallow: /pricing-new2
Disallow: /product
Disallow: /testimonial-one
Disallow: /testimonial-three
Disallow: /testimonial-two
Disallow: /topstrip
Disallow: /trusted-by-one
Disallow: /trusted-by
Disallow: /webinar-summary
Disallow: /lp/
Disallow: /ads/


Sitemap: https://teams.cc/sitemap.xml