User-Agent: *
Disallow: admin
Disallow: testcron
Disallow: jQueryAssets
Disallow: jQueryAssets-2 
Disallow: cron
Disallow: downloads
Disallow: database
Disallow: uploads
Disallow: test
Disallow: /details-page.php?id=168263326
Disallow: /details-page.php?id=220787040
Disallow: /details-page.php?id=220787047
Sitemap: https://thehinduimages.com/sitemap/index
