User-agent: *
Crawl-delay: 2
Disallow: /admin
Disallow: /nl/account/
Disallow: /de/account/
Disallow: /en/account/
Disallow: /fr/account/
Disallow: /nl/cart/
Disallow: /de/cart/
Disallow: /en/cart/
Disallow: /fr/cart/
Disallow: /nl/compare/
Disallow: /de/compare/
Disallow: /en/compare/
Disallow: /fr/compare/
Disallow: /nl/checkout/
Disallow: /de/checkout/
Disallow: /en/checkout/
Disallow: /fr/checkout/

Sitemap: https://themes.lightspeedhq.com/sitemap.xml