User-agent: *
Disallow: /_generated_assets/*
Disallow: /_layouts-*
Disallow: /account/*
Disallow: /admin-*
Disallow: /admin/*
Disallow: /assets/images/artwork/new-homepage-design/new-homepage-static-html/*
Disallow: /blog/tags/*
Disallow: /botmails/*
Disallow: /c/*
Disallow: /collections/*
Disallow: /console.html
Disallow: /contracts/*
Disallow: /.git/*
Disallow: /crm2/*
Disallow: /denied/*
Disallow: /docs/faq/why-charged-by-debuggable/*
Disallow: /docs/sdks/heroku-addon/*
Disallow: /docs/sdks/rawtemplate/*
Disallow: /docs/transcoding/artificial-intelligence/$
Disallow: /docs/transcoding/audio-encoding/$
Disallow: /docs/transcoding/code-evaluation/$
Disallow: /docs/transcoding/content-delivery/edgly-deliver/$
Disallow: /docs/transcoding/content-delivery/tlcdn-deliver/$
Disallow: /docs/transcoding/document-processing/$
Disallow: /docs/transcoding/file-compressing/$
Disallow: /docs/transcoding/file-filtering/$
Disallow: /docs/transcoding/handling-uploads/$
Disallow: /docs/transcoding/image-manipulation/$
Disallow: /docs/transcoding/media-cataloging/$
Disallow: /docs/transcoding/media-cataloging/media-playlist/$
Disallow: /docs/transcoding/video-encoding/$
Disallow: /errors/*
Disallow: /example_apps/*
Disallow: /factsheet.html
Disallow: /factsheet.md
Disallow: /factsheet.pdf
Disallow: /factsheet/*
Disallow: /integration-code-tester/*
Disallow: /linkinbio/*
Disallow: /newsletters/*
Disallow: /premium-packages/*
Disallow: /renderedsnippets/*
Disallow: /services/content-delivery/*
Disallow: /services/content-delivery/file-serve/*
Disallow: /services/media-cataloging/media-preview/$
Disallow: /stats-*
Disallow: /template-editor/*
Disallow: /unpublished/*
Sitemap: https://transloadit.com/sitemap.xml
