User-agent: *
Disallow: /caas/
Disallow: /comments/
Disallow: /photos/
Disallow: /lightbox/
Disallow: /fin_ms/
Disallow: /_td_api
Disallow: /tdv2_fp
Disallow: /nel_ms
Disallow: /fp_ms
Disallow: /sports_fp_ms
Disallow: /search_ms
Disallow: /*?bcmt=*
Sitemap: https://tw.news.yahoo.com/sitemap/sitemap_topic.xml.gz
Sitemap: https://tw.news.yahoo.com/sitemap/sitemap_tag.xml.gz
Sitemap: https://tw.news.yahoo.com/sitemap/sitemap_poll.xml.gz
Sitemap: https://tw.news.yahoo.com/sitemap/sitemap_pk.xml.gz
Sitemap: https://tw.news.yahoo.com/sitemap/sitemap_ybrain.xml.gz
Sitemap: https://tw.news.yahoo.com/sitemap/sitemap_pages.xml
Sitemap: https://tw.news.yahoo.com/sitemap/news-sitemap_index_TW_zh-Hant-TW.xml.gz
Sitemap: https://tw.news.yahoo.com/sitemap/news-sitemap_googlenewsindex_TW_zh-Hant-TW.xml.gz