User-agent: CCBot
Disallow: /

User-agent: ChatGPT-User
Disallow: /

User-agent: GPTBot
Disallow: /

User-agent: Google-Extended
Disallow: /

User-agent: *
Disallow: /tncms/tracking/
Disallow: /_services/
Disallow: /eedition/
Disallow: /nowapp/delete_account/
Disallow: /test/
Disallow: /test/arts_and_entertainment/
Disallow: /test/email/
Disallow: /test/jobs/
Disallow: /test/lifestyle/
Disallow: /test/local/
Disallow: /test/marketplace/
Disallow: /test/opinion/
Disallow: /test/sports/
Disallow: /tncms/weather/
Disallow: /tncms/tax/
Disallow: /tncms/block/
Disallow: /tncms/dmp/
Disallow: /tncms/openweb/*
Disallow: /tncms/counter/
Disallow: /tncms/openid2/
Disallow: /tncms/auth/
Disallow: /tncms/gtm/
Disallow: /tncms/media/
Disallow: /tncms/track/
Disallow: /tncms/webservice/
Disallow: /tncms/admin/
Disallow: /tncms/messaging/
Disallow: /tncms/search/
Disallow: /marketplace/*action=srch
Disallow: /content/tncms/assets/v3/form/
Disallow: /content/tncms/form/
Disallow: /classifieds/*?
Disallow: /housing/*?
Disallow: /jobs/*?
Disallow: /worship/*?
Disallow: /newspaperads/*?
Disallow: /tncms/calendar/
Disallow: /calendar/search/
Disallow: /calendar/club_organization_meetings/search/
Disallow: /calendar/fairs_festivals/search/
Disallow: /calendar/faith_related/search/
Disallow: /calendar/fundraisers/search/
Disallow: /calendar/live_music/search/
Disallow: /calendar/mixers_networking/search/
Disallow: /calendar/other/search/
Disallow: /calendar/sports/search/
Disallow: /calendar/theater_plays/search/
Disallow: /calendar/walks_runs_marathons/search/
Disallow: /tncms/user/
Disallow: /users/admin/
Disallow: /users/*/?
Disallow: /tncms/disqus/

Sitemap: https://tylerpaper.com/sitemap.xml
Sitemap: https://tylerpaper.com/tncms/sitemap/editorial.xml
Sitemap: https://tylerpaper.com/tncms/sitemap/editorial.xml?year=2006
Sitemap: https://tylerpaper.com/tncms/sitemap/editorial.xml?year=2011
Sitemap: https://tylerpaper.com/tncms/sitemap/editorial.xml?year=2012
Sitemap: https://tylerpaper.com/tncms/sitemap/editorial.xml?year=2013
Sitemap: https://tylerpaper.com/tncms/sitemap/editorial.xml?year=2014
Sitemap: https://tylerpaper.com/tncms/sitemap/editorial.xml?year=2015
Sitemap: https://tylerpaper.com/tncms/sitemap/editorial.xml?year=2016
Sitemap: https://tylerpaper.com/tncms/sitemap/editorial.xml?year=2017
Sitemap: https://tylerpaper.com/tncms/sitemap/editorial.xml?year=2018
Sitemap: https://tylerpaper.com/tncms/sitemap/editorial.xml?year=2019
Sitemap: https://tylerpaper.com/tncms/sitemap/editorial.xml?year=2020
Sitemap: https://tylerpaper.com/tncms/sitemap/editorial.xml?year=2021
Sitemap: https://tylerpaper.com/tncms/sitemap/editorial.xml?year=2022
Sitemap: https://tylerpaper.com/tncms/sitemap/editorial.xml?year=2023
