User-agent: * 
Allow: /
Sitemap: https://www.wardsauto.com/sitemap.xml
Sitemap: https://www.wardsauto.com/generic-content.xml
Sitemap: https://www.wardsauto.com/article-content-formats-index.xml
Sitemap: https://www.wardsauto.com/googlenews.xml
Sitemap: https://www.wardsauto.com/news-archive-index.xml
Sitemap: https://www.wardsauto.com/contributors.xml
Sitemap: https://www.wardsauto.com/podcast-archive-index.xml
Sitemap: https://www.wardsauto.com/webinar-archive-index.xml
Sitemap: https://www.wardsauto.com/document-archive-index.xml
Sitemap: https://www.wardsauto.com/event-archive-index.xml
Sitemap: https://www.wardsauto.com/videos-archive-index.xml
Sitemap: https://www.wardsauto.com/image-archive-index.xml
Sitemap: https://www.wardsauto.com/sitemap-index.xml
Disallow: /search
Disallow: /api/health
Disallow: /cdn-cgi/
User-agent: GPTBot
Disallow: /
Disallow: /live-preview/