User-agent: *

Disallow: *?q=
Disallow: /adpages/
Disallow: /akamai/
Disallow: /aprimoemails/
Disallow: /careers/landing-pages/
Disallow: /cd/
Disallow: /directnews
Disallow: /events/landing-pages/
Disallow: /events/ucdist/
Disallow: /flashmedia/
Disallow: /graphics/
Disallow: /graphicsnav/
Disallow: /htmlemails/
Disallow: /htmlform/
Disallow: /industries/landing-pages/
Disallow: /industries/electric/landing-page/
Disallow: /library/promoitems/
Disallow: /messages/
Disallow: /metadata/
Disallow: /products/includes/products-min.xml
Disallow: /scripts/
Disallow: /site/err_404.html
Disallow: /sitecore/
Disallow: /software/landing_pages/
Disallow: /_testing/
Disallow: /templates/
Disallow: /?utm_campaign=gisuser-esrisponsorlogo&utm_medium=esrilogo&utm_source=gisuser&utm_content=esrisponsor
Disallow: /~/media/Files/Pdfs/landing-pages/products/ventana-location-analytics-2013.pdf
Disallow: /~/media/Files/Pdfs/landing-pages/products/ventana-la-2013.pdf
Disallow: */_reused_content_block_items/section-items/mega-footer
Disallow: /software/arcgis-maps-for-office
Allow: /en-us/search$
Allow: /training/events/search/
Allow: /training/catalog/search/
Disallow: /training/catalog/search/options/
Disallow: /training/admin/
Disallow: /training/courses/
Disallow: /training/Engine/
Disallow: /training/mooc/player/
Disallow: /arcgis-blog/?s
Disallow: /arcgis-blog/search
Disallow: /arcgis-blog/page/
Disallow: /videos/search?
Disallow: /videos/iframe
Disallow: */?s=
Disallow: /search?filter
Disallow: /Search_New
Disallow: /content/esri-sites/
Allow: /content/esri-sites/*.jpg
Disallow: */thank-you-page
Disallow: */site-settings
Allow: /content/experience-fragments/esri-sites/en-us/site-settings/global-navigation-config/2022-nav-config.25.json
Allow: /content/experience-fragments/esri-sites/en-us/site-settings/one-form-admin/master/jcr:content/root/one_form_admin.json
Allow: */site-settings/global-navigation.js
Disallow: /about/events/uc/dynamic-content/
Disallow: */landing-page/product/2018/autodesk/aec
Disallow: */landing-page/lp/autodesk-infraworks-agol-subscription
Disallow: */content-parts/
Disallow: /en-us/arcgis/products/esri-story-maps
Allow: /en-us/arcgis/products/esri-story-maps/contest/overview
Allow: /en-us/arcgis/products/esri-story-maps/contest/get-started
Allow: /en-us/arcgis/products/esri-story-maps/contest/winners-gallery
Allow: /graphics/logotagline
Allow: /graphics/logos
Disallow: /about/newsroom/page/*/?s
Disallow: /about/newsroom/page/*/?tag
Disallow: */wp-login
Disallow: */wp-admin

Sitemap: https://www.esri.com/sitemap-sites.xml
#Sitemap: https://www.esri.com/sitemap.xml
Sitemap: https://www.esri.com/training/sitemap-training.xml
Sitemap: https://www.esri.com/about/newsroom/sitemap_index.xml
Sitemap: https://www.esri.com/arcgis-blog/sitemap_index.xml
Sitemap: https://www.esri.com/partners/sitemap-partners.xml
Sitemap: https://www.esri.com/partners/sitemap-solutions.xml
Sitemap: https://www.esri.com/careers/sitemap-careers.xml
Sitemap: https://www.esri.com/bin/esri/marketplacesitemapproducts
Sitemap: https://www.esri.com/bin/esri/marketplacesitemapservices
Sitemap: https://www.esri.com/en-us/industries/blog/blog-sitemap.xml
Sitemap: https://www.esri.com/en-us/industries/blog/author-sitemap.xml
Sitemap: https://www.esri.com/bin/esri/assetsitemap