User-agent: *

Disallow: /spa/
Disallow: /bundles/

Disallow: /iig/ 
Disallow: /variable/ 

Disallow: /contact-us/agent-appointment-inquiry
Disallow: /contact-us/agent-product-inquiry
Disallow: /contact-us/agent-account-inquiry
Disallow: /contact-us/agent-question
Disallow: /contact-us/agent-website-suggestion
Disallow: /contact-us/agent-compliment
Disallow: /contact-us/agent-concern
Disallow: /contact-us/client-policy-inquiry
Disallow: /contact-us/client-product-inquiry
Disallow: /contact-us/client-question
Disallow: /contact-us/client-website-suggestion
Disallow: /contact-us/client-compliment
Disallow: /contact-us/client-concern
Disallow: /contact-us/general-question
Disallow: /contact-us/general-website-suggestion
Disallow: /contact-us/general-media-inquiry
Disallow: /retirement-planning/retirement-income-calculator 
Disallow: /retirement-planning/tax-deferral-calculator
Disallow: /calculators/core-income-7-calculator
Disallow: /calculators/essential-income-7-calculator
Disallow: /ratewatch
Disallow: /rates
Disallow: /retirement-and-planning-tools/generations-apart/executive-summary-download
Disallow: /patterns
Disallow: /patterns/pages/annuities
Disallow: /patterns/molecules/cta-story4
Disallow: /em*
Disallow: /em/elif
Disallow: /em/efix
Disallow: /em/egen
Disallow: /em/evar

Disallow: /What-We-Offer/Life-Insurance/Tools-and-strategies-to-help-grow-your-life-insurance-business

Disallow: /new-york/login/change-password
Disallow: /new-york/login/change-password-success
Disallow: /new-york/login/fail-account-disabled
Disallow: /new-york/login/fail-account-disabled-individual
Disallow: /new-york/login/fail-account-disabled-life-agency
Disallow: /new-york/login/fail-account-disabled-success
Disallow: /new-york/login/fail-account-exiled
Disallow: /new-york/login/fail-account-locked
Disallow: /new-york/login/fail-account-locked-individual
Disallow: /new-york/login/fail-account-locked-life-agency
Disallow: /new-york/login/fail-account-locked-success
Disallow: /new-york/login/fail-account-questar
Disallow: /new-york/login/fail-account-terminated
Disallow: /new-york/login/fail-incorrect-login
Disallow: /new-york/login/forgot-password-fail
Disallow: /new-york/login/forgot-password-life-agency
Disallow: /new-york/login/forgot-password-select
Disallow: /new-york/login/forgot-password-success_dynamic
Disallow: /new-york/login/forgot-username-fail
Disallow: /new-york/login/forgot-username-life-agency
Disallow: /new-york/login/forgot-username-select
Disallow: /new-york/login/forgot-username-success_dynamic
Disallow: /new-york/login/login-challenge
Disallow: /new-york/login/logout
Disallow: /new-york/login/sitechooser


Disallow: /new-york/registration/fail-6th-time
Disallow: /new-york/registration/fail-account-exiled
Disallow: /new-york/registration/fail-existing-account-found
Disallow: /new-york/registration/fail-not-eligible-to-register
Disallow: /new-york/registration/fail-pending-account-found
Disallow: /new-york/registration/fail-questar
Disallow: /new-york/registration/fail-system-error
Disallow: /new-york/registration/life-agency
Disallow: /new-york/registration/success_dynamic
Disallow: /new-york/registration/validation-link-account-active
Disallow: /new-york/registration/validation-link-expired
Disallow: /new-york/registration/validation-link-invalid
Disallow: /new-york/registration/validation-link-success

Disallow: /login/change-password
Disallow: /login/change-password-success
Disallow: /login/edelivery
Disallow: /login/edelivery-charity-campaign
Disallow: /login/fail-account-disabled
Disallow: /login/fail-account-disabled-individual
Disallow: /login/fail-account-disabled-life-agency
Disallow: /login/fail-account-disabled-success_dynamic
Disallow: /login/fail-account-exiled
Disallow: /login/fail-account-locked
Disallow: /login/fail-account-locked-individual
Disallow: /login/fail-account-locked-life-agency
Disallow: /login/fail-account-locked-success
Disallow: /login/fail-account-terminated
Disallow: /login/fail-incorrect-login
Disallow: /login/forgot-password-fail
Disallow: /login/forgot-password-individual
Disallow: /login/forgot-password-life-agency
Disallow: /login/forgot-password-select
Disallow: /login/forgot-password-success_dynamic
Disallow: /login/forgot-username-fail
Disallow: /login/forgot-username-individual
Disallow: /login/forgot-username-life-agency
Disallow: /login/forgot-username-select
Disallow: /login/forgot-username-success_dynamic
Disallow: /login/InsufficientWMDRoles
Disallow: /login/logout
Disallow: /login/NotPermittedToLogon

Disallow: /registration/edelivery
Disallow: /registration/edelivery-contest-rules
Disallow: /registration/fail-6th-time
Disallow: /registration/fail-account-exiled
Disallow: /registration/fail-data-mismatch
Disallow: /registration/fail-existing-account-found
Disallow: /registration/fail-not-eligible-to-register
Disallow: /registration/fail-pending-account-found
Disallow: /registration/fail-soc-requireement
Disallow: /registration/fail-system-error
Disallow: /registration/life-agency
Disallow: /registration/missingdata
Disallow: /registration/registration-coupon-link-expired
Disallow: /registration/registration-coupon-link-invalid
Disallow: /registration/success_dynamic
Disallow: /registration/validation-link-account-active
Disallow: /registration/validation-link-expired
Disallow: /registration/validation-link-invalid
Disallow: /registration/validation-link-success


Disallow: /logout

Sitemap: https://www.allianzlife.com/sitemap.xml
