User-agent: *
Disallow: /

User-agent: bingbot
Allow: /
User-agent: BingPreview
Allow: /
User-agent: msnbot
Allow: /
User-agent: msnbot-media
Allow: /
User-agent: adidxbot
Allow: /
User-agent: Googlebot
Allow: /
User-agent: Googlebot-Image
Allow: /
User-agent: Googlebot-Mobile
Allow: /
User-agent: Googlebot-News
Allow: /
User-agent: Googlebot-Video
Allow: /
User-agent: Mediapartners-Google
Allow: /
User-agent: AdsBot-Google
Allow: /
User-agent: Twitterbot
Allow: /
User-agent: facebookexternalhit
Allow: /
User-agent: LinkedInBot
Allow: /



User-agent: DuckDuckBot
Disallow: /
User-agent: slurp
Disallow: /
User-agent: yandex
Disallow: /
User-agent: Applebot
Disallow: /
User-agent: Baiduspider
Disallow: /
User-agent: PiplBot
Disallow: /
User-agent: GPTBot
Disallow: /
User-agent: CCbot
Disallow: /
User-agent: anthropic-ai
Disallow: /
User-agent: Claude-Web
Disallow: /
User-agent: SemrushBot
Crawl-delay: 60
Disallow: /
User-agent: SemrushBot-BA
Crawl-delay: 60
Disallow: /
User-agent: AhrefsBot
Crawl-Delay: 60
Disallow: /
User-Agent: omgili
Disallow: /
User-agent: rogerbot
Disallow: /