User-agent: *
Disallow: */noindex/*
Disallow: */alumni/*
Disallow: */secure/*
Disallow: */mailings/*
Disallow: */?filters=*
Sitemap: https://www.bain.com/en/sitemap.xml
Sitemap: https://www.bain.com/pt-br/sitemap.xml
Sitemap: https://www.bain.com/es/sitemap.xml
Sitemap: https://www.bain.com/es-es/sitemap.xml
Sitemap: https://www.bain.com/fr/sitemap.xml
Sitemap: https://www.bain.com/de/sitemap.xml
Sitemap: https://www.bain.com/it/sitemap.xml
Sitemap: https://www.bain.com/el/sitemap.xml
Sitemap: https://www.bain.com/ko/sitemap.xml
Sitemap: https://www.bain.com/ja/sitemap.xml
Sitemap: https://www.bain.com/globalassets/sitemap/images-sitemap.xml
Sitemap: https://www.bain.com/globalassets/sitemap/video-sitemap.xml