####### Common #######

User-agent: *
Disallow: */config/*
Disallow: */errorpages/*
Disallow: */errorpages*
Disallow: */error-pages*
Disallow: */search.html*
Disallow: /*.gif$
Disallow: /*.pdf$
Disallow: /content/dam/onemarketing/ehndbx/
Disallow: /en_gl/
Disallow: /en_globalobal/
Disallow: /content/dam/onemarketing/euh/
Disallow: /en_global/APAC/free-buyer-pre-checks/
Disallow: /en_global/APAC.html
Disallow: /*?wordfence*
Disallow: /*utm_source=*
Disallow: /*?gclid=*
Disallow: /*?fbclid=*
Disallow: /*?platform=*
Disallow: /*?hsamp_network=*
Disallow: /*?s*
Disallow: /*?gh_jid=*
Disallow: /*?gh_src=*
Disallow: /*?loc_physical_ms=*
Disallow: /*?rc=*

Sitemap: https://www.allianz-trade.com/en.xml
Sitemap: https://www.allianz-trade.com/en_global.sitemap.xml
Sitemap: https://www.allianz-trade.com/en_CH.sitemap.xml
Sitemap: https://www.allianz-trade.com/it_CH.sitemap.xml
Sitemap: https://www.allianz-trade.com/fr_CH.sitemap.xml
Sitemap: https://www.allianz-trade.com/de_CH.sitemap.xml
Sitemap: https://www.allianz-trade.com/en_US.sitemap.xml
Sitemap: https://www.allianz-trade.com/en_CA.sitemap.xml
Sitemap: https://www.allianz-trade.com/fr_CA.sitemap.xml
Sitemap: https://www.allianz-trade.com/en_BR.sitemap.xml
Sitemap: https://www.allianz-trade.com/pt_BR.sitemap.xml
Sitemap: https://www.allianz-trade.com/pl_PL.sitemap.xml
Sitemap: https://www.allianz-trade.com/en_IE.sitemap.xml
Sitemap: https://www.allianz-trade.com/en_GB.sitemap.xml
Sitemap: https://www.allianz-trade.com/en_BE.sitemap.xml
Sitemap: https://www.allianz-trade.com/nl_BE.sitemap.xml
Sitemap: https://www.allianz-trade.com/fr_BE.sitemap.xml
Sitemap: https://www.allianz-trade.com/nl_NL.sitemap.xml
Sitemap: https://www.allianz-trade.com/cs_CZ.sitemap.xml
Sitemap: https://www.allianz-trade.com/sk_SK.sitemap.xml
Sitemap: https://www.allianz-trade.com/hu_HU.sitemap.xml
Sitemap: https://www.allianz-trade.com/ro_RO.sitemap.xml
Sitemap: https://www.allianz-trade.com/bg_BG.sitemap.xml
Sitemap: https://www.allianz-trade.com/da_DK.sitemap.xml
Sitemap: https://www.allianz-trade.com/sv_SE.sitemap.xml
Sitemap: https://www.allianz-trade.com/no_NO.sitemap.xml
Sitemap: https://www.allianz-trade.com/fi_FI.sitemap.xml
Sitemap: https://www.allianz-trade.com/lt_LT.sitemap.xml
Sitemap: https://www.allianz-trade.com/lv_LV.sitemap.xml
Sitemap: https://www.allianz-trade.com/et_EE.sitemap.xml
Sitemap: https://www.allianz-trade.com/it_IT.sitemap.xml
Sitemap: https://www.allianz-trade.com/tr_TR.sitemap.xml
Sitemap: https://www.allianz-trade.com/en_AE.sitemap.xml
Sitemap: https://www.allianz-trade.com/ar_AE.sitemap.xml
Sitemap: https://www.allianz-trade.com/fr_MA.sitemap.xml
Sitemap: https://www.allianz-trade.com/el_GR.sitemap.xml
Sitemap: https://www.allianz-trade.com/en_ZA.sitemap.xml
Sitemap: https://www.allianz-trade.com/en_HK.sitemap.xml
Sitemap: https://www.allianz-trade.com/zh_HK.sitemap.xml
Sitemap: https://www.allianz-trade.com/en_SG.sitemap.xml
Sitemap: https://www.allianz-trade.com/en_JP.sitemap.xml
Sitemap: https://www.allianz-trade.com/ja_JP.sitemap.xml
Sitemap: https://www.allianz-trade.com/en_TW.sitemap.xml
Sitemap: https://www.allianz-trade.com/zh_TW.sitemap.xml
Sitemap: https://www.allianz-trade.com/en_IN.sitemap.xml
Sitemap: https://www.allianz-trade.com/en_ID.sitemap.xml
Sitemap: https://www.allianz-trade.com/en_KR.sitemap.xml
Sitemap: https://www.allianz-trade.com/ko_KR.sitemap.xml
Sitemap: https://www.allianz-trade.com/en_MY.sitemap.xml
Sitemap: https://www.allianz-trade.com/ms_MY.sitemap.xml
Sitemap: https://www.allianz-trade.com/en_TH.sitemap.xml
Sitemap: https://www.allianz-trade.com/en_TH.sitemap.xml
Sitemap: https://www.allianz-trade.com/en_AU.sitemap.xml
Sitemap: https://www.allianz-trade.com/en_NZ.sitemap.xml