User-agent: *
Allow: /includes/cookie-policy/js/cookie-policy.js
Allow: /includes/cookie-policy/css/cookie-policy.css
Disallow: /connectdev.php
Disallow: /connectdev.php?p=login&username=*$
Disallow: /search/
Disallow: /includes/*
Disallow: /embedded-jlink/
Disallow: /embedded-link/
Disallow: /uploadajax.php
Disallow: /forums/*$
Disallow: /upload_dld.php
Sitemap: https://www.123formbuilder.com/sitemap_index.xml
Sitemap: https://www.123formbuilder.com/blog/sitemap_index.xml
Sitemap: https://www.123formbuilder.com/docs/sitemap_index.xml
Sitemap: https://www.123formbuilder.com/free-form-templates-sitemap1.xml
Sitemap: https://www.123formbuilder.com/free-form-templates-sitemap2.xml
Sitemap: https://www.123formbuilder.com/free-form-templates-sitemap3.xml
Sitemap: https://www.123formbuilder.com/section-sitemap.xml