User-agent: *
Disallow: /search
Disallow: /navy-wireless-contract/*
Disallow: /acc-apg-wireless-bpa/*
Disallow: /gsa-fssi/*
Disallow: /ucvoice/*
Disallow: /ucclient/*
Disallow: /dept-of-comm/*
Disallow: /supportsvcs/*
