User-agent: *
Disallow: /preparesite/empty.js*
Disallow: /cdn-cgi/beacon/performance*
Disallow: /*/v_premium_not_allowed/*.html$
Disallow: /*v_detail_tab_print*.html$
Disallow: /*v_detail_tab_comments/*
Disallow: /ajaxentry/
Disallow: /*imagelightbox?elementId*
Disallow: /user-registrierung/
Disallow: /*;jsessionid=*
Disallow: /*jsessionid=*
Disallow: /*action=activate*
Disallow: /lesezeichen/
Disallow: /registrierung/
Disallow: /*?ajaxelementid=*
Disallow: /*ajaxelementid=*
Disallow: /*?view=print*
Disallow: /*view=print*
Disallow: /*?view=lightbox
Disallow: /*view=lightbox*
Disallow: /channelizer/
Disallow: /themen/my/*
Disallow: /meine-news*
Disallow: /api/*
Allow: /api/content
Disallow: */partials/htmlbox/*
Disallow: */iframe_grafik.html*
Disallow: */v_advertorial_detail/*
Disallow: */amp-ivw.html*
Disallow: */partials/related*
Disallow: /cdn-cgi/rum*
Disallow: /boerse/option/*
Disallow: /boerse/zertifikat/*
Disallow: /recommendation/hb_web/offerpage*
Disallow: /cdn-cgi/

User-agent: ChatGPT-User
Disallow: /

User-agent: GPTBot
Disallow: /

user-agent: Google-Extended
Disallow: /

User-agent: CCBot
Disallow: /

Sitemap: https://www.handelsblatt.com/news.xml
Sitemap: https://www.handelsblatt.com/contentexport/feed/sitemap/themen
Sitemap: https://www.handelsblatt.com/sitemapExternal/sitemaps_ressorts.xml
Sitemap: https://www.handelsblatt.com/sitemapExternal/sitemaps_videos.xml
Sitemap: https://www.handelsblatt.com/sitemapExternal/sitemaps_index_1999.xml
Sitemap: https://www.handelsblatt.com/sitemapExternal/sitemaps_index_2000.xml
Sitemap: https://www.handelsblatt.com/sitemapExternal/sitemaps_index_2001.xml
Sitemap: https://www.handelsblatt.com/sitemapExternal/sitemaps_index_2002.xml
Sitemap: https://www.handelsblatt.com/sitemapExternal/sitemaps_index_2003.xml
Sitemap: https://www.handelsblatt.com/sitemapExternal/sitemaps_index_2004.xml
Sitemap: https://www.handelsblatt.com/sitemapExternal/sitemaps_index_2005.xml
Sitemap: https://www.handelsblatt.com/sitemapExternal/sitemaps_index_2006.xml
Sitemap: https://www.handelsblatt.com/sitemapExternal/sitemaps_index_2007.xml
Sitemap: https://www.handelsblatt.com/sitemapExternal/sitemaps_index_2008.xml
Sitemap: https://www.handelsblatt.com/sitemapExternal/sitemaps_index_2009.xml
Sitemap: https://www.handelsblatt.com/sitemapExternal/sitemaps_index_2010.xml
Sitemap: https://www.handelsblatt.com/sitemapExternal/sitemaps_index_2011.xml
Sitemap: https://www.handelsblatt.com/sitemapExternal/sitemaps_index_2012.xml
Sitemap: https://www.handelsblatt.com/sitemapExternal/sitemaps_index_2013.xml
Sitemap: https://www.handelsblatt.com/sitemapExternal/sitemaps_index_2014.xml
Sitemap: https://www.handelsblatt.com/sitemapExternal/sitemaps_index_2015.xml
Sitemap: https://www.handelsblatt.com/sitemapExternal/sitemaps_index_2016.xml
Sitemap: https://www.handelsblatt.com/sitemapExternal/sitemaps_index_2017.xml
Sitemap: https://www.handelsblatt.com/sitemapExternal/sitemaps_index_2018.xml
Sitemap: https://www.handelsblatt.com/sitemapExternal/sitemaps_index_2019.xml
Sitemap: https://www.handelsblatt.com/sitemapExternal/sitemaps_index_2020.xml
Sitemap: https://www.handelsblatt.com/sitemapExternal/sitemaps_index_2021.xml
Sitemap: https://www.handelsblatt.com/sitemapExternal/sitemaps_index_2022.xml
Sitemap: https://www.handelsblatt.com/sitemapExternal/sitemaps_index_2023.xml
Sitemap: https://www.handelsblatt.com/sitemapExternal/sitemaps_index_2024.xml
