User-agent: *
Allow: /
Disallow: */sandbox
Disallow: */api
Disallow: /ru
Disallow: */content/qatartourism/*

Sitemap: https://www.qatartourism.com/en/sitemap.xml
Sitemap: https://www.qatartourism.com/ru/sitemap.xml
Sitemap: https://www.qatartourism.com/ar/sitemap.xml
Sitemap: https://www.qatartourism.com/de/sitemap.xml
Sitemap: https://www.qatartourism.com/fr/sitemap.xml
Sitemap: https://www.qatartourism.com/it/sitemap.xml
Sitemap: https://www.qatartourism.com/es/sitemap.xml
Sitemap: https://www.qatartourism.com/tr/sitemap.xml
Sitemap: https://www.qatartourism.com/zh/sitemap.xml
Sitemap: https://www.qatartourism.com/pt/sitemap.xml
Sitemap: https://www.qatartourism.com/jp/sitemap.xml
Sitemap: https://www.qatartourism.com/fa/sitemap.xml
Sitemap: https://www.qatartourism.com/ko/sitemap.xml