User-agent: *
Disallow: /x01122019-higfiles/
Disallow: /sbo/registration/
Disallow: /higrd16/
Disallow: /newhire/
Disallow: /benefits-resource/
Disallow: /higfiles/
Disallow: /coverage-identifier/
Disallow: /theGIC_myTomorrow/
Disallow: /home-sales/
Disallow: /internet-sales/
Sitemap: https://www.thehartford.com/sitemap.xml