User-agent: * 
Disallow: https://www.aussiespecialist.com/zh/404.html
Disallow: https://www.aussiespecialist.com/zh-hk/404.html
Disallow: https://www.aussiespecialist.com/en/404.html
Disallow: https://www.aussiespecialist.com/fr-fr/404.html
Disallow: https://www.aussiespecialist.com/de-de/404.html
Disallow: https://www.aussiespecialist.com/id-id/404.html
Disallow: https://www.aussiespecialist.com/it-it/404.html
Disallow: https://www.aussiespecialist.com/ja-jp/404.html
Disallow: https://www.aussiespecialist.com/ko-kr/404.html
Disallow: https://www.aussiespecialist.com/en-sg/404.html
Disallow: https://www.aussiespecialist.com/en-in/404.html
Disallow: https://www.aussiespecialist.com/en-my/404.html
Disallow: https://www.aussiespecialist.com/en-gb/404.html
Disallow: https://www.aussiespecialist.com/en-nz/404.html
Disallow: https://www.aussiespecialist.com/en-ca/404.html
Disallow: https://www.aussiespecialist.com/en-us/404.html
Disallow: /global-master/*
Disallow: /na/*
Disallow: /gb/*
Disallow: /sea/*
Disallow: /id/*
Disallow: /eu/*
Disallow: /fr/*
Disallow: /it/*
Disallow: /de/*
Disallow: /nas/*
Disallow: /ja/*
Disallow: /ko/*
Disallow: /zh/*
Disallow: /cn/*
Disallow: /te-lc/*
Disallow: */component-archive/*
Disallow: */test-content/*
Disallow: */test-pages/*
Disallow: /*.pdf$
Disallow: */pdf/*
Sitemap: https://www.aussiespecialist.com/zh/sitemap.xml
Sitemap: https://www.aussiespecialist.com/zh-hk/sitemap.xml
Sitemap: https://www.aussiespecialist.com/en/sitemap.xml
Sitemap: https://www.aussiespecialist.com/fr-fr/sitemap.xml
Sitemap: https://www.aussiespecialist.com/de-de/sitemap.xml
Sitemap: https://www.aussiespecialist.com/id-id/sitemap.xml
Sitemap: https://www.aussiespecialist.com/it-it/sitemap.xml
Sitemap: https://www.aussiespecialist.com/ja-jp/sitemap.xml
Sitemap: https://www.aussiespecialist.com/ko-kr/sitemap.xml
Sitemap: https://www.aussiespecialist.com/en-sg/sitemap.xml
Sitemap: https://www.aussiespecialist.com/en-in/sitemap.xml
Sitemap: https://www.aussiespecialist.com/en-my/sitemap.xml
Sitemap: https://www.aussiespecialist.com/en-gb/sitemap.xml
Sitemap: https://www.aussiespecialist.com/en-nz/sitemap.xml
Sitemap: https://www.aussiespecialist.com/en-ca/sitemap.xml
Sitemap: https://www.aussiespecialist.com/en-us/sitemap.xml
