User-agent: Applebot
Allow: /
Disallow: /typo3/
Allow: /typo3/sysext/*/Resources/Public/
Disallow: /typo3conf/
Allow: /typo3conf/ext/*/Resources/Public/ 
Allow: /typo3conf/ext/solr/Resources/Css/  
Disallow: /fileadmin/
Allow: /fileadmin/sites/etnic/uploads/ 
Allow: /fileadmin/sites/etnic/css/
Allow: /fileadmin/sites/etnic/js/
Allow: /fileadmin/_processed_/* 
Allow: /*?id=*   
Allow: /*?type=*  
Allow: /*?eID=*
Allow: /typo3temp/  
Disallow: /typo3temp/var/  
Disallow: /typo3temp/logs/ 

User-agent: Bingbot
Allow: /
Disallow: /typo3/
Allow: /typo3/sysext/*/Resources/Public/
Disallow: /typo3conf/
Allow: /typo3conf/ext/*/Resources/Public/ 
Allow: /typo3conf/ext/solr/Resources/Css/  
Disallow: /fileadmin/
Allow: /fileadmin/sites/etnic/uploads/ 
Allow: /fileadmin/sites/etnic/css/
Allow: /fileadmin/sites/etnic/js/
Allow: /fileadmin/_processed_/* 
Allow: /*?id=*   
Allow: /*?type=*  
Allow: /*?eID=*
Allow: /typo3temp/  
Disallow: /typo3temp/var/  
Disallow: /typo3temp/logs/ 

User-agent: Googlebot
Allow: /
Disallow: /typo3/
Allow: /typo3/sysext/*/Resources/Public/
Disallow: /typo3conf/
Allow: /typo3conf/ext/*/Resources/Public/ 
Allow: /typo3conf/ext/solr/Resources/Css/  
Disallow: /fileadmin/
Allow: /fileadmin/sites/etnic/uploads/ 
Allow: /fileadmin/sites/etnic/css/
Allow: /fileadmin/sites/etnic/js/
Allow: /fileadmin/_processed_/* 
Allow: /*?id=*   
Allow: /*?type=*  
Allow: /*?eID=*
Allow: /typo3temp/  
Disallow: /typo3temp/var/  
Disallow: /typo3temp/logs/ 

User-agent: ia_archiver
Allow: /
Disallow: /typo3/
Allow: /typo3/sysext/*/Resources/Public/
Disallow: /typo3conf/
Allow: /typo3conf/ext/*/Resources/Public/ 
Allow: /typo3conf/ext/solr/Resources/Css/  
Disallow: /fileadmin/
Allow: /fileadmin/sites/etnic/uploads/ 
Allow: /fileadmin/sites/etnic/css/
Allow: /fileadmin/sites/etnic/js/
Allow: /fileadmin/_processed_/* 
Allow: /*?id=*   
Allow: /*?type=*  
Allow: /*?eID=*
Allow: /typo3temp/  
Disallow: /typo3temp/var/  
Disallow: /typo3temp/logs/ 

User-agent: msnbot
Allow: /
Disallow: /typo3/
Allow: /typo3/sysext/*/Resources/Public/
Disallow: /typo3conf/
Allow: /typo3conf/ext/*/Resources/Public/ 
Allow: /typo3conf/ext/solr/Resources/Css/  
Disallow: /fileadmin/
Allow: /fileadmin/sites/etnic/uploads/ 
Allow: /fileadmin/sites/etnic/css/
Allow: /fileadmin/sites/etnic/js/
Allow: /fileadmin/_processed_/* 
Allow: /*?id=*   
Allow: /*?type=*  
Allow: /*?eID=*
Allow: /typo3temp/  
Disallow: /typo3temp/var/  
Disallow: /typo3temp/logs/ 

User-agent: Naverbot
Allow: /
Disallow: /typo3/
Allow: /typo3/sysext/*/Resources/Public/
Disallow: /typo3conf/
Allow: /typo3conf/ext/*/Resources/Public/ 
Allow: /typo3conf/ext/solr/Resources/Css/  
Disallow: /fileadmin/
Allow: /fileadmin/sites/etnic/uploads/ 
Allow: /fileadmin/sites/etnic/css/
Allow: /fileadmin/sites/etnic/js/
Allow: /fileadmin/_processed_/* 
Allow: /*?id=*   
Allow: /*?type=*  
Allow: /*?eID=*
Allow: /typo3temp/  
Disallow: /typo3temp/var/  
Disallow: /typo3temp/logs/ 

User-agent: seznambot
Allow: /
Disallow: /typo3/
Allow: /typo3/sysext/*/Resources/Public/
Disallow: /typo3conf/
Allow: /typo3conf/ext/*/Resources/Public/ 
Allow: /typo3conf/ext/solr/Resources/Css/  
Disallow: /fileadmin/
Allow: /fileadmin/sites/etnic/uploads/ 
Allow: /fileadmin/sites/etnic/css/
Allow: /fileadmin/sites/etnic/js/
Allow: /fileadmin/_processed_/* 
Allow: /*?id=*   
Allow: /*?type=*  
Allow: /*?eID=*
Allow: /typo3temp/  
Disallow: /typo3temp/var/  
Disallow: /typo3temp/logs/ 

User-agent: Slurp
Allow: /
Disallow: /typo3/
Allow: /typo3/sysext/*/Resources/Public/
Disallow: /typo3conf/
Allow: /typo3conf/ext/*/Resources/Public/ 
Allow: /typo3conf/ext/solr/Resources/Css/  
Disallow: /fileadmin/
Allow: /fileadmin/sites/etnic/uploads/ 
Allow: /fileadmin/sites/etnic/css/
Allow: /fileadmin/sites/etnic/js/
Allow: /fileadmin/_processed_/* 
Allow: /*?id=*   
Allow: /*?type=*  
Allow: /*?eID=*
Allow: /typo3temp/  
Disallow: /typo3temp/var/  
Disallow: /typo3temp/logs/ 

User-agent: teoma
Allow: /
Disallow: /typo3/
Allow: /typo3/sysext/*/Resources/Public/
Disallow: /typo3conf/
Allow: /typo3conf/ext/*/Resources/Public/ 
Allow: /typo3conf/ext/solr/Resources/Css/  
Disallow: /fileadmin/
Allow: /fileadmin/sites/etnic/uploads/ 
Allow: /fileadmin/sites/etnic/css/
Allow: /fileadmin/sites/etnic/js/
Allow: /fileadmin/_processed_/* 
Allow: /*?id=*   
Allow: /*?type=*  
Allow: /*?eID=*
Allow: /typo3temp/  
Disallow: /typo3temp/var/  
Disallow: /typo3temp/logs/ 

User-agent: Twitterbot
Allow: /
Disallow: /typo3/
Allow: /typo3/sysext/*/Resources/Public/
Disallow: /typo3conf/
Allow: /typo3conf/ext/*/Resources/Public/ 
Allow: /typo3conf/ext/solr/Resources/Css/  
Disallow: /fileadmin/
Allow: /fileadmin/sites/etnic/uploads/ 
Allow: /fileadmin/sites/etnic/css/
Allow: /fileadmin/sites/etnic/js/
Allow: /fileadmin/_processed_/* 
Allow: /*?id=*   
Allow: /*?type=*  
Allow: /*?eID=*
Allow: /typo3temp/  
Disallow: /typo3temp/var/  
Disallow: /typo3temp/logs/ 

User-agent: Yandex
Allow: /
Disallow: /typo3/
Allow: /typo3/sysext/*/Resources/Public/
Disallow: /typo3conf/
Allow: /typo3conf/ext/*/Resources/Public/ 
Allow: /typo3conf/ext/solr/Resources/Css/  
Disallow: /fileadmin/
Allow: /fileadmin/sites/etnic/uploads/ 
Allow: /fileadmin/sites/etnic/css/
Allow: /fileadmin/sites/etnic/js/
Allow: /fileadmin/_processed_/* 
Allow: /*?id=*   
Allow: /*?type=*  
Allow: /*?eID=*
Allow: /typo3temp/  
Disallow: /typo3temp/var/  
Disallow: /typo3temp/logs/ 

User-agent: Yeti
Allow: /
Disallow: /typo3/
Allow: /typo3/sysext/*/Resources/Public/
Disallow: /typo3conf/
Allow: /typo3conf/ext/*/Resources/Public/ 
Allow: /typo3conf/ext/solr/Resources/Css/  
Disallow: /fileadmin/
Allow: /fileadmin/sites/etnic/uploads/ 
Allow: /fileadmin/sites/etnic/css/
Allow: /fileadmin/sites/etnic/js/
Allow: /fileadmin/_processed_/* 
Allow: /*?id=*   
Allow: /*?type=*  
Allow: /*?eID=*
Allow: /typo3temp/  
Disallow: /typo3temp/var/  
Disallow: /typo3temp/logs/ 

User-agent: *
Disallow: /

Sitemap: https://www.etnic.be/sitemap.xml