User-agent: *
Allow: /
Disallow: /want-cars/
Disallow: /admin/
Disallow: /newcar/
Disallow: /newbike/
Disallow: /classifieds/
Disallow: /bike-classifieds/
Disallow: /evaluation/
Disallow: /ndtv/
Disallow: /vehicle/
Disallow: *?variant1=
Disallow: *?variant2=
Disallow: *?id3=
Disallow: *?q=
Disallow: *?model=
Disallow: *?tvc_universalCookie=
Disallow: *?model3=
Disallow: *?listing=
Sitemap: https://www.carandbike.com/sitemap.xml
Sitemap: https://www.carandbike.com/news/sitemap.xml