user-agent: *
Disallow: /~campaign-ns
Disallow: /aboutcigna/cigna-leadership-team/
Disallow: /campaigns/
Disallow: /customer_care/
Disallow: /eapmanager/
Disallow: /healthcarepartners/
Disallow: /healthy-benefits/
Disallow: /individuals-families/campaigns/
Disallow: /individuals-families/external_policy_disclosure
Disallow: /maintenancerx
Disallow: /mckesson/
Disallow: /medicare-campaigns/
Disallow: /medicare/medicare-campaigns/
Disallow: /medicare/campaigns/
Disallow: /pharmacy-networks/pharmacy-network-1
Disallow: /pharmacy-networks/pharmacy-network-2
Disallow: /pharmacy-networks/pharmacy-network-3
Disallow: /assets/docs/personal/pharmacy-networks/876412-pharmacy-qa-flyer-no-walgreens.pdf
Disallow: /assets/docs/personal/pharmacy-networks/876349-pharmacy-qa-flyer-no-cvs-or-walgreens.pdf
Disallow: /pod/
Disallow: /predisability/
Disallow: /scripps/
Disallow: /sites/
Disallow: /sites/careallies/
Disallow: /sjhh/
Disallow: /sp/
Disallow: /assets/docs/sp/
Disallow: /spn/
Disallow: /transformations/
Disallow: /client-forum/login-set
Disallow: /assets/docs/Cigna%20notices-of-privacy-practices/stay-at-work-services/881532-pre-dis-voc-service-schedule-10-27-final.pdf
Disallow: /assets/docs/Cigna%20notices-of-privacy-practices/stay-at-work-services/881535-saw-participant-guide-v4-final.pdf
Disallow: /assets/docs/business/tpa/hiv-consent-form-new-hampshire.pdf
Disallow: /surefit-game/
Disallow: /assets/docs/insperity-gul-certificate.pdf
Disallow: /world-bank/
Disallow: /withyou/
Disallow: /willistowerswatson-medical/
Disallow: /willistowerswatson-medicalrx/
Disallow: /utc/
Disallow: /sterlinginsurance/
Disallow: /statestreet/
Disallow: /pitneybowes/
Disallow: /nationwide/
Disallow: /mercer/
Disallow: /jps/
Disallow: /gs/
Disallow: /aonactivehealth-withyou-2018/
Disallow: /aonactivehealth-2018/
Disallow: /sites/sodexo/
Disallow: /search*
Disallow: /ascension*
Disallow: /individuals-families/health-wellness/topic-autism/seminars/
Disallow: /individuals-families/health-wellness/topic-substance-use-disorders/seminars/
Disallow: /individuals-families/health-wellness/topic-eating-disorders/seminars/
Disallow: /individuals-families/health-wellness/topic-mental-health/seminars/
Disallow: /iwov-resources/the-bridge/
Disallow: /medicare-2020/
Disallow: /health-promotion/
Disallow: /disability/
Disallow: /the-bridge
Disallow: /the-bridge/
Disallow: /ubs/
Disallow: /privacyinformation/employment-privacy-and-data-protection/career-policy/kenya
Disallow: /privacyinformation/employment-privacy-and-data-protection/career-policy/lebanon
Disallow: /privacyinformation/employment-privacy-and-data-protection/career-policy/saudiarabia
Disallow: /privacyinformation/employment-privacy-and-data-protection/career-policy/uae
Disallow: /static/www-cigna-com/docs/health-care-providers/copay_override_032306.pdf
Disallow: /static/www-cigna-com/docs/pharmacy/prior-authorization-032306.pdf
Disallow: /iwov-resources/national-second-sale/docs/healthy-benefits/healthy-habits-incentive-instructions.pdf
Disallow: /edison/
Disallow: /syneoshealth-clinical/
Disallow: /digital.cigna.com/
Disallow: /individuals-families/member-resources/cigna-90-now-cvs
Disallow: /individuals-families/member-resources/cigna-90-now-walgreens
Sitemap: https://www.cigna.com/sitemap.xml
Sitemap: https://www.cigna.com/sitemap-v2.xml
Sitemap: https://www.cigna.com/sitemap-es-us.xml
Sitemap: https://www.cigna.com/healthwise.xml
Sitemap: https://www.cigna.com/healthwise-es.xml