User-agent: * 
Disallow: */component-archive/*
Disallow: */404.html
Disallow: */atdw/*
Disallow: */search.html?q=*
Disallow: /en-us/favourites.html
Disallow: /*.pdf$
Disallow: */pdf/*
Disallow: /global-master/*
Disallow: /na/*
Disallow: /gb/*
Disallow: /sea/*
Disallow: /id/*
Disallow: /eu/*
Disallow: /fr/*
Disallow: /it/*
Disallow: /de/*
Disallow: /nas/*
Disallow: /ja/*
Disallow: /ko/*
Disallow: /zh/*
Disallow: /cn/*
Disallow: */te-lc/*
Disallow: */test-content/*
Disallow: */test-pages/*
Sitemap: https://www.australia.com/en/sitemap.xml
Sitemap: https://www.australia.com/en-us/sitemap.xml
Sitemap: https://www.australia.com/en-ca/sitemap.xml
Sitemap: https://www.australia.com/en-gb/sitemap.xml
Sitemap: https://www.australia.com/en-sg/sitemap.xml
Sitemap: https://www.australia.com/en-my/sitemap.xml
Sitemap: https://www.australia.com/en-in/sitemap.xml
Sitemap: https://www.australia.com/fr-fr/sitemap.xml
Sitemap: https://www.australia.com/de-de/sitemap.xml
Sitemap: https://www.australia.com/id-id/sitemap.xml
Sitemap: https://www.australia.com/it-it/sitemap.xml
Sitemap: https://www.australia.com/ko-kr/sitemap.xml
Sitemap: https://www.australia.com/ja-jp/sitemap.xml
Sitemap: https://www.australia.com/zh-hk/sitemap.xml
Sitemap: https://www.australia.com/en-nz/sitemap.xml
Sitemap: https://www.australia.com/zh-tw/sitemap.xml
Sitemap: https://www.australia.com/en/video-sitemap.xml
Sitemap: https://www.australia.com/en-us/video-sitemap.xml
Sitemap: https://www.australia.com/en-ca/video-sitemap.xml
Sitemap: https://www.australia.com/en-gb/video-sitemap.xml
Sitemap: https://www.australia.com/en-sg/video-sitemap.xml
Sitemap: https://www.australia.com/en-my/video-sitemap.xml
Sitemap: https://www.australia.com/en-in/video-sitemap.xml
Sitemap: https://www.australia.com/fr-fr/video-sitemap.xml
Sitemap: https://www.australia.com/de-de/video-sitemap.xml
Sitemap: https://www.australia.com/id-id/video-sitemap.xml
Sitemap: https://www.australia.com/it-it/video-sitemap.xml
Sitemap: https://www.australia.com/ko-kr/video-sitemap.xml
Sitemap: https://www.australia.com/ja-jp/video-sitemap.xml
Sitemap: https://www.australia.com/zh-hk/video-sitemap.xml
Sitemap: https://www.australia.com/en-nz/video-sitemap.xml
Sitemap: https://www.australia.com/zh-tw/video-sitemap.xml