User-agent: CrazyWebCrawler-Spider
Disallow: /

User-agent: *
Disallow: /img/users
Disallow: /app/search
Disallow: /cgi-bin/search.fpl
Disallow: /patterns
Disallow: /jobs/posting_clicks
Disallow: /user-ass/jobs/posting_pdf
Disallow: /publicsearch/
Disallow: /search/
Disallow: /people/search/
Disallow: /r/
Disallow: /xbp/search
Disallow: /go/login
Disallow: /ads/
Disallow: /jobs/search/
Disallow: /start/
Allow: /start/signup
Disallow: /start/signup?*
Disallow: /signup?*
Disallow: /xing-one/api
Disallow: /graphql/api
Disallow: */external-application
Disallow: /pages/*:CSV2024*
Disallow: /pages/ä¹°*
Disallow: /pages/è´­*
Disallow: /pages/å *
Disallow: /pages/è³*
Disallow: /pages/è¯*
Disallow: /pages/è¿·*
Disallow: /pages/åª*
Disallow: /pages/ç½*
Disallow: /pages/é*
Disallow: /pages/æ°´*
Disallow: /pages/æ*
Disallow: /pages/å*
Disallow: /pages/æ*
Disallow: /pages/ç*
Disallow: /pages/ä¹*
Disallow: /pages/å¬*
Disallow: /pages/å®*
Disallow: /pages/å°*
Disallow: /pages/åº*
Disallow: /pages/æ¥*
Disallow: /pages/å¼º*
Disallow: /pages/ä¹*
Disallow: /pages/å¤*
Disallow: /pages/ä¸*
Disallow: /pages/æ*
Disallow: /pages/ç¨*
Disallow: /pages/å¨*
Disallow: /pages/æ*
Disallow: /pages/å£*
Disallow: /pages/å°*
Disallow: /pages/å¯*
Disallow: /pages/é¦*
Disallow: /pages/é±*
Disallow: /pages/åº*
Disallow: /pages/å¹»*
Disallow: /pages/ä»¥*
Disallow: /pages/æ*
Disallow: /pages/è®¢*
Disallow: /pages/ç²*
Disallow: /pages/ä½*
Disallow: /pages/å¬*
Disallow: /pages/å*
Disallow: /pages/äºº*
Disallow: /pages/è*
Disallow: /pages/è*
Disallow: /pages/ç *
Disallow: /pages/çº¿*
Disallow: /pages/å¥³*
Disallow: /pages/è¯*
Disallow: /pages/æ­£*
Disallow: /pages/å·*
Disallow: /pages/ä»*
Disallow: /pages/ç*
Disallow: /pages/ç¡*
Disallow: /pages/æ*
Disallow: /pages/å¥¸*
Disallow: /pages/å¶*
Disallow: /pages/é±¼*
Disallow: /pages/å®*
Disallow: /pages/å¤±*
Disallow: /pages/é­*
Disallow: /pages/å¦*
Disallow: /pages/ä½*
Disallow: /pages/å®*
Disallow: /pages/ç«*
Disallow: /pages/å*
Disallow: /pages/æ ¼*
Disallow: /pages/è½*
Disallow: /pages/æ·*
Disallow: /pages/æ¶²*
Disallow: /pages/åª*
Disallow: /pages/å*
Disallow: /pages/ä»·*
Disallow: /pages/ä»*
Disallow: /pages/ä¸*
Disallow: /pages/è*
Disallow: /pages/ç³»*
Disallow: /pages/å*
Disallow: /pages/å*
Disallow: /pages/æ*
Disallow: /pages/ä¸*
Disallow: /pages/æ»´*
Disallow: /pages/ä¼*
Disallow: /pages/è®©*
Disallow: /pages/æ¹*
Disallow: /pages/æ§*
Disallow: /pages/å*
Disallow: /pages/ä»*
Disallow: /pages/é²*
Disallow: /pages/å¿*
Disallow: /pages/ç*
Disallow: /pages/æ*
Disallow: /pages/è¿*
Disallow: /pages/å¡*
Disallow: /pages/é*
Disallow: /pages/è©*
Disallow: /pages/æ*
Disallow: /pages/æ*
Disallow: /pages/å*
Disallow: /pages/å«*
Disallow: /pages/å*
Disallow: /pages/è*
Disallow: /pages/å*
Disallow: /pages/å»*
Disallow: /pages/è´§*
Disallow: /pages/æ¬¾*
Disallow: /pages/å*
Disallow: /pages/å¥*
Disallow: /pages/è´*
Disallow: /pages/æ´*
Disallow: /pages/ä¹*
Disallow: /pages/é*
Disallow: /pages/é®*
Disallow: /pages/ç®±*
Disallow: /pages/å²*
Disallow: /pages/ä¸*
Disallow: /pages/ç¥*
Disallow: /pages/å¤*
Disallow: /pages/å*
Disallow: /pages/ä¼*
Disallow: /pages/é­*
Disallow: /pages/é¾*
Disallow: /pages/ç©*
Disallow: /pages/å¤*
Disallow: /pages/å¸*
Disallow: /pages/è³*
Disallow: /pages/ç¾*
Disallow: /pages/ç³*
Disallow: /pages/ç*
Disallow: /pages/å¼*
Disallow: /pages/å§¦*
Disallow: /pages/ä½¿*
Disallow: /pages/äº*
Disallow: /pages/ä¸*
Disallow: /pages/é*
Disallow: /pages/é*
Disallow: /pages/èº«*
Disallow: /pages/è*
Disallow: /pages/ç²¾*
Disallow: /pages/çµ*
Disallow: /pages/æ±*
Disallow: /pages/å¾®*
Disallow: /pages/å®*
Disallow: /pages/å½*
Disallow: /pages/å¯*
Disallow: /pages/éº»*
Disallow: /pages/é*
Disallow: /pages/é*
Disallow: /pages/ç*
Disallow: /pages/æ¸ *
Disallow: /pages/æ¬*
Disallow: /pages/æ¥*
Disallow: /pages/å¹³*
Disallow: /pages/å *
Disallow: /pages/å°*
Disallow: /pages/ä¿¡*
Disallow: /pages/éº¦*
Disallow: /pages/ç¹*
Disallow: /pages/æ¼«*
Disallow: /pages/æ¯*
Disallow: /pages/æ¶*
Disallow: /pages/æ¼*
Disallow: /pages/æ¶*
Disallow: /pages/æ*
Disallow: /pages/å¼¥*
Disallow: /pages/å»¶*
Disallow: /pages/å®´*
Disallow: /pages/å¥*
Disallow: /pages/å¤©*
Disallow: /pages/ä¸*
Disallow: /pages/éª*
Disallow: /pages/è§*
Disallow: /pages/ç­*
Disallow: /pages/å­*
Disallow: /pages/å©*
Disallow: /pages/äº¬*
Disallow: /pages/é©¬*
Disallow: /pages/é*
Disallow: /pages/è¯·*
Disallow: /pages/çº¢*
Disallow: /pages/ç©*
Disallow: /pages/ç½*
Disallow: /pages/æ´»*
Disallow: /pages/æ¯*
Disallow: /pages/å¿«*
Disallow: /pages/å*
Disallow: /pages/è¥¿*
Disallow: /pages/è*
Disallow: /pages/è*
Disallow: /pages/ç*
Disallow: /pages/æ³*
Disallow: /pages/å*

User-agent: pimeyes.com crawler
Disallow: /

User-agent: ChatGPT-User
Disallow: /

User-agent: GPTBot
Disallow: /

Sitemap: https://www.xing.com/sitemap.xml.gz
