# www.robotstxt.org/
# www.google.com/support/webmasters/bin/answer.py?hl=en&answer=156449

User-agent: *

Sitemap: https://www.zorgkaartnederland.nl/files/sitemap/rating_55.xml
Sitemap: https://www.zorgkaartnederland.nl/files/sitemap/rating_44.xml
Sitemap: https://www.zorgkaartnederland.nl/files/sitemap/rating_58.xml
Sitemap: https://www.zorgkaartnederland.nl/files/sitemap/rating_10.xml
Sitemap: https://www.zorgkaartnederland.nl/files/sitemap/rating_34.xml
Sitemap: https://www.zorgkaartnederland.nl/files/sitemap/rating_37.xml
Sitemap: https://www.zorgkaartnederland.nl/files/sitemap/rating_77.xml
Sitemap: https://www.zorgkaartnederland.nl/files/sitemap/rating_43.xml
Sitemap: https://www.zorgkaartnederland.nl/files/sitemap/page_1.xml
Sitemap: https://www.zorgkaartnederland.nl/files/sitemap/rating_25.xml
Sitemap: https://www.zorgkaartnederland.nl/files/sitemap/rating_74.xml
Sitemap: https://www.zorgkaartnederland.nl/files/sitemap/person_2.xml
Sitemap: https://www.zorgkaartnederland.nl/files/sitemap/rating_16.xml
Sitemap: https://www.zorgkaartnederland.nl/files/sitemap/rating_67.xml
Sitemap: https://www.zorgkaartnederland.nl/files/sitemap/rating_81.xml
Sitemap: https://www.zorgkaartnederland.nl/files/sitemap/rating_46.xml
Sitemap: https://www.zorgkaartnederland.nl/files/sitemap/rating_61.xml
Sitemap: https://www.zorgkaartnederland.nl/files/sitemap/rating_48.xml
Sitemap: https://www.zorgkaartnederland.nl/files/sitemap/rating_40.xml
Sitemap: https://www.zorgkaartnederland.nl/files/sitemap/rating_72.xml
Sitemap: https://www.zorgkaartnederland.nl/files/sitemap/rating_13.xml
Sitemap: https://www.zorgkaartnederland.nl/files/sitemap/rating_45.xml
Sitemap: https://www.zorgkaartnederland.nl/files/sitemap/rating_18.xml
Sitemap: https://www.zorgkaartnederland.nl/files/sitemap/rating_71.xml
Sitemap: https://www.zorgkaartnederland.nl/files/sitemap/rating_64.xml
Sitemap: https://www.zorgkaartnederland.nl/files/sitemap/company_2.xml
Sitemap: https://www.zorgkaartnederland.nl/files/sitemap/rating_49.xml
Sitemap: https://www.zorgkaartnederland.nl/files/sitemap/rating_50.xml
Sitemap: https://www.zorgkaartnederland.nl/files/sitemap/rating_76.xml
Sitemap: https://www.zorgkaartnederland.nl/files/sitemap/rating_42.xml
Sitemap: https://www.zorgkaartnederland.nl/files/sitemap/rating_38.xml
Sitemap: https://www.zorgkaartnederland.nl/files/sitemap/person_1.xml
Sitemap: https://www.zorgkaartnederland.nl/files/sitemap/rating_57.xml
Sitemap: https://www.zorgkaartnederland.nl/files/sitemap/rating_60.xml
Sitemap: https://www.zorgkaartnederland.nl/files/sitemap/rating_6.xml
Sitemap: https://www.zorgkaartnederland.nl/files/sitemap/person_0.xml
Sitemap: https://www.zorgkaartnederland.nl/files/sitemap/rating_63.xml
Sitemap: https://www.zorgkaartnederland.nl/files/sitemap/company_4.xml
Sitemap: https://www.zorgkaartnederland.nl/files/sitemap/rating_31.xml
Sitemap: https://www.zorgkaartnederland.nl/files/sitemap/rating_41.xml
Sitemap: https://www.zorgkaartnederland.nl/files/sitemap/rating_22.xml
Sitemap: https://www.zorgkaartnederland.nl/files/sitemap/rating_66.xml
Sitemap: https://www.zorgkaartnederland.nl/files/sitemap/rating_28.xml
Sitemap: https://www.zorgkaartnederland.nl/files/sitemap/rating_30.xml
Sitemap: https://www.zorgkaartnederland.nl/files/sitemap/rating_27.xml
Sitemap: https://www.zorgkaartnederland.nl/files/sitemap/rating_4.xml
Sitemap: https://www.zorgkaartnederland.nl/files/sitemap/rating_5.xml
Sitemap: https://www.zorgkaartnederland.nl/files/sitemap/rating_26.xml
Sitemap: https://www.zorgkaartnederland.nl/files/sitemap/rating_9.xml
Sitemap: https://www.zorgkaartnederland.nl/files/sitemap/rating_65.xml
Sitemap: https://www.zorgkaartnederland.nl/files/sitemap/rating_54.xml
Sitemap: https://www.zorgkaartnederland.nl/files/sitemap/rating_62.xml
Sitemap: https://www.zorgkaartnederland.nl/files/sitemap/rating_7.xml
Sitemap: https://www.zorgkaartnederland.nl/files/sitemap/rating_35.xml
Sitemap: https://www.zorgkaartnederland.nl/files/sitemap/rating_47.xml
Sitemap: https://www.zorgkaartnederland.nl/files/sitemap/rating_36.xml
Sitemap: https://www.zorgkaartnederland.nl/files/sitemap/rating_29.xml
Sitemap: https://www.zorgkaartnederland.nl/files/sitemap/rating_79.xml
Sitemap: https://www.zorgkaartnederland.nl/files/sitemap/rating_0.xml
Sitemap: https://www.zorgkaartnederland.nl/files/sitemap/rating_53.xml
Sitemap: https://www.zorgkaartnederland.nl/files/sitemap/rating_56.xml
Sitemap: https://www.zorgkaartnederland.nl/files/sitemap/rating_51.xml
Sitemap: https://www.zorgkaartnederland.nl/files/sitemap/rating_21.xml
Sitemap: https://www.zorgkaartnederland.nl/files/sitemap/rating_52.xml
Sitemap: https://www.zorgkaartnederland.nl/files/sitemap/company_1.xml
Sitemap: https://www.zorgkaartnederland.nl/files/sitemap/company_0.xml
Sitemap: https://www.zorgkaartnederland.nl/files/sitemap/rating_24.xml
Sitemap: https://www.zorgkaartnederland.nl/files/sitemap/rating_17.xml
Sitemap: https://www.zorgkaartnederland.nl/files/sitemap/rating_78.xml
Sitemap: https://www.zorgkaartnederland.nl/files/sitemap/rating_59.xml
Sitemap: https://www.zorgkaartnederland.nl/files/sitemap/person_4.xml
Sitemap: https://www.zorgkaartnederland.nl/files/sitemap/rating_15.xml
Sitemap: https://www.zorgkaartnederland.nl/files/sitemap/rating_8.xml
Sitemap: https://www.zorgkaartnederland.nl/files/sitemap/rating_11.xml
Sitemap: https://www.zorgkaartnederland.nl/files/sitemap/rating_20.xml
Sitemap: https://www.zorgkaartnederland.nl/files/sitemap/rating_69.xml
Sitemap: https://www.zorgkaartnederland.nl/files/sitemap/rating_70.xml
Sitemap: https://www.zorgkaartnederland.nl/files/sitemap/rating_23.xml
Sitemap: https://www.zorgkaartnederland.nl/files/sitemap/rating_12.xml
Sitemap: https://www.zorgkaartnederland.nl/files/sitemap/rating_39.xml
Sitemap: https://www.zorgkaartnederland.nl/files/sitemap/rating_14.xml
Sitemap: https://www.zorgkaartnederland.nl/files/sitemap/rating_73.xml
Sitemap: https://www.zorgkaartnederland.nl/files/sitemap/rating_68.xml
Sitemap: https://www.zorgkaartnederland.nl/files/sitemap/rating_19.xml
Sitemap: https://www.zorgkaartnederland.nl/files/sitemap/rating_32.xml
Sitemap: https://www.zorgkaartnederland.nl/files/sitemap/rating_2.xml
Sitemap: https://www.zorgkaartnederland.nl/files/sitemap/rating_75.xml
Sitemap: https://www.zorgkaartnederland.nl/files/sitemap/rating_33.xml
Sitemap: https://www.zorgkaartnederland.nl/files/sitemap/rating_3.xml
Sitemap: https://www.zorgkaartnederland.nl/files/sitemap/rating_1.xml

Disallow: /beheer/
Disallow: *?*sort=*
Disallow: *?*distance=*
Disallow: *?*zoekterm=*
Disallow: *?*search-send=*
Disallow: *?d=*
Disallow: *&d=*

User-agent: GPTBot
Disallow: /*waardering

User-agent: ChatGPT-User
Disallow: /*waardering

User-agent: CCBot
Disallow: /*waardering

User-agent: anthropic-ai
Disallow: /*waardering
