User-agent:*
Disallow:/mip/
Disallow:/ask/api/
Disallow:/api/
Disallow:/special/
Disallow:/tag/
Disallow:/search/
Disallow:/index.php?*
Disallow:/-121*
Disallow:/ask/api*
Disallow:/api/search/*
Disallow:/news/
Disallow:/zixun/
Disallow:/-223xmwe/
Disallow:/-/
Sitemap:https://www.kuaiji.com/sitemap-1.txt
Sitemap:https://www.kuaiji.com/sitemap-2.txt
Sitemap:https://www.kuaiji.com/sitemap-3.txt
Sitemap:https://www.kuaiji.com/sitemap-4.txt
Sitemap:https://www.kuaiji.com/sitemap-5.txt
Sitemap:https://www.kuaiji.com/sitemap-6.txt
Sitemap:https://www.kuaiji.com/sitemap-7.txt
Sitemap:https://www.kuaiji.com/sitemap-8.txt
Sitemap:https://www.kuaiji.com/sitemap-9.txt
Sitemap:https://www.kuaiji.com/sitemap-10.txt
Sitemap:https://www.kuaiji.com/sitemap-11.txt
Sitemap:https://www.kuaiji.com/sitemap-12.txt
Sitemap:https://www.kuaiji.com/sitemap-13.txt
Sitemap:https://www.kuaiji.com/sitemap-14.txt
Sitemap:https://www.kuaiji.com/sitemap-15.txt
Sitemap:https://www.kuaiji.com/sitemap-16.txt
Sitemap:https://www.kuaiji.com/sitemap-17.txt
Sitemap:https://www.kuaiji.com/sitemap-18.txt
Sitemap:https://www.kuaiji.com/sitemap-19.txt
Sitemap:https://www.kuaiji.com/sitemap-20.txt
Sitemap:https://www.kuaiji.com/sitemap-21.txt
Sitemap:https://www.kuaiji.com/sitemap-22.txt
Sitemap:https://www.kuaiji.com/sitemap-23.txt
Sitemap:https://www.kuaiji.com/sitemap-24.txt
