User-agent: *

# Directories
Disallow: /accountdocs/
Disallow: /app/
Disallow: /checkout/
Disallow: /customer/
Disallow: /downloader/
Disallow: /errors/
Disallow: /includes/
Disallow: /js/
Disallow: /jsXiti/
Disallow: /lib/
Disallow: /lmdv/
Disallow: /pkginfo/
Disallow: /scripts/
Disallow: /shell/
Disallow: /var/
Disallow: /catalog/
Disallow: /catalogsearch/result/
Disallow: /catalog/product_compare/
Disallow: /catalog/category/view/
Disallow: /catalog/product/view/
Disallow: /catalogsearch/
Disallow: /checkout/
Disallow: /control/
Disallow: /contacts/
Disallow: /customer/
Disallow: /customize/
Disallow: /newsletter/
Disallow: /sendfriend/
Disallow: /wishlist
Disallow: /xml/ 

# Files
Disallow: /cron.php
Disallow: /cron.sh
Disallow: /error_log
Disallow: /install.php
Disallow: /LICENSE.html
Disallow: /LICENSE.txt
Disallow: /LICENSE_AFL.txt
Disallow: /STATUS.txt
 

# Paths (clean URLs)
Disallow: /*?mois_de_depart=*
Disallow: /*?destination=*
Disallow: /proposition/
Disallow: /bi/
Disallow: /votre-voyage/
Disallow: /vos-envies/
Disallow: /votre-depart/
Disallow: /recherche_voyage
Disallow: /contactez-nous.html
Disallow: /credits.html
Disallow: /securite-confidentialite.html
Disallow: *?titleText=
Disallow: /Qui-Sommes-Nous.aspx
Disallow: /Recherche.aspx
Disallow: /securite-confidentialite.aspx
Disallow: /partenariats
Disallow: /*?price=*
Disallow: /*?mdv_general_*
Disallow: /*?type_de_circuit*
Disallow: /europe/russie/saint-petersbourg/circuit-accompagne/escapade-a-saint-petersbourg-p
Disallow: /europe/italie/sicile/autotour/de-la-sicile-orientale-a-la-sicile-occidentale-au-volant
Disallow: /amerique/etats-unis/new-york/sejour/black-friday-a-new-york-city
Disallow: /amerique/etats-unis/new-york/sejour/escapade-a-new-york-city
Disallow: /asie/chine/tibet/circuit-accompagne/mythes-et-merveilles-du-toit-du-monde
Disallow: /afrique/zanzibar/sejour/reve-de-zanzibar-sejour-a-l-ocean-paradise
Disallow: /amerique/guadeloupe/sejour/guadeloupe-sejour-fleur-d-epee
Disallow: /orient/jordanie/circuit-accompagne/jordanie-petra-la-sublime
Disallow: /amerique/guatemala/circuit-accompagne/guatemala-en-pays-maya
Disallow: /asie/vietnam/circuit-accompagne/decouverte-du-vietnam-p
Disallow: /amerique/costa-rica/circuit-accompagne/costa-rica-le-pays-ou-la-vie-est-plus-verte
Disallow: /amerique/guadeloupe/sejour/guadeloupe-sejour-fleur-d-epee-depart-de-bordeaux
Disallow: /amerique/guadeloupe/sejour/guadeloupe-sejour-fleur-d-epee-depart-de-lyon
Disallow: /amerique/guadeloupe/sejour/guadeloupe-sejour-fleur-d-epee-depart-de-marseille
Disallow: /amerique/guadeloupe/sejour/guadeloupe-sejour-fleur-d-epee-depart-de-toulouse
Disallow: /amerique/martinique/sejour/martinique-sejour-le-carayou-9118
Disallow: /orient/emirats-arabes-unis/circuit-accompagne/week-end-prolonge-a-dubai-pour-l-exposition-universelle
Disallow: /amerique/etats-unis/new-york/new-york-city-au-black-friday
Disallow: /amerique/etats-unis/new-york/sejour/black-friday-a-new-york-city
Disallow: /amerique/martinique/sejour/martinique-sejour-le-carayou
Disallow: /afrique/afrique-du-sud/circuit-accompagne/safari-en-afrique-du-sud
Disallow: /amerique/costa-rica/circuit-accompagne/costa-rica-le-pays-ou-la-vie-est-plus-verte1
Disallow: /asie/birmanie/circuit-accompagne/traversee-de-la-birmanie-de-mandalay-a-yangon
Disallow: /oceanie/australie/circuit-accompagne/splendeurs-australiennes
Disallow: /*?accomodation_type=*
Disallow: /*?accomodation_style=*
Disallow: /*?comfort_level*
Disallow: /*mdv_general_*
Disallow: /*?ord=*
Disallow: /*ord=*.
Disallow: /*?categorie=*

# Paths (no clean URLs)
Disallow: /*?mois_de_depart=*
Disallow: /*?destination=*
Disallow: /proposition
Disallow: /bi/
Disallow: /vos-envies/ 
Disallow: /votre-depart/   
Disallow: /conditions-vente.html   
Disallow: /securite-confidentialite.html
Disallow: /architecture-du-voyage.html
Disallow: /devis-sur-mesure.html
Disallow: /notre-valeur-ajoutee.html
Disallow: /securite-confidentialite.html
Disallow: /conditions-vente.html
Disallow: /credits.html
Disallow: /devis-groupe.html
Disallow: /contactez-nous-formulaire.html
Disallow: /qui-sommes-nous.html
Disallow: /partenariats
Disallow: /*.php$
Disallow: /*?p=*&
Disallow: /*?SID=
Disallow: /*?limit=all
Disallow: /*?mdv_journey_mode=*
Disallow: /*?vous_voyagez=*
Disallow: /*___store=*
Disallow: /*?c=*
Disallow: /*?dir=*
Disallow: /*?dest=*

 
User-agent: Exabot
User-agent: MojeekBot
User-agent: semalt
User-agent: dotbot
User-agent: Rogerbot
User-agent: Spiderbot/Nutch-1.7
User-agent: MJ12bot
Disallow: /