User-agent: *

Disallow: /*?returnUrl
Disallow: /_info.json*
Disallow: /administrator/
Disallow: /api/
Disallow: /attendees
Disallow: /blackfish/
Disallow: /blackfish/page_previews/*
Disallow: /blog/tags/
Disallow: /clicktale/
Disallow: /designers/colorfilter?*
Disallow: /designers/subtlepatterns/patterns/*.zip
Disallow: /disqus_comments.json*
Disallow: /hire
Disallow: /hire/*
Disallow: /platform/
Disallow: /posts
Disallow: /secure_redirect/default
Disallow: /signed_in
Disallow: /track/
Disallow: /users/login
Disallow: /search?term
Disallow: /search?page=&term=*
Disallow: /search?filter
Disallow: /search?limit

Sitemap: https://www.toptal.com/sitemap.xml
Sitemap: https://www.toptal.com/sitemap/locations.xml
Sitemap: https://www.toptal.com/sitemap/community.xml
Sitemap: https://www.toptal.com/designers/subtlepatterns/sitemap.xml
Sitemap: https://www.toptal.com/sitemap/htmlarrows.xml
Sitemap: https://www.toptal.com/developers/css/sprite-generator/sitemap.xml
Sitemap: https://www.toptal.com/developers/json-formatter/sitemap.xml
Sitemap: https://www.toptal.com/designers/colorfilter/sitemap.xml
Sitemap: https://www.toptal.com/developers/javascript-minifier/sitemap.xml
Sitemap: https://www.toptal.com/developers/css3maker/sitemap.xml
Sitemap: https://www.toptal.com/developers/html-minifier/sitemap.xml
Sitemap: https://www.toptal.com/developers/cssminifier/sitemap.xml
