User-agent: CCBot
Disallow: /

User-agent: ChatGPT-User
Disallow: /

User-agent: GPTBot
Disallow: /

User-agent: Google-Extended
Disallow: /

User-agent: *
Disallow: /tncms/tracking/
Disallow: /_services/
Disallow: /nowapp/delete_account/
Disallow: /tncms/openid2/
Disallow: /tncms/track/
Disallow: /tncms/admin/
Disallow: /tncms/block/
Disallow: /tncms/weather/
Disallow: /tncms/auth/
Disallow: /tncms/openweb/*
Disallow: /tncms/gtm/
Disallow: /tncms/dmp/
Disallow: /tncms/media/
Disallow: /tncms/search/
Disallow: /tncms/counter/
Disallow: /tncms/tax/
Disallow: /tncms/messaging/
Disallow: /tncms/webservice/
Disallow: /tncms/user/
Disallow: /users/admin/
Disallow: /users/*/?
Disallow: /tncms/calendar/
Disallow: /calendar/search/
Disallow: /calendar/closings/search/
Disallow: /cattleseller/calendar/search/
Disallow: /midwestmessenger/calendar/search/
Disallow: /midwestmessenger/calendar/auction/search/
Disallow: /content/tncms/assets/v3/form/
Disallow: /content/tncms/form/
Disallow: /places/*action=srch
Disallow: /tncms/disqus/
Disallow: /newsletter-templates
Disallow: /newsletter-templates/daily-headlines
Disallow: /newsletter-templates/local
Disallow: /newsletter-templates/local/av
Disallow: /newsletter-templates/local/av/auction
Disallow: /newsletter-templates/local/av/from-the-fields
Disallow: /newsletter-templates/local/av/marketing
Disallow: /newsletter-templates/local/av/marketing/ad-email
Disallow: /newsletter-templates/local/av/marketing/ad-email2
Disallow: /newsletter-templates/local/av/marketing/ad-html
Disallow: /newsletter-templates/local/av/producers
Disallow: /newsletter-templates/local/av/weekly
Disallow: /newsletter-templates/local/cropwatch
Disallow: /newsletter-templates/local/daily-headlines
Disallow: /newsletter-templates/local/frg
Disallow: /newsletter-templates/local/frg/auction
Disallow: /newsletter-templates/local/frg/marketing
Disallow: /newsletter-templates/local/frg/marketing/ad-email
Disallow: /newsletter-templates/local/frg/marketing/ad-email2
Disallow: /newsletter-templates/local/frg/marketing/ad-html
Disallow: /newsletter-templates/local/frg/weekly
Disallow: /newsletter-templates/local/iaft
Disallow: /newsletter-templates/local/iaft/auction
Disallow: /newsletter-templates/local/iaft/marketing
Disallow: /newsletter-templates/local/iaft/marketing/ad-email
Disallow: /newsletter-templates/local/iaft/marketing/ad-email2
Disallow: /newsletter-templates/local/iaft/marketing/ad-html
Disallow: /newsletter-templates/local/iaft/marketwatch
Disallow: /newsletter-templates/local/iaft/marketwatch/am
Disallow: /newsletter-templates/local/iaft/marketwatch/pm
Disallow: /newsletter-templates/local/iaft/weekly
Disallow: /newsletter-templates/local/ilft
Disallow: /newsletter-templates/local/ilft/marketing
Disallow: /newsletter-templates/local/ilft/marketing/ad-email
Disallow: /newsletter-templates/local/ilft/marketing/ad-email2
Disallow: /newsletter-templates/local/ilft/marketing/ad-html
Disallow: /newsletter-templates/local/ilft/weekly
Disallow: /newsletter-templates/local/livestock-roundup
Disallow: /newsletter-templates/local/livestock-roundup/marketing
Disallow: /newsletter-templates/local/livestock-roundup/marketing/ad-email
Disallow: /newsletter-templates/local/livestock-roundup/marketing/ad-email2
Disallow: /newsletter-templates/local/livestock-roundup/marketing/ad-html
Disallow: /newsletter-templates/local/livestock-roundup/marketing/ad-html2
Disallow: /newsletter-templates/local/mfg
Disallow: /newsletter-templates/local/mfg/auction
Disallow: /newsletter-templates/local/mfg/marketing
Disallow: /newsletter-templates/local/mfg/marketing/ad-email
Disallow: /newsletter-templates/local/mfg/marketing/ad-email2
Disallow: /newsletter-templates/local/mfg/marketing/ad-html
Disallow: /newsletter-templates/local/mfg/weekly
Disallow: /newsletter-templates/local/mft
Disallow: /newsletter-templates/local/mft/marketing
Disallow: /newsletter-templates/local/mft/marketing/ad-email
Disallow: /newsletter-templates/local/mft/marketing/ad-email2
Disallow: /newsletter-templates/local/mft/marketing/ad-html
Disallow: /newsletter-templates/local/mft/weekly
Disallow: /newsletter-templates/local/mm
Disallow: /newsletter-templates/local/mm/marketing
Disallow: /newsletter-templates/local/mm/marketing/ad-email
Disallow: /newsletter-templates/local/mm/marketing/ad-email2
Disallow: /newsletter-templates/local/mm/marketing/ad-html
Disallow: /newsletter-templates/local/mwm
Disallow: /newsletter-templates/local/mwm/auction
Disallow: /newsletter-templates/local/mwm/marketing
Disallow: /newsletter-templates/local/mwm/marketing/ad-email
Disallow: /newsletter-templates/local/mwm/marketing/ad-email2
Disallow: /newsletter-templates/local/mwm/marketing/ad-html
Disallow: /newsletter-templates/local/mwm/weekly
Disallow: /newsletter-templates/local/mwmk
Disallow: /newsletter-templates/local/mwmk/marketing
Disallow: /newsletter-templates/local/mwmk/marketing/ad-email
Disallow: /newsletter-templates/local/mwmk/marketing/ad-email2
Disallow: /newsletter-templates/local/mwmk/marketing/ad-html
Disallow: /newsletter-templates/local/mwmk/weekly
Disallow: /newsletter-templates/local/tps
Disallow: /newsletter-templates/local/tps/auction
Disallow: /newsletter-templates/local/tps/marketing
Disallow: /newsletter-templates/local/tps/marketing/ad-email
Disallow: /newsletter-templates/local/tps/marketing/ad-email2
Disallow: /newsletter-templates/local/tps/marketing/ad-html
Disallow: /newsletter-templates/local/tps/weekly
Disallow: /newsletter-templates/local/tsn
Disallow: /newsletter-templates/local/tsn/auction
Disallow: /newsletter-templates/local/tsn/marketing
Disallow: /newsletter-templates/local/tsn/marketing/ad-email
Disallow: /newsletter-templates/local/tsn/marketing/ad-email2
Disallow: /newsletter-templates/local/tsn/marketing/ad-html
Disallow: /newsletter-templates/local/tsn/weekly
Disallow: /newsletter-templates/marketing
Disallow: /newsletter-templates/marketing/ad-email
Disallow: /newsletter-templates/marketing/ad-html
Disallow: /newsletter-templates/marketing/ad-html-ift
Disallow: /newsletter-templates/marketing/ad-html2
Disallow: /newsletter-templates/marketing/ad-html3
Disallow: /newsletter-templates/marketing/html
Disallow: /newsletter-templates/marketing/promo
Disallow: /newsletter-templates/marketing/signup
Disallow: /newsletter-templates/marketing/special
Disallow: /newsletter-templates/topic
Disallow: /newsletter-templates/topic/popup
Disallow: /newsletter-templates/topic/popup2
Disallow: /newsletter-templates/marketing/b2b
Disallow: /newsletter-templates/afternoon-headlines
Disallow: /newsletter-templates/marketing/get-healthy
Disallow: /ads/*?
Disallow: /ads/endofyeardeals/*?
Disallow: /ag_pubs/illinois_farmer_today/classifieds/*?
Disallow: /ag_pubs/minnesota_farm_guide/classifieds/*?
Disallow: /ag_pubs/missouri_farmer_today/classifieds/*?
Disallow: /ag_pubs/the_prairie_star/classifieds/*?
Disallow: /ag_pubs/todays_producer/classifieds/*?
Disallow: /ag_pubs/tri_state_neighbor/classifieds/*?
Disallow: /agrisearch/*?
Disallow: /agriview/ads/*?
Disallow: /community/burt_county/ads/*?
Disallow: /farmandranchguide/ads/*?
Disallow: /farmandranchnetwork/ads/*?
Disallow: /illinoisfarmertoday/ads/*?
Disallow: /iowafarmertoday/ads/*?
Disallow: /livestockroundup/ads/*?
Disallow: /midwestmarketer/ads/*?
Disallow: /midwestmessenger/ads/*?
Disallow: /minnesotafarmguide/ads/*?
Disallow: /missourifarmertoday/ads/*?
Disallow: /theprairiestar/ads/*?
Disallow: /todaysproducer/ads/*?
Disallow: /tristateneighbor/ads/*?

Sitemap: https://agupdate.com/sitemap.xml
Sitemap: https://agupdate.com/tncms/sitemap/editorial.xml
Sitemap: https://agupdate.com/tncms/sitemap/editorial.xml?year=1977
Sitemap: https://agupdate.com/tncms/sitemap/editorial.xml?year=2000
Sitemap: https://agupdate.com/tncms/sitemap/editorial.xml?year=2001
Sitemap: https://agupdate.com/tncms/sitemap/editorial.xml?year=2002
Sitemap: https://agupdate.com/tncms/sitemap/editorial.xml?year=2003
Sitemap: https://agupdate.com/tncms/sitemap/editorial.xml?year=2004
Sitemap: https://agupdate.com/tncms/sitemap/editorial.xml?year=2005
Sitemap: https://agupdate.com/tncms/sitemap/editorial.xml?year=2006
Sitemap: https://agupdate.com/tncms/sitemap/editorial.xml?year=2007
Sitemap: https://agupdate.com/tncms/sitemap/editorial.xml?year=2008
Sitemap: https://agupdate.com/tncms/sitemap/editorial.xml?year=2009
Sitemap: https://agupdate.com/tncms/sitemap/editorial.xml?year=2010
Sitemap: https://agupdate.com/tncms/sitemap/editorial.xml?year=2011
Sitemap: https://agupdate.com/tncms/sitemap/editorial.xml?year=2012
Sitemap: https://agupdate.com/tncms/sitemap/editorial.xml?year=2013
Sitemap: https://agupdate.com/tncms/sitemap/editorial.xml?year=2014
Sitemap: https://agupdate.com/tncms/sitemap/editorial.xml?year=2015
Sitemap: https://agupdate.com/tncms/sitemap/editorial.xml?year=2016
Sitemap: https://agupdate.com/tncms/sitemap/editorial.xml?year=2017
Sitemap: https://agupdate.com/tncms/sitemap/editorial.xml?year=2018
Sitemap: https://agupdate.com/tncms/sitemap/editorial.xml?year=2019
Sitemap: https://agupdate.com/tncms/sitemap/editorial.xml?year=2020
Sitemap: https://agupdate.com/tncms/sitemap/editorial.xml?year=2021
Sitemap: https://agupdate.com/tncms/sitemap/editorial.xml?year=2022
Sitemap: https://agupdate.com/tncms/sitemap/editorial.xml?year=2023
