User-agent: *
Disallow: /wp-admin/
Allow: /wp-admin/admin-ajax.php
Disallow: /wp-login.php
Disallow: *.jpeg$
Disallow: *.jpg$
Disallow: *.gif$
Disallow: *.png$
Disallow: *.mp4$
Disallow: *.webm$
Disallow: *.woff$
Disallow: *.woff2$
Disallow: *.ttf$
Disallow: *.eot$
Disallow: *.webp$
