#
# robots.txt
#
# This file is to prevent the crawling and indexing of certain parts
# of your site by web crawlers and spiders run by sites like Yahoo!
# and Google. By telling these "robots" where not to go on your site,
# you save bandwidth and server resources.
#
# This file will be ignored unless it is at the root of your host:
# Used:    http://example.com/robots.txt
# Ignored: http://example.com/site/robots.txt
#
# For more information about the robots.txt standard, see:
# http://www.robotstxt.org/robotstxt.html

User-agent: *
Crawl-delay: 10
# CSS, JS, Images
Allow: /core/*.css$
Allow: /core/*.css?
Allow: /core/*.js$
Allow: /core/*.js?
Allow: /core/*.gif
Allow: /core/*.jpg
Allow: /core/*.jpeg
Allow: /core/*.png
Allow: /core/*.svg
Allow: /profiles/*.css$
Allow: /profiles/*.css?
Allow: /profiles/*.js$
Allow: /profiles/*.js?
Allow: /profiles/*.gif
Allow: /profiles/*.jpg
Allow: /profiles/*.jpeg
Allow: /profiles/*.png
Allow: /profiles/*.svg
Allow: /misc/*.css$
Allow: /misc/*.css?
Allow: /misc/*.js$
Allow: /misc/*.js?
Allow: /misc/*.gif
Allow: /misc/*.jpg
Allow: /misc/*.jpeg
Allow: /misc/*.png
Allow: /modules/*.css$
Allow: /modules/*.css?
Allow: /modules/*.js$
Allow: /modules/*.js?
Allow: /modules/*.gif
Allow: /modules/*.jpg
Allow: /modules/*.jpeg
Allow: /modules/*.png
Allow: /profiles/*.css$
Allow: /profiles/*.css?
Allow: /profiles/*.js$
Allow: /profiles/*.js?
Allow: /profiles/*.gif
Allow: /profiles/*.jpg
Allow: /profiles/*.jpeg
Allow: /profiles/*.png
Allow: /themes/*.css$
Allow: /themes/*.css?
Allow: /themes/*.js$
Allow: /themes/*.js?
Allow: /themes/*.gif
Allow: /themes/*.jpg
Allow: /themes/*.jpeg
Allow: /themes/*.png
# Directories
Disallow: /core/
Disallow: /profiles/
# Files
Disallow: /README.txt
Disallow: /web.config
Disallow: /CHANGELOG.txt
Disallow: /cron.php
Disallow: /INSTALL.mysql.txt
Disallow: /INSTALL.pgsql.txt
Disallow: /INSTALL.sqlite.txt
Disallow: /install.php
Disallow: /INSTALL.txt
Disallow: /LICENSE.txt
Disallow: /MAINTAINERS.txt
Disallow: /update.php
Disallow: /UPGRADE.txt
Disallow: /xmlrpc.php
Disallow: /sites/default/files/*gtd-*.pdf
Disallow: /sites/default/files/*lgy-*.pdf
Disallow: /thank-you-*
Disallow: /sites/default/files/pfpt-us-tr-state-of-the-phish-2019.pdf
Disallow: /sites/default/files/mail-routing-agent-datasheet-v2.pdf
# Paths (clean URLs)
Disallow: /admin/
Disallow: /comment/reply/
Disallow: /filter/tips
Disallow: /node/add/
Disallow: /search/
Disallow: /user/register/
Disallow: /user/password/
Disallow: /user/login/
Disallow: /user/logout/
Disallow: /admin/
Disallow: /comment/reply/
Disallow: /node/add/
Disallow: /search/
Disallow: /user/register*
Disallow: /user/password*
Disallow: /user/login*
Disallow: /user/logout*
Disallow: /events/*
Disallow: /upcoming-events/*
Disallow: /lp/*
Disallow: /conquer
Disallow: /merck
Disallow: /johnson-controls
Disallow: /baxter
Disallow: /sutter-health
Disallow: /chevron
Disallow: /meeting-request
# Paths (no clean URLs)
Disallow: /index.php/admin/
Disallow: /index.php/comment/reply/
Disallow: /index.php/filter/tips
Disallow: /index.php/node/add/
Disallow: /index.php/search/
Disallow: /index.php/user/password/
Disallow: /index.php/user/register/
Disallow: /index.php/user/login/
Disallow: /index.php/user/logout/
Disallow: /?q=admin/
Disallow: /?q=comment/reply/
Disallow: /?q=filter/tips/
Disallow: /?q=node/add/
Disallow: /?q=search/
Disallow: /?q=user/password/
Disallow: /?q=user/register/
Disallow: /?q=user/login/
Disallow: /?q=user/logout/
Disallow: /?q=events/*
Disallow: /?q=upcoming-events/*
Disallow: /sites/default/files/e-books/pfpt-jp-eb-getting-started-with-DMARC-ebook.pdf
Disallow: /sites/default/files/e-books/pfpt-uk-eb-setting-up-itm.pdf
Disallow: /sites/default/files/e-books/pfpt-uk-eb-itm-overview.pdf
Disallow: /sites/default/files/e-books/pfpt-us-eb-role-of-itm.pdf
Disallow: /sites/default/files/e-books/pfpt-jp-eb-itm-cybersecurity.pdf
Disallow: /sites/default/files/e-books/pfpt-de-eb-itm-overview.pdf
Disallow: /sites/default/files/e-books/pfpt-jp-eb-setting-up-itm.pdf
Disallow: /sites/default/files/e-books/pfpt-jp-eb-itm-overview.pdf
Disallow: /sites/default/files/e-books/pfpt-jp-eb-role-of-itm.pdf
Disallow: /sites/default/files/e-books/pfpt-uk-eb-demystifying-bec-eac.pdf
Disallow: /sites/default/files/e-books/pfpt-uk-eb-deploying-people-centric-security-3.pdf
Disallow: /sites/default/files/e-books/pfpt-fr-dr-demystifying-bec-eac.pdf
Disallow: /sites/default/files/e-books/pfpt-fr-da-deploying-people-centric-security-3.pdf
Disallow: /sites/default/files/solution-briefs/pfpt-de-sb-CASB-adaptive-access-controls.pdf
Disallow: /sites/default/files/e-books/pfpt-de-da-deploying-people-centric-security-3.pdf
Disallow: /sites/default/files/solution-briefs/RemoteWorkAlliance_Webinar.pdf
Disallow: /sites/default/files/white-papers/pfpt-us-eb-the-hidden-cost-of-mso365-security.pdf
Disallow: /sites/default/files/e-books/pfpt-de-eb-dr-whack-a-mail.pdf
Disallow: /sites/default/files/e-books/pfpt-de-eb-no-compromises.pdf
Disallow: /sites/default/files/e-books/pfpt-uk-eb-putting-people-at-center-of-your-email-security-strategy.pdf
Disallow: /sites/default/files/e-books/pfpt-uk-eb-calculated-risks.pdf
Disallow: /sites/default/files/solution-briefs/pfpt-ja-sb-CASB-adaptive-access-controls.pdf
Disallow: /sites/default/files/e-books/pfpt-de-eb-demystifying-bec-eac.pdf
Disallow: /sites/default/files/e-books/pfpt-uk-eb-no-compromises.pdf
Disallow: /sites/default/files/e-books/pfpt-jp-da-deploying-people-centric-security-3.pdf
Disallow: /sites/default/files/e-books/pfpt-uk-eb-whack-a-mail.pdf
Disallow: /sites/default/files/e-books/pfpt-uk-eb-unmasking-bec-and-eac.pdf
Disallow: /sites/default/files/e-books/pfpt-de-eb-role-of-itm.pdf
Disallow: /sites/default/files/e-books/pfpt-es-eb-calculated-risks.pdf
Disallow: /sites/default/files/e-books/pfpt-de-eb-top-10-reasons-customers-choose-pfpt-to-secure-ms365.pdf
Disallow: /sites/default/files/e-books/gtd-pfpt-de-eb-top-10-reasons-customers-choose-pfpt-to-secure-ms365.pdf
Disallow: /sites/default/files/e-books/gtd-pfpt-de-eb-putting-people-at-center-of-your-email-security-strategy.pdf
Disallow: /sites/default/files/solution-briefs/pfpt-jp-eb-unmasking-bec-and-eac.pdf
Disallow: /sites/default/files/e-books/pfpt-fr-eb-calculated-risks.pdf
Disallow: /sites/default/files/e-books/pfpt-es-eb-top-10-reasons-customers-choose-pfpt-to-secure-ms365.pdf
Disallow: /sites/default/files/e-books/pfpt-fr-eb-top-10-reasons-customers-choose-pfpt-to-secure-ms365.pdf
Disallow: /sites/default/files/e-books/pfpt-it-eb-top-10-reasons-customers-choose-pfpt-to-secure-ms365.pdf
Disallow: /sites/default/files/misc/pfpt-us-eb-the-evolution-of-the-casb.pdf
Disallow: /sites/default/files/e-books/pfpt-us-eb-the-evolution-of-the-casb.pdf
Disallow: /sites/default/files/infographics/Pfpt-Phishing%20Infographic%20Poster-17x24-jp.pdf
Disallow: /sites/default/files/e-books/pfpt-jp-eb-calculated-risks.pdf
Disallow: /sites/default/files/e-books/pfpt-es-da-deploying-people-centric-security-3.pdf
Disallow: /sites/default/files/e-books/gtd-pfpt-de-eb-calculated-risks.pdf
Disallow: /sites/default/files/e-books/gtd-pfpt-it-eb-calculated-risks.pdf
Disallow: /sites/default/files/white-papers/gtyd-pfpt-fr-wp-driving-real-behavior-change.pdf
Disallow: /sites/default/files/e-books/gtd-pfpt-es-eb-demystifying-bec-eac.pdf
Disallow: /sites/default/files/solution-briefs/gtd-pfpt-es-sb-CASB-adaptive-access-controls.pdf
Disallow: /sites/default/files/securityawarenesskit/Cybersecurity-Awareness-Kit-BEC.zip
Disallow: /sites/default/files/e-books/pfpt-us-eb-rethinking-insider-risk.pdf
Disallow: /sites/default/files/data-sheets/pfpt-jp-eval_2020-evaluation-jp.pdf
Disallow: /sites/default/files/e-books/pfpt-us-tr-healthcare-report.pdf
Disallow: /sites/default/files/white-papers/pfpt-de-eb-the-hidden-cost-of-mso365-security.pdf
Disallow: /sites/default/files/white-papers/pfpt-uk-eb-the-hidden-cost-of-mso365-security.pdf
Disallow: /sites/default/files/white-papers/pfpt-au-eb-the-hidden-cost-of-mso365-security.pdf
Disallow: /sites/default/files/white-papers/pfpt-fr-eb-the-hidden-cost-of-mso365-security.pdf
Disallow: /sites/default/files/white-papers/pfpt-es-eb-the-hidden-cost-of-mso365-security.pdf
Disallow: /sites/default/files/white-papers/pfpt-it-eb-the-hidden-cost-of-mso365-security.pdf
Disallow: /sites/default/files/white-papers/pfpt-jp-eb-the-hidden-cost-of-mso365-security.pdf
Disallow: /sites/default/files/misc/gtd-pfpt-jp-a4-eb-top-10-reasons-customers-choose-pfpt-to-secure-ms365.pdf
Disallow: /sites/default/files/analyst-reports/pfpt-us-ar-esg-economic-validation-sep-2020.pdf
Disallow: /sites/default/files/e-books/gtd-pfpt-it-eb-stopping-bec-and-eac.pdf
Disallow: /sites/default/files/e-books/gtd-pfpt-jp-eb-stopping-bec-and-eac.pdf
Disallow: /sites/default/files/e-books/gtd-pfpt-fr-eb-stopping-bec-and-eac.pdf
Disallow: /sites/default/files/e-books/gtd-pfpt-es-eb-stopping-bec-and-eac.pdf
Disallow: /sites/default/files/e-books/gtd-pfpt-it-eb-putting-people-at-center-of-your-email-security-strategy.pdf
Disallow: /sites/default/files/e-books/gtd-pfpt-jp-eb-putting-people-at-center-of-your-email-security-strategy.pdf
Disallow: /sites/default/files/e-books/gtd-pfpt-fr-eb-putting-people-at-center-of-your-email-security-strategy.pdf
Disallow: /sites/default/files/e-books/gtd-pfpt-es-eb-putting-people-at-center-of-your-email-security-strategy.pdf
Disallow: /sites/default/files/analyst-reports/pfpt-es-ar-esg-economic-validation-sep-2020.pdf
Disallow: /sites/default/files/analyst-reports/pfpt-fr-ar-esg-economic-validation-sep-2020.pdf
Disallow: /sites/default/files/analyst-reports/pfpt-it-ar-esg-economic-validation-sep-2020.pdf
Disallow: /sites/default/files/e-books/gtd-pfpt-fr-eb-role-of-itm.pdf
Disallow: /sites/default/files/e-books/gtd-pfpt-fr-eb-itm-overview.pdf
Disallow: /sites/default/files/e-books/gtd-pfpt-de-eb-itm-cybersecurity.pdf
Disallow: /sites/default/files/e-books/gtd-pfpt-fr-eb-itm-cybersecurity.pdf
Disallow: /sites/default/files/e-books/gtd-pfpt-de-eb-setting-up-itm.pdf
Disallow: /sites/default/files/e-books/gtd-pfpt-fr-eb-setting-up-itm.pdf
Disallow: /sites/default/files/analyst-reports/pfpt-uk-ar-esg-economic-validation-sep-2020.pdf
Disallow: /sites/default/files/solution-briefs/pfpt-jp-a4-sb-solutions-bundles_201111a.pdf
Disallow: /sites/default/files/analyst-reports/pfpt-jp-ar-esg-economic-validation-sep-2020.pdf
Disallow: /sites/default/files/white-papers/pfpt-us-wp-cyber-risk-alliance-research-report.pdf
Disallow: /sites/default/files/e-books/gtd-pfpt-uk-eb-top-10-reasons-customers-choose-pfpt-to-secure-ms365.pdf
Disallow: /sites/default/files/e-books/gtd-pfpt-au-eb-top-10-reasons-customers-choose-pfpt-to-secure-ms365.pdf
Disallow: /sites/default/files/e-books/gtd-pfpt-it-eb-role-of-itm.pdf
Disallow: /sites/default/files/e-books/gtd-pfpt-it-eb-itm-cybersecurity.pdf
Disallow: /sites/default/files/analyst-reports/pfpt-de-ar-esg-economic-validation-sep-2020.pdf
Disallow: /sites/default/files/e-books/gtd-pfpt-it-eb-setting-up-itm.pdf
Disallow: /sites/default/files/white-papers/pfpt-us-wp-radicati-secure-email-gateway-market-quadrant-2020.pdf
Disallow: /sites/default/files/white-papers/gtd-pfpt-it-wp-driving-real-behavior-change.pdf
Disallow: /sites/default/files/white-papers/gtd-pfpt-es-wp-driving-real-behavior-change.pdf
Disallow: /sites/default/files/e-books/pfpt-de-eb-itm-overview-v7.pdf
Disallow: /sites/default/files/e-books/pfpt-uk-eb-itm-overview-v7.pdf
Disallow: /sites/default/files/e-books/pfpt-au-eb-itm-overview-v7.pdf
Disallow: /sites/default/files/e-books/gtd-pfpt-fr-eb-itm-overview-v5.pdf
Disallow: /sites/default/files/e-books/gtd-pfpt-it-eb-itm-overview.pdf
Disallow: /sites/default/files/e-books/pfpt-jp-eb-itm-overview-v7.pdf
Disallow: /sites/default/files/e-books/pfpt-uk-eb-rethinking-insider-risk.pdf
Disallow: /sites/default/files/e-books/pfpt-au-eb-rethinking-insider-risk.pdf
Disallow: /sites/default/files/solution-briefs/gtd-pfpt-fr-sb-CASB-adaptive-access-controls.pdf
Disallow: /sites/default/files/e-books/gtd-pfpt-it-eb-demystifying-bec-eac.pdf
Disallow: /sites/default/files/misc/gtd-pfpt-uk-eb-role-of-itm.pdf.pdf
Disallow: /sites/default/files/e-books/pfpt-us-eb-2021-ransomware-survival-guide.pdf
Disallow: /sites/default/files/e-books/pfpt-uk-eb-2021-ransomware-survival-guide.pdf
Disallow: /sites/default/files/e-books/pfpt-a4-da-ransomware-survival-guide-executive-summary.pdf
Disallow: /sites/default/files/e-books/pfpt-es-eb-rethinking-insider-risk.pdf
Disallow: /sites/default/files/e-books/PROO3754_fr_RethinkingIT_GIG_eBook.pdf
Disallow: /sites/default/files/e-books/pfpt-fr-eb-rethinking-insider-risk.pdf
Disallow: /sites/default/files/e-books/PROO3773_FinServ_eBook.pdf
Disallow: /sites/default/files/e-books/pfpt-us-eb-FinServ_eBook.pdf
Disallow: /sites/default/files/threat-reports/pfpt-us-tr-healthcare.pdf
Disallow: /sites/default/files/e-books/pfpt-it-eb-rethinking-insider-risk.pdf
Disallow: /sites/default/files/threat-reports/pfpt-es-tr-healthcare-report.pdf
Disallow: /sites/default/files/threat-reports/pfpt-uk-tr-healthcare-report.pdf
Disallow: /sites/default/files/threat-reports/pfpt-fr-tr-healthcare-report.pdf
Disallow: /sites/default/files/e-books/pfpt-jp-eb-driving-real-behavior-change.pdf
Disallow: /sites/default/files/white-papers/pfpt-us-wp-driving-real-behavior-change.pdf
Disallow: /sites/default/files/misc/pfpt-2020-type2-soc2-report-clickwrap.pdf
Disallow: /sites/default/files/e-books/pfpt-jp-eb-rethinking-insider-risk.pdf
Disallow: /sites/default/files/e-books/pfpt-de-eb-rethinking-insider-risk.pdf
Disallow: /sites/default/files/threat-reports/pfpt-jp-tr-healthcare-report.pdf
Disallow: /sites/default/files/threat-reports/pfpt-it-tr-healthcare-report.pdf
Disallow: /sites/default/files/2020-05/pfpt-us-wp-how-proofpoint-helps-organizations-meet-NIST-cybersecurity-guidelines.pdf
Disallow: /sites/default/files/e-books/pfpt-us-eb-biggest-and-boldest-insider-threats-2019-2020.pdf
Disallow: /sites/default/files/e-books/pfpt-us-eb-compliance-in-the-age-of-digital-collaboration.pdf
Disallow: /sites/default/files/e-books/pfpt-us-eb-compliance-in-the-age-of-digital-collaborations.pdf
Disallow: /sites/default/files/2020-06/pfpt-us-eb-the-definitive-email-security-guide.pdf
Disallow: /sites/default/files/ciso_ebook_sponsored_by_proofpoint.pdf
Disallow: /sites/default/files/threat-reports/pfpt-us-tr-state-of-the-phish-2021.pdf
Disallow: /sites/default/files/threat-reports/pfpt-de-tr-healthcare-report.pdf
Disallow: /sites/default/files/threat-reports/pfpt-us-tr-financial-services-and-insurance.pdf
Disallow: /sites/default/files/e-books/pfpt-us-eb-managing-insider-threats-in-the-technology-sector.pdf
Disallow: /sites/default/files/e-books/pfpt-us-eb-managing-insider-threats-in-the-technology-sector-.pdf
Disallow: /sites/default/files/threat-reports/gtd-pfpt-uk-a4-r-state-of-the-phish-2021.pdf
Disallow: /sites/default/files/misc/gtd-pfpt-de-a4-r-state-of-the-phish-2021.pdf
Disallow: /sites/default/files/misc/gtd-pfpt-fr-a4-r-state-of-the-phish-2021.pdf
Disallow: /sites/default/files/misc/Proofpoint-jp-a4-eb-2021-ransomware-survival-guide.pdf
Disallow: /sites/default/files/white-papers/pfpt-us-wp-securing-digital-healthcare.pdf
Disallow: /sites/default/files/e-books/pfpt-jp-eb-ransomware-survival-guide-executive-summary.pdf
Disallow: /sites/default/files/e-books/pfpt-us-eb-complete-guide-to-migrating-your-enterprise-archiving-system.pdf
Disallow: /sites/default/files/e-books/0503-001-01-01-pfpt-A4-e-book-youve-got-BEC-JP-30APR2020.pdf
Disallow: /sites/default/files/e-books/gtd-pfpt-es-eb-role-of-itm.pdf
Disallow: /sites/default/files/e-books/gtd-pfpt-es-eb-itm-cybersecurity.pdf
Disallow: /sites/default/files/e-books/gtd-pfpt-es-eb-setting-up-itm.pdf
Disallow: /sites/default/files/e-books/gtd-pfpt-es-eb-itm-overview.pdf
Disallow: /sites/default/files/white-papers/gtd-pfpt-es-a4-r-state-of-the-phish-2021.pdf.pdf
Disallow: /sites/default/files/white-papers/gtd-pfpt-it-a4-r-state-of-the-phish-2021.pdf.pdf
Disallow: /sites/default/files/threat-reports/gtd-pfpt-es-a4-r-state-of-the-phish-2021.pdf
Disallow: /sites/default/files/threat-reports/gtd-pfpt-it-a4-r-state-of-the-phish-2021.pdf
Disallow: /sites/default/files/threat-reports/220252.37-pfpt-jp-a4-r-state-of-the-phish-2021.pdf
Disallow: /sites/default/files/white-papers/pfpt-us-wp-business-impact-brief.pdf
Disallow: /sites/default/files/white-papers/gtd-pfpt-us-wp-people-centric-cybersecurity-federal-perspective.pdf
Disallow: /sites/default/files/e-books/pfpt-uk-eb-complete-guide-to-migrating-your-enterprise-archiving-system.pdf
Disallow: /sites/default/files/e-books/pfpt-au-eb-complete-guide-to-migrating-your-enterprise-archiving-system.pdf
Disallow: /sites/default/files/solution-briefs/pfpt-jp-wp-a4-people-centric-approach-insider-threat-management-3.pdf
Disallow: /sites/default/files/analyst-reports/pfpt-us-ar-cost-of-cloud-compromise-and-shadow-IT.pdf
Disallow: /sites/default/files/e-books/pfpt-uk-a4-eb-10-reasons-orgs-choose-pfpt-to-secure-email-and-cloud.pdf
Disallow: /sites/default/files/misc/pfpt-es-a4-eb-10-reasons-orgs-choose-pfpt-to-secure-email-and-cloud.pdf
Disallow: /sites/default/files/customer-stories/pfpt-jp-cs-macdonald_20210426a.pdf
Disallow: /sites/default/files/customer-stories/pfpt-jp-cs-mcdonald_20210426a.pdf
Disallow: /sites/default/files/misc/Password%20Day%20Awareness%20Kit.zip
Disallow: /sites/default/files/e-books/pfpt-uk-eb-managing-insider-threats-in-the-technology-sector.pdf
Disallow: /sites/default/files/e-books/pfpt-au-eb-managing-insider-threats-in-the-technology-sector.pdf
Disallow: /sites/default/files/e-books/pfpt-uk-eb-compliance-in-the-age-of-digital-collaboration.pdf
Disallow: /sites/default/files/e-books/pfpt-au-eb-compliance-in-the-age-of-digital-collaboration.pdf
Disallow: /sites/default/files/e-books/pfpt-us-eb-reimagining-email-security.pdf
Disallow: /sites/default/files/white-papers/pfpt-us-wp-beyond-the-cloud.pdf
Disallow: /sites/default/files/white-papers/pfpt-us-wp-voice-of-the-CISO-report.pdf
Disallow: /sites/default/files/e-books/pfpt-it-eb-reimagining-email-security.pdf
Disallow: /sites/default/files/e-books/pfpt-uk-eb-reimagining-email-security.pdf
Disallow: /sites/default/files/e-books/pfpt-au-eb-reimagining-email-security.pdf
Disallow: /sites/default/files/e-books/pfpt-fr-eb-reimagining-email-security.pdf
Disallow: /sites/default/files/e-books/pfpt-es-eb-reimagining-email-security.pdf
Disallow: /sites/default/files/e-books/pfpt-de-eb-reimagining-email-security.pdf
Disallow: /sites/default/files/e-books/gtd-pfpt-us-wp-getting-started-with-casb-v33.pdf
Disallow: /sites/default/files/e-books/pfpt-de-eb-reimagining-email-security-v3.pdf
Disallow: /sites/default/files/e-books/pfpt-us-eb-frost-sullivan-guarding-the-virtual-doorway.pdf
Disallow: /sites/default/files/awareness-materials/Email%20Fraud%20and%20Security%20Awareness%20Kit%202021.zip
Disallow: /sites/default/files/threat-reports/pfpt-us-tr-human-factor-report.pdf
Disallow: /sites/default/files/pfpt-uk-tr-human-factor-report.pdf
Disallow: /sites/default/files/pfpt-au-tr-human-factor-report.pdf
Disallow: /sites/default/files/pfpt-de-tr-human-factor-report.pdf
Disallow: /sites/default/files/pfpt-es-tr-human-factor-report.pdf
Disallow: /sites/default/files/pfpt-fr-tr-human-factor-report.pdf
Disallow: /sites/default/files/pfpt-it-tr-human-factor-report_0.pdf
Disallow: /sites/default/files/pfpt-it-tr-human-factor-report_1.pdf
Disallow: /sites/default/files/e-books/pfpt-us-eb-unmasking-bec-and-eac.pdf
Disallow: /sites/default/files/white-papers/pfpt-jp-wp-voice-of-the-CISO-report.pdf
Disallow: /sites/default/files/white-papers/pfpt-us-wp-beyond-vpn-securing-your-remote-workforce.pdf
Disallow: /sites/default/files/e-books/pfpt-us-eb-rethinking-dlp.pdf
Disallow: /sites/default/files/white-papers/pfpt-jp-wp-voice-of-the-CISO-report_v2.pdf
Disallow: /sites/default/files/e-books/pfpt-us-eb-the-anatomy-of-an-insider-threat-investigation.pdf
Disallow: /sites/default/files/e-books/pfpt-fr-eb-complete-guide-to-migrating-your-enterprise-archiving-system.pdf
Disallow: /sites/default/files/e-books/pfpt-de-eb-complete-guide-to-migrating-your-enterprise-archiving-system.pdf
Disallow: /sites/default/files/customer-stories/pfpt-jp-cs-segasammy_20210622.pdf
Disallow: /sites/default/files/e-books/pfpt-us-eb-the-bec-handbook.pdf
Disallow: /sites/default/files/analyst-reports/pfpt-us-ar-frost-radar-global-email-security-market-report.pdf
Disallow: /sites/default/files/e-books/pfpt-uk-eb-rethinking-dlp.pdf
Disallow: /sites/default/files/e-books/pfpt-au-eb-rethinking-dlp.pdf
Disallow: /sites/default/files/e-books/pfpt-it-eb-rethinking-dlp.pdf
Disallow: /sites/default/files/e-books/pfpt-de-eb-rethinking-dlp.pdf
Disallow: /sites/default/files/e-books/pfpt-es-eb-rethinking-dlp.pdf
Disallow: /sites/default/files/e-books/pfpt-fr-eb-rethinking-dlp.pdf
Disallow: /sites/default/files/threat-reports/pfpt-us-tr-the-cost-of-insider-threats-ponemon-report.pdf
Disallow: /sites/default/files/analyst-reports/pfpt-uk-ar-frost-radar-global-email-security-market-report.pdf
Disallow: /sites/default/files/analyst-reports/pfpt-au-ar-frost-radar-global-email-security-market-report.pdf
Disallow: /sites/default/files/analyst-reports/pfpt-uk-ar-cost-of-cloud-compromise-and-shadow-IT.pdf
Disallow: /sites/default/files/analyst-reports/pfpt-au-ar-cost-of-cloud-compromise-and-shadow-IT.pdf
Disallow: /sites/default/files/event-materials/210713_CYBERGYMxProofpoint.zip
Disallow: /sites/default/files/white-papers/pfpt-uk-wp-beyond-the-cloud.pdf
Disallow: /sites/default/files/white-papers/pfpt-au-wp-beyond-the-cloud.pdf
Disallow: /sites/default/files/event-materials/210713Webinar_Crowdstrike-Netskope-Okta-Proofpoint.zip
Disallow: /sites/default/files/threat-reports/pfpt-it-tr-human-factor-report.pdf
Disallow: /sites/default/files/analyst-reports/pfpt-us-ar-ponemon-2021-cost-of-phishing-study.pdf
Disallow: /sites/default/files/e-books/pfpt-jp-eb-rethinking-dlp.pdf
Disallow: /sites/default/files/white-papers/pfpt-uk-wp-securing-digital-healthcare.pdf
Disallow: /sites/default/files/white-papers/pfpt-au-wp-securing-digital-healthcare.pdf
Disallow: /sites/default/files/white-papers/pfpt-es-wp-securing-digital-healthcare.pdf
Disallow: /sites/default/files/white-papers/pfpt-de-wp-securing-digital-healthcare.pdf
Disallow: /sites/default/files/white-papers/pfpt-it-wp-securing-digital-healthcare.pdf
Disallow: /sites/default/files/white-papers/pfpt-fr-wp-securing-digital-healthcare.pdf
Disallow: /sites/default/files/e-books/pfpt-us-eb-three-information-protection-use-cases-in-the-cloud-era.pdf
Disallow: /sites/default/files/e-books/pfpt-us-eb-ige-modern-blueprint-to-information-protection.pdf
Disallow: /sites/default/files/analyst-reports/gtd-pfpt-us-ar-frost-radar-security-awareness-training-market-report-2021.pdf.pdf
Disallow: /sites/default/files/analyst-reports/gtd-pfpt-us-ar-frost-radar-security-awareness-training-market-report-2021.pdf
Disallow: /sites/default/files/e-books/pfpt-uk-eb-the-bec-handbook.pdf
Disallow: /sites/default/files/e-books/pfpt-au-eb-the-bec-handbook.pdf
Disallow: /sites/default/files/e-books/pfpt-fr-eb-the-bec-handbook.pdf
Disallow: /sites/default/files/e-books/pfpt-it-eb-the-bec-handbook.pdf
Disallow: /sites/default/files/e-books/pfpt-de-eb-the-bec-handbook.pdf
Disallow: /sites/default/files/e-books/pfpt-es-eb-the-bec-handbook.pdf
Disallow: /sites/default/files/e-books/pfpt-us-eb-data-breach-is-coming-from-inside-the-house.pdf
Disallow: /sites/default/files/e-books/pfpt-uk-eb-the-anatomy-of-an-insider-threat-investigation.pdf
Disallow: /sites/default/files/e-books/pfpt-au-eb-the-anatomy-of-an-insider-threat-investigation.pdf
Disallow: /sites/default/files/e-books/pfpt-fr-eb-the-anatomy-of-an-insider-threat-investigation.pdf
Disallow: /sites/default/files/e-books/pfpt-es-eb-the-anatomy-of-an-insider-threat-investigation.pdf
Disallow: /sites/default/files/e-books/pfpt-it-eb-the-anatomy-of-an-insider-threat-investigation.pdf
Disallow: /sites/default/files/e-books/pfpt-de-eb-the-anatomy-of-an-insider-threat-investigation.pdf
Disallow: /sites/default/files/white-papers/pfpt-de-wp-voice-of-the-CISO-report.pdf
Disallow: /sites/default/files/e-books/pfpt-jp-eb-the-bec-handbook.pdf
Disallow: /sites/default/files/threat-reports/pfpt-japanese-tr-human-factor-report.pdf
Disallow: /sites/default/files/e-books/pfpt-us-eb-biggest-and-boldest-insider-threats-2020-2021.pdf
Disallow: /sites/default/files/white-papers/pfpt-fr-wp-voice-of-the-CISO-report.pdf
Disallow: /sites/default/files/e-books/pfpt-us-eb-esg-ediscovery-market-trends-and-challenges.pdf
Disallow: /sites/default/files/e-books/pfpt-jp-eb-the-anatomy-of-an-insider-threat-investigation.pdf
Disallow: /sites/default/files/e-books/pfpt-us-eb-measuring-security-awareness-impact.pdf
Disallow: /sites/default/files/white-papers/pfpt-us-wp-building-a-business-case-for-itm.pdf
Disallow: /sites/default/files/e-books/pfpt-us-eb-2021-user-risk-report.pdf
Disallow: /sites/default/files/e-books/pfpt-uk-eb-biggest-and-boldest-insider-threats-2019-2020.pdf
Disallow: /sites/default/files/e-books/pfpt-au-eb-biggest-and-boldest-insider-threats-2019-2020.pdf
Disallow: /sites/default/files/e-books/pfpt-fr-eb-biggest-and-boldest-insider-threats-2019-2020.pdf
Disallow: /sites/default/files/e-books/pfpt-it-eb-biggest-and-boldest-insider-threats-2019-2020.pdf
Disallow: /sites/default/files/e-books/pfpt-es-eb-biggest-and-boldest-insider-threats-2019-2020.pdf
Disallow: /sites/default/files/e-books/pfpt-de-eb-biggest-and-boldest-insider-threats-2019-2020.pdf
Disallow: /sites/default/files/analyst-reports/pfpt-us-ar-frost-sullivan-market-leadership-award.pdf
Disallow: /sites/default/files/white-papers/pfpt-it-wp-building-a-business-case-for-itm.pdf
Disallow: /sites/default/files/white-papers/pfpt-es-wp-building-a-business-case-for-itm.pdf
Disallow: /sites/default/files/white-papers/pfpt-fr-wp-building-a-business-case-for-itm.pdf
Disallow: /sites/default/files/white-papers/pfpt-de-wp-building-a-business-case-for-itm.pdf
Disallow: /sites/default/files/analyst-reports/pfpt-us-ar-a-strategic-approach-to-zero-trust-security-the-spectra-alliance.pdf
Disallow: /sites/default/files/e-books/pfpt-uk-eb-measuring-security-awareness-impact.pdf
Disallow: /sites/default/files/e-books/pfpt-au-eb-measuring-security-awareness-impact.pdf
Disallow: /sites/default/files/e-books/pfpt-de-eb-measuring-security-awareness-impact.pdf
Disallow: /sites/default/files/e-books/pfpt-fr-eb-measuring-security-awareness-impact.pdf
Disallow: /sites/default/files/e-books/pfpt-it-eb-measuring-security-awareness-impact.pdf
Disallow: /sites/default/files/e-books/pfpt-es-eb-measuring-security-awareness-impact.pdf
Disallow: /sites/default/files/misc/2021%20PSAT%20Holiday%20Kit.zip
Disallow: /sites/default/files/threat-reports/pfpt-us-tr-fall-winter-2021-threat-update.pdf
Disallow: /sites/default/files/e-books/biggest-and-boldest-insider-threats-2020-2021-jp.pdf
Disallow: /sites/default/files/white-papers/pfpt-us-wp-idc-paper-fed-58.pdf
Disallow: /sites/default/files/e-books/pfpt-us-eb-open-channels-hidden-threats.pdf
Disallow: /sites/default/files/white-papers/pfpt-jp-wp-securing-digital-healthcare.pdf
Disallow: /sites/default/files/threat-reports/pfpt-jp-tr-threat-insight-paper-triple-threat-N-Korea-aligned-TA406-steals-scams-spies.pdf
Disallow: /sites/default/files/e-books/pfpt-jp-eb-measuring-security-awareness-impact.pdf
Disallow: /sites/default/files/awareness-materials/DE_Ransomware%20Awareness%20Kit.zip
Disallow: /sites/default/files/awareness-materials/UK_Ransomware%20Awareness%20Kit.zip
Disallow: /sites/default/files/white-papers/pfpt-us-wp-getting-started-with-casb.pdf
Disallow: /sites/default/files/e-books/pfpt-uk-eb-open-channels-hidden-threats.pdf
Disallow: /sites/default/files/e-books/pfpt-au-eb-open-channels-hidden-threats.pdf
Disallow: /sites/default/files/e-books/pfpt-fr-eb-open-channels-hidden-threats.pdf
Disallow: /sites/default/files/e-books/pfpt-de-eb-open-channels-hidden-threats.pdf
Disallow: /sites/default/files/e-books/pfpt-es-eb-open-channels-hidden-threats.pdf
Disallow: /sites/default/files/e-books/pfpt-it-eb-open-channels-hidden-threats.pdf
Disallow: /sites/default/files/e-books/pfpt-us-eb-2022-ransomware-survival-guide.pdf
Disallow: /sites/default/files/e-books/pfpt-jp-eb-open-channels-hidden-threats.pdf
Disallow: /sites/default/files/e-books/pfpt-us-eb-breaking-down-bec.pdf
Disallow: /sites/default/files/e-books/pfpt-it-eb-2021-ransomware-survival-guide.pdf
Disallow: /sites/default/files/e-books/pfpt-de-eb-2021-ransomware-survival-guide.pdf
Disallow: /sites/default/files/e-books/pfpt-es-eb-2021-ransomware-survival-guide.pdf
Disallow: /sites/default/files/e-books/pfpt-fr-eb-2021-ransomware-survival-guide.pdf
Disallow: /sites/default/files/e-books/pfpt-us-eb-youve-got-bec.pdf
Disallow: /sites/default/files/misc/ISMG%20-%20Proofpoint%20-%20Matt%20Cooke%20eBook.pdf
Disallow: /sites/default/files/threat-reports/pfpt-uk-tr-the-cost-of-insider-threats-ponemon-report.pdf
Disallow: /sites/default/files/threat-reports/pfpt-au-tr-the-cost-of-insider-threats-ponemon-report.pdf
Disallow: /sites/default/files/threat-reports/pfpt-es-tr-the-cost-of-insider-threats-ponemon-report.pdf
Disallow: /sites/default/files/threat-reports/pfpt-de-tr-the-cost-of-insider-threats-ponemon-report.pdf
Disallow: /sites/default/files/threat-reports/pfpt-fr-tr-the-cost-of-insider-threats-ponemon-report.pdf
Disallow: /sites/default/files/threat-reports/pfpt-it-tr-the-cost-of-insider-threats-ponemon-report.pdf
Disallow: /sites/default/files/e-books/pfpt-us-eb-social-media-threats-ismg.pdf
Disallow: /sites/default/files/analyst-reports/pfpt-jp-tr-the-cost-of-insider-threats-ponemon-report.pdf
Disallow: /sites/default/files/e-books/pfpt-uk-eb-data-breach-is-coming-from-inside-the-house.pdf
Disallow: /sites/default/files/e-books/pfpt-au-eb-data-breach-is-coming-from-inside-the-house.pdf
Disallow: /sites/default/files/e-books/pfpt-fr-eb-data-breach-is-coming-from-inside-the-house.pdf
Disallow: /sites/default/files/e-books/pfpt-it-eb-data-breach-is-coming-from-inside-the-house.pdf
Disallow: /sites/default/files/e-books/pfpt-de-eb-data-breach-is-coming-from-inside-the-house.pdf
Disallow: /sites/default/files/e-books/pfpt-us-eb-current-state-of-data-privacy.pdf
Disallow: /sites/default/files/threat-reports/pfpt-us-tr-state-of-the-phish-2022.pdf
Disallow: /sites/default/files/threat-reports/pfpt-uk-tr-state-of-the-phish-2022.pdf
Disallow: /sites/default/files/threat-reports/pfpt-au-tr-state-of-the-phish-2022.pdf
Disallow: /sites/default/files/threat-reports/pfpt-fr-tr-state-of-the-phish-2022.pdf
Disallow: /sites/default/files/threat-reports/pfpt-es-tr-state-of-the-phish-2022.pdf
Disallow: /sites/default/files/threat-reports/pfpt-it-tr-state-of-the-phish-2022.pdf
Disallow: /sites/default/files/threat-reports/pfpt-de-tr-state-of-the-phish-2022.pdf
Disallow: /sites/default/files/e-books/pfpt-es-eb-data-breach-is-coming-from-inside-the-house.pdf
Disallow: /sites/default/files/e-books/pfpt-us-eb-making-sense-of-sase-and-sse.pdf
Disallow: /sites/default/files/e-books/pfpt-us-eb-modern-blueprint-to-insider-threat-management.pdf
Disallow: /sites/default/files/white-papers/pfpt-us-wp-idc-spotlight-higher-education.pdf
Disallow: /sites/default/files/e-books/pfpt-jp-eb-2022-ransomware-survival-guide.pdf
Disallow: /sites/default/files/e-books/pfpt-us-eb-email-reporting-and-remediation.pdf
Disallow: /sites/default/files/e-books/pfpt-us-eb-legacy-%20dlp-crumbles-in-the-cloud.pdf
Disallow: /sites/default/files/e-books/pfpt-us-eb-legacy-dlp-crumbles-in-the-crowd.pdf
Disallow: /sites/default/files/e-books/pfpt-us-eb-risk-aware-data-privacy.pdf
Disallow: /sites/default/files/e-books/pfpt-uk-eb-youve-got-bec.pdf
Disallow: /sites/default/files/e-books/pfpt-au-eb-youve-got-bec.pdf
Disallow: /sites/default/files/e-books/pfpt-it-eb-youve-got-bec.pdf
Disallow: /sites/default/files/e-books/pfpt-de-eb-youve-got-bec.pdf
Disallow: /sites/default/files/e-books/pfpt-es-eb-youve-got-bec.pdf
Disallow: /sites/default/files/e-books/pfpt-fr-eb-youve-got-bec.pdf
Disallow: /sites/default/files/e-books/pfpt-us-eb-managing-cybersecurity-skills-shortage.pdf
Disallow: /sites/default/files/e-books/pfpt-jp-eb-data-breach-is-coming-from-inside-the-house.pdf
Disallow: /sites/default/files/white-papers/pfpt-us-wp-email-security-rfp-rfi-template-jan-2022.xlsx
Disallow: /sites/default/files/threat-reports/pfpt-jp-tr-state-of-the-phish-2022.pdf
Disallow: /sites/default/files/e-books/pfpt-us-eb-metrics-that-matter.pdf
Disallow: /sites/default/files/e-books/pfpt-uk-eb-breaking-down-bec.pdf
Disallow: /sites/default/files/e-books/pfpt-au-eb-breaking-down-bec.pdf
Disallow: /sites/default/files/e-books/pfpt-fr-eb-breaking-down-bec.pdf
Disallow: /sites/default/files/e-books/pfpt-it-eb-breaking-down-bec.pdf
Disallow: /sites/default/files/e-books/pfpt-de-eb-breaking-down-bec.pdf
Disallow: /sites/default/files/e-books/pfpt-es-eb-breaking-down-bec.pdf
Disallow: /sites/default/files/e-books/pfpt-us-eb-the-definitive-email-cybersecurity-guide.pdf
Disallow: /sites/default/files/e-books/pfpt-us-eb-beyond-awareness-training.pdf
Disallow: /sites/default/files/e-books/pfpt-us-eb-reimagining-risk-and-resilience.pdf
Disallow: /sites/default/files/white-papers/pfpt-es-wp-voice-of-the-CISO-report.pdf
Disallow: /sites/default/files/white-papers/pfpt-uk-wp-voice-of-the-CISO-report.pdf
Disallow: /sites/default/files/white-papers/pfpt-au-wp-voice-of-the-CISO-report.pdf
Disallow: /sites/default/files/infographics/PP_jp_InsiderThreat_Infographic_final_ysohta0309a.pdf
Disallow: /sites/default/files/e-books/pfpt-uk-eb-modern-blueprint-to-insider-threat-management.pdf
Disallow: /sites/default/files/e-books/pfpt-au-eb-modern-blueprint-to-insider-threat-management.pdf
Disallow: /sites/default/files/e-books/pfpt-de-eb-metrics-that-matter.pdf
Disallow: /sites/default/files/e-books/pfpt-es-eb-metrics-that-matter.pdf
Disallow: /sites/default/files/e-books/pfpt-fr-eb-metrics-that-matter.pdf
Disallow: /sites/default/files/e-books/pfpt-br-eb-metrics-that-matter.pdf
Disallow: /sites/default/files/e-books/pfpt-it-eb-metrics-that-matter.pdf
Disallow: /sites/default/files/e-books/pfpt-uk-eb-email-reporting-and-remediation.pdf
Disallow: /sites/default/files/e-books/pfpt-au-eb-email-reporting-and-remediation.pdf
Disallow: /sites/default/files/e-books/pfpt-de-eb-email-reporting-and-remediation.pdf
Disallow: /sites/default/files/e-books/pfpt-es-eb-email-reporting-and-remediation.pdf
Disallow: /sites/default/files/e-books/pfpt-fr-eb-email-reporting-and-remediation.pdf
Disallow: /sites/default/files/e-books/pfpt-it-eb-email-reporting-and-remediation.pdf
Disallow: /sites/default/files/threat-reports/pfpt-us-tr-the-human-factor-report-2022.pdf
Disallow: /sites/default/files/e-books/pfpt-uk-eb-managing-cybersecurity-skills-shortage.pdf
Disallow: /sites/default/files/e-books/pfpt-au-eb-managing-cybersecurity-skills-shortage.pdf
Disallow: /sites/default/files/e-books/pfpt-fr-eb-managing-cybersecurity-skills-shortage.pdf
Disallow: /sites/default/files/e-books/pfpt-de-eb-managing-cybersecurity-skills-shortage.pdf
Disallow: /sites/default/files/e-books/pfpt-it-eb-managing-cybersecurity-skills-shortage.pdf
Disallow: /sites/default/files/e-books/pfpt-es-eb-managing-cybersecurity-skills-shortage.pdf
Disallow: /sites/default/files/threat-reports/pfpt-uk-tr-human-factor-report-2022.pdf
Disallow: /sites/default/files/threat-reports/pfpt-fr-tr-human-factor-report-2022.pdf
Disallow: /sites/default/files/threat-reports/pfpt-de-tr-human-factor-report-2022.pdf
Disallow: /sites/default/files/threat-reports/pfpt-it-tr-human-factor-report-2022.pdf
Disallow: /sites/default/files/threat-reports/pfpt-br-tr-human-factor-report-2022.pdf
Disallow: /sites/default/files/threat-reports/pfpt-us-tr-human-factor-report-2022.pdf
Disallow: /sites/default/files/threat-reports/pfpt-uk-tr-human-factor-report-2022_0.pdf
Disallow: /sites/default/files/threat-reports/pfpt-uk-tr-human-factor-report-2022.pdf
Disallow: /sites/default/files/threat-reports/pfpt-uk-tr-human-factor-report-2022.pdf
Disallow: /sites/default/files/threat-reports/pfpt-us-tr-human-factor-report-2022.pdf
Disallow: /sites/default/files/threat-reports/pfpt-br-tr-human-factor-report.pdf
Disallow: /sites/default/files/threat-reports/pfpt-es-tr-human-factor-report.pdf
Disallow: /sites/default/files/threat-reports/pfpt-de-tr-human-factor-report.pdf
Disallow: /sites/default/files/threat-reports/pfpt-fr-tr-human-factor-report.pdf
Disallow: /sites/default/files/threat-reports/pfpt-uk-tr-human-factor-report.pdf
Disallow: /sites/default/files/threat-reports/pfpt-au-tr-human-factor-report.pdf
Disallow: /sites/default/files/e-books/pfpt-br-eb-breaking-down-bec.pdf
Disallow: /sites/default/files/e-books/pfpt-jp-eb-metrics-that-matter.pdf
Disallow: /sites/default/files/e-books/pfpt-us-eb-gartner-how-to-succeed-with-data-classification.pdf
Disallow: /sites/default/files/e-books/pfpt-jp-eb-email-reporting-and-remediation.pdf
Disallow: /sites/default/files/e-books/pfpt-us-eb-getting-dlp-right.pdf
Disallow: /sites/default/files/threat-reports/2022-CISO-REPORT_Final_jp_v2.pdf
Disallow: /sites/default/files/e-books/pfpt-uk-eb-the-definitive-email-cybersecurity-guide.pdf
Disallow: /sites/default/files/e-books/pfpt-au-eb-the-definitive-email-cybersecurity-guide.pdf
Disallow: /sites/default/files/e-books/pfpt-it-eb-the-definitive-email-cybersecurity-guide.pdf
Disallow: /sites/default/files/e-books/pfpt-de-eb-the-definitive-email-cybersecurity-guide.pdf
Disallow: /sites/default/files/e-books/pfpt-br-eb-the-definitive-email-cybersecurity-guide.pdf
Disallow: /sites/default/files/e-books/pfpt-fr-eb-the-definitive-email-cybersecurity-guide.pdf
Disallow: /sites/default/files/e-books/pfpt-es-eb-the-definitive-email-cybersecurity-guide.pdf
Disallow: /sites/default/files/e-books/pfpt-us-eb-legacy-dlp-crumbles-in-the-cloud.pdf
Disallow: /sites/default/files/e-books/pfpt-uk-eb-beyond-awareness-training.pdf
Disallow: /sites/default/files/e-books/pfpt-au-eb-beyond-awareness-training.pdf
Disallow: /sites/default/files/e-books/pfpt-it-eb-beyond-awareness-training.pdf
Disallow: /sites/default/files/e-books/pfpt-de-eb-beyond-awareness-training.pdf
Disallow: /sites/default/files/e-books/pfpt-es-eb-beyond-awareness-training.pdf
Disallow: /sites/default/files/e-books/pfpt-fr-eb-beyond-awareness-training.pdf
Disallow: /sites/default/files/e-books/pfpt-br-eb-beyond-awareness-training.pdf
Disallow: /sites/default/files/white-papers/pfpt-kr-wp-voice-of-the-CISO-report.pdf
Disallow: /sites/default/files/e-books/pfpt-us-eb-inertia-not-an-option.pdf
Disallow: /sites/default/files/e-books/pfpt-it-eb-risk-aware-data-privacy.pdf
Disallow: /sites/default/files/e-books/pfpt-de-eb-risk-aware-data-privacy.pdf
Disallow: /sites/default/files/e-books/pfpt-fr-eb-risk-aware-data-privacy.pdf
Disallow: /sites/default/files/e-books/pfpt-es-eb-risk-aware-data-privacy.pdf
Disallow: /sites/default/files/threat-reports/pfpt-br-tr-state-of-the-phish-2022.pdf
Disallow: /sites/default/files/e-books/pfpt-jp-eb-the-definitive-email-cybersecurity-guide.pdf
Disallow: /sites/default/files/awareness-materials/Cybersecurity%20Awareness%20Kit_jp.zip
Disallow: /sites/default/files/legal-documents/pfpt-en-business-conduct-guidelines-20190724.pdf
Disallow: /sites/default/files/legal-documents/pfpt-en-security-products-exhibit-20180806.pdf
Disallow: /sites/default/files/legal-documents/pfpt-en-gb-general-terms-and-conditions-20180521.pdf
Disallow: /sites/default/files/legal-documents/pfpt-en-general-terms-and-conditions-20201110.pdf
Disallow: /sites/default/files/legal-documents/pfpt-en-digital-risk-products-exhibit-20171006.pdf
Disallow: /sites/default/files/legal-documents/pfpt-en-information-and-compliance-products-exhibit-20190516.pdf
Disallow: /sites/default/files/legal-documents/pfpt-en-premium-support-for-cloudmark-products.pdf
Disallow: /sites/default/files/legal-documents/pfpt-en-support-services-program-202103.pdf
Disallow: /sites/default/files/legal-documents/pfpt-en-essentials-eula-20201009.pdf
Disallow: /sites/default/files/legal-documents/pfpt-en-evaluation-terms-and-conditions-201108.pdf
Disallow: /sites/default/files/legal-documents/pfpt-en-data-security-protection-audit-and-compliance-policy-20220502.pdf
Disallow: /sites/default/files/legal-documents/pfpt-en-hosted-services-sla-201603.pdf
Disallow: /sites/default/files/legal-documents/pfpt-en-psat-products-support-services-program-2019.pdf
Disallow: /sites/default/files/legal-documents/pfpt-en-jp-proofpoint-customer-dpa.pdf
Disallow: /sites/default/files/legal-documents/pfpt-transferring-data-from-japan.zip
Disallow: /sites/default/files/legal-documents/pfpt-transferring-data-from-the-eu.zip
Disallow: /sites/default/files/legal-documents/pfpt-transferring-data-from-the-uk.zip
Disallow: /sites/default/files/legal-documents/pfpt-en-proofpoint-essentials-sla.pdf
Disallow: /sites/default/files/legal-documents/pfpt-en-proofpoint-digital-risk-services-sla.pdf
Disallow: /sites/default/files/legal-documents/pfpt-en-information-cloud-security-platform-sla.pdf
Disallow: /sites/default/files/legal-documents/pfpt-web-security-sla-20220429.pdf
Disallow: /sites/default/files/legal-documents/pfpt-en-ser-sla-20220426.pdf
Disallow: /sites/default/files/legal-documents/pfpt-en-gb-uk-modern-slavery-act-transparency-statement-20220407_0.pdf
Disallow: /sites/default/files/legal-documents/pfpt-en-jp-proofpoint-partner-dpa.pdf
Disallow: /sites/default/files/legal-documents/pfpt-en-business-conduct-guidelines-20220413.pdf
Disallow: /sites/default/files/legal-documents/pfpt-en-whistleblower-and-compliant-policy-20220413.pdf
Disallow: /sites/default/files/legal-documents/pfpt-en-information-disclosure-statement-20220419.pdf
Disallow: /sites/default/files/legal-documents/pfpt-en-cloudmark-smc-cpsaas-sla-20200827.pdf
Disallow: /sites/default/files/legal-documents/pfpt-en-ser-sla.pdf
Disallow: /sites/default/files/legal-documents/pfpt-en-itm-saas-sla.pdf
Disallow: /sites/default/files/legal-documents/pfpt-en-business-associate-agreement-presigned-addendum.pdf
Disallow: /sites/default/files/legal-documents/pfpt-it-gdpr-dpa-202203.pdf
Disallow: /sites/default/files/legal-documents/pfpt-es-gdpr-dpa-202203.pdf
Disallow: /sites/default/files/legal-documents/pfpt-en-gdpr-dpa-202203.pdf
Disallow: /sites/default/files/legal-documents/pfpt-en-gb-idta-20220409.pdf
Disallow: /sites/default/files/legal-documents/pfpt-en-ccpa-data-processing-presigned-addendum.pdf
Disallow: /sites/default/files/e-books/pfpt-jp-eb-managing-cybersecurity-skills-shortage.pdf
Disallow: /sites/default/files/white-papers/pfpt-us-wp-data-sensitivity.pdf
Disallow: /sites/default/files/e-books/pfpt-jp-eb-risk-aware-data-privacy.pdf
Disallow: /sites/default/files/e-books/pfpt-jp-eb-breaking-down-bec.pdf
Disallow: /sites/default/files/e-books/pfpt-br-eb-email-reporting-and-remediation.pdf
Disallow: /sites/default/files/e-books/pfpt-jp-eb-beyond-awareness-training.pdf
Disallow: /sites/default/files/e-books/pfpt-jp-eb-getting-started-with-DMARC-ebook_2020-b.pdf
Disallow: /sites/default/files/e-books/pfpt-fr-eb-third-party-oauth-apps-faq-security-checklist.pdf
Disallow: /sites/default/files/e-books/pfpt-es-eb-third-party-oauth-apps-faq-security-checklist.pdf
Disallow: /sites/default/files/e-books/pfpt-us-eb-cloud-and-web-attacks.pdf
Disallow: /sites/default/files/threat-reports/pfpt-kr-tr-the-cost-of-insider-threats-ponemon-report.pdf
Disallow: /sites/default/files/white-papers/pfpt-de-wp-third-party-oauth-apps-security.pdf
Disallow: /sites/default/files/white-papers/pfpt-it-wp-third-party-oauth-apps-security.pdf
Disallow: /sites/default/files/threat-reports/Proofpoint-jp-DM-ISSUE-4-Final.pdf
Disallow: /sites/default/files/legal-documents/pfpt-en-data-transfer-assessment-20201028.pdf
Disallow: /sites/default/files/legal-documents/pfpt-privacy-policy-202203.pdf
Disallow: /sites/default/files/legal-documents/pfpt-en-gdpr-dpa-and-scc.pdf
Disallow: /sites/default/files/legal-documents/pfpt-it-gdpr-dpa-and-scc.pdf
Disallow: /sites/default/files/legal-documents/pfpt-en-privacy-policy-202203.pdf
Disallow: /sites/default/files/legal-documents/pfpt-es-dpa-and-scc.pdf
Disallow: /sites/default/files/legal-documents/pfpt-en-data-security-policy-202205.pdf
Disallow: /sites/default/files/legal-documents/pfpt-fr-gdpr-dpa-and-scc.pdf
Disallow: /sites/default/files/legal-documents/pfpt-de-gdpr-dpa-and-scc.pdf
Disallow: /sites/default/files/legal-documents/pfpt-en-third-party-providers-and-subprocessors-202205.pdf
Disallow: /sites/default/files/legal-documents/pfpt-en-gb-uk-addendum-202204.pdf
Disallow: /sites/default/files/legal-documents/pfpt-ja-privacy-policy.pdf
Disallow: /sites/default/files/legal-documents/pfpt-en-jp-customer-data-processing-agreement.pdf
Disallow: /sites/default/files/legal-documents/pfpt-en-jp-partner-data-processing-agreement.pdf
Disallow: /sites/default/files/legal-documents/pfpt-en-ccpa-addendum.pdf
Disallow: /sites/default/files/legal-documents/pfpt-en-business-associate-agreement-addendum.pdf
Disallow: /sites/default/files/legal-documents/pfpt-en-gb-uk-addendum-202204_0.pdf
Disallow: /sites/default/files/legal-documents/pfpt-en-gb-uk-addendum-202204_1.pdf
Disallow: /sites/default/files/legal-documents/pfpt-de-gdpr-dpa-and-scc.pdf
Disallow: /sites/default/files/legal-documents/pfpt-fr-gdpr-dpa-and-scc.pdf
Disallow: /sites/default/files/legal-documents/pfpt-es-dpa-and-scc.pdf
Disallow: /sites/default/files/legal-documents/pfpt-it-gdpr-dpa-and-scc.pdf
Disallow: /sites/default/files/legal-documents/pfpt-ja-privacy-policy.pdf
Disallow: /sites/default/files/legal-documents/pfpt-en-gb-uk-addendum-202204_1.pdf
Disallow: /sites/default/files/legal-documents/pfpt-en-gb-uk-addendum-202204_1.pdf
Disallow: /sites/default/files/legal-documents/pfpt-es-gdpr-dpa-and-scc.pdf
Disallow: /sites/default/files/legal-documents/pfpt-en-gb-uk-addendum-202204_1.pdf
Disallow: /sites/default/files/e-books/pfpt-uk-eb-getting-started-with-dmarc-ebook.pdf
Disallow: /sites/default/files/e-books/pfpt-au-eb-getting-started-with-dmarc-ebook.pdf
Disallow: /sites/default/files/e-books/pfpt-it-eb-getting-started-with-dmarc-ebook.pdf
Disallow: /sites/default/files/e-books/pfpt-br-eb-getting-started-with-dmarc-ebook.pdf
Disallow: /sites/default/files/legal-documents/pfpt-en-gb-uk-addendum-202204.pdf
Disallow: /sites/default/files/e-books/pfpt-de-eb-getting-started-with-dmarc-ebook.pdf
Disallow: /sites/default/files/e-books/pfpt-fr-eb-getting-started-with-dmarc-ebook.pdf
Disallow: /sites/default/files/e-books/pfpt-es-eb-getting-started-with-dmarc-ebook.pdf
Disallow: /sites/default/files/e-books/pfpt-uk-eb-inertia-not-an-option.pdf
Disallow: /sites/default/files/e-books/pfpt-au-eb-inertia-not-an-option.pdf
Disallow: /sites/default/files/e-books/pfpt-fr-eb-inertia-not-an-option.pdf
Disallow: /sites/default/files/e-books/pfpt-it-eb-inertia-not-an-option.pdf
Disallow: /sites/default/files/e-books/pfpt-de-eb-inertia-not-an-option.pdf
Disallow: /sites/default/files/e-books/pfpt-es-eb-inertia-not-an-option.pdf
Disallow: /sites/default/files/legal-documents/pfpt-en-gdpr-dpa-and-scc-202208.pdf
Disallow: /sites/default/files/e-books/gtd-pfpt-jp-wp-ebook-third-party-oauthpps-qa-security-checklist.pdf
Disallow: /sites/default/files/legal-documents/pfpt-en-gdpr-dpa.pdf
Disallow: /sites/default/files/e-books/pfpt-uk-eb-cloud-web-security-challenges-2022.pdf
Disallow: /sites/default/files/e-books/pfpt-au-eb-cloud-web-security-challenges-2022.pdf
Disallow: /sites/default/files/e-books/pfpt-fr-eb-cloud-web-security-challenges-2022.pdf
Disallow: /sites/default/files/e-books/pfpt-it-eb-cloud-web-security-challenges-2022.pdf
Disallow: /sites/default/files/e-books/pfpt-es-eb-cloud-web-security-challenges-2022.pdf
Disallow: /sites/default/files/e-books/pfpt-de-eb-cloud-web-security-challenges-2022.pdf
Disallow: /sites/default/files/data-sheets/pfpt-jp-a4-ds-managed-services-for-information-protection.pdf
Disallow: /sites/default/files/threat-reports/Proofpoint-UAE-REPORT-2022.pdf
Disallow: /sites/default/files/e-books/pfpt-us-eb-misc-guide-to-global-digital-comm-regs.pdf
Disallow: /sites/default/files/legal-documents/pfpt-en-dpa-amendment.pdf
Disallow: /sites/default/files/legal-documents/pfpt-es-gdpr-dpa.pdf
Disallow: /sites/default/files/legal-documents/pfpt-fr-gdpr-dpa.pdf
Disallow: /sites/default/files/legal-documents/pfpt-it-gdpr-dpa.pdf
Disallow: /sites/default/files/legal-documents/pfpt-de-gdpr-dpa.pdf
Disallow: /sites/default/files/e-books/pfpt-jp-eb-getting-started-with-dmarc-ebook.pdf
Disallow: /sites/default/files/e-books/pfpt-sg-eb-user-risk-report.pdf
Disallow: /sites/default/files/white-papers/pfpt-us-wp-board-perspective-report.pdf
Disallow: /sites/default/files/threat-reports/pfpt-us-tr-spr-summ-report.pdf
Disallow: /sites/default/files/e-books/pfpt-us-eb-cost-of-good-enough-security.pdf
Disallow: /sites/default/files/legal-documents/pfpt-px-sla.pdf
Disallow: /sites/default/files/e-books/pfpt-us-eb-securing-microsoft-365.pdf
Disallow: /sites/default/files/white-papers/pfpt-uk-wp-board-perspective-report.pdf
Disallow: /sites/default/files/white-papers/pfpt-au-wp-board-perspective-report.pdf
Disallow: /sites/default/files/threat-reports/Proofpoint-Cybersecurity-Deutschland-Menschen-Daten-besser-sch%C3%BCtzen.pdf
Disallow: /sites/default/files/legal-documents/pfpt-en-uk-addendum.pdf
Disallow: /sites/default/files/legal-documents/pfpt-en-gb-uk-addendum.pdf
Disallow: /sites/default/files/misc/pfpt-jp-cs-psat-iris-ohyamama_20220916a_FINAL_wo.address.pdf
Disallow: /sites/default/files/customer-stories/pfpt-jp-cs-psat-iris-ohyamama.pdf
Disallow: /sites/default/files/customer-stories/pfpt-jp-cs-ITM-Softbank_20221024a.pdf
Disallow: /sites/default/files/white-papers/Proofpoint-jp-DM-ISSUE-4-Final.pdf
Disallow: /sites/default/files/white-papers/pfpt-us-wp-explainable-document-classification.pdf
Disallow: /sites/default/files/legal-documents/pfpt-en-digital-risk-products-sla.pdf
Disallow: /sites/default/files/white-papers/pfpt-es-wp-board-perspective-report-summary.pdf.pdf
Disallow: /sites/default/files/white-papers/pfpt-fr-wp-board-perspective-report-summary.pdf.pdf
Disallow: /sites/default/files/white-papers/pfpt-it-wp-board-perspective-report-summary.pdf.pdf
Disallow: /sites/default/files/white-papers/pfpt-de-wp-board-perspective-report-summary.pdf.pdf
Disallow: /sites/default/files/e-books/pfpt-us-eb-phish-in-a-barrel.pdf
Disallow: /sites/default/files/white-papers/pfpt-us-wp-avoid-mistakes-that-expose-data.pdf
Disallow: /sites/default/files/misc/2022%20PSAT%20Holiday%20Kit.zip
Disallow: /sites/default/files/threat-reports/pfpt-covid-research_v2.pdf
Disallow: /sites/default/files/legal-documents/pfpt-en-business-conduct-guidelines.pdf
Disallow: /sites/default/files/legal-documents/pfpt-en-gb-uk-modern-slavery-act-transparency-statement.pdf
Disallow: /sites/default/files/legal-documents/pfpt-en-whistleblower-and-complaint-policy.pdf
Disallow: /sites/default/files/legal-documents/pfpt-en-gb-uk-modern-slavery-and-human-trafficking-statement.pdf
Disallow: /sites/default/files/analyst-reports/pfpt-jp-wp-board-perspective-report.pdf
Disallow: /sites/default/files/threat-reports/Proofpoint-Italy-CISO-Survey.pdf
Disallow: /sites/default/files/e-books/pfpt-uk-eb-cost-of-good-enough-security.pdf
Disallow: /sites/default/files/e-books/pfpt-au-eb-cost-of-good-enough-security.pdf
Disallow: /sites/default/files/e-books/pfpt-fr-eb-cost-of-good-enough-security.pdf
Disallow: /sites/default/files/e-books/pfpt-it-eb-cost-of-good-enough-security.pdf
Disallow: /sites/default/files/e-books/pfpt-de-eb-cost-of-good-enough-security.pdf
Disallow: /sites/default/files/e-books/pfpt-es-eb-cost-of-good-enough-security.pdf
Disallow: /sites/default/files/legal-documents/pfpt-en-scc-addendum-for-switzerland.pdf
Disallow: /sites/default/files/data-sheets/pfpt-jp-a4-ds-email-fraud-defense.pdf
Disallow: /sites/default/files/customer-stories/pfpt-jp-cs-psat-jgc-holdings.pdf
Disallow: /sites/default/files/legal-documents/pfpt-en-us-privacy-law-addendum.pdf
Disallow: /sites/default/files/white-papers/pfpt-uk-wp-explainable-document-classification.pdf
Disallow: /sites/default/files/white-papers/pfpt-au-wp-explainable-document-classification.pdf
Disallow: /sites/default/files/white-papers/pfpt-it-wp-explainable-document-classification.pdf
Disallow: /sites/default/files/white-papers/pfpt-fr-wp-explainable-document-classification.pdf
Disallow: /sites/default/files/white-papers/pfpt-es-wp-explainable-document-classification.pdf
Disallow: /sites/default/files/white-papers/pfpt-de-wp-explainable-document-classification.pdf
Disallow: /sites/default/files/analyst-reports/pfpt-jp-wp-board-perspective-report_v2.pdf
Disallow: /sites/default/files/e-books/pfpt-jp-eb-inertia-not-an-option.pdf
Disallow: /sites/default/files/threat-reports/pfpt-jp-wp-board-perspective-report.pdf
Disallow: /sites/default/files/white-papers/pfpt-jp-wp-explainable-document-classification.pdf
Disallow: /sites/default/files/white-papers/pfpt-uk-wp-driving-real-behavior-change.pdf
Disallow: /sites/default/files/white-papers/pfpt-au-wp-driving-real-behavior-change.pdf
Disallow: /sites/default/files/white-papers/pfpt-it-wp-driving-real-behavior-change.pdf
Disallow: /sites/default/files/white-papers/pfpt-es-wp-driving-real-behavior-change.pdf
Disallow: /sites/default/files/legal-documents/pfpt-en-scc-addendum-for-brazil.pdf
Disallow: /sites/default/files/e-books/pfpt-uk-eb-phish-in-a-barrel.pdf
Disallow: /sites/default/files/e-books/pfpt-au-eb-phish-in-a-barrel.pdf
Disallow: /sites/default/files/e-books/pfpt-fr-eb-phish-in-a-barrel.pdf
Disallow: /sites/default/files/e-books/pfpt-es-eb-phish-in-a-barrel.pdf
Disallow: /sites/default/files/e-books/pfpt-de-eb-phish-in-a-barrel.pdf
Disallow: /sites/default/files/e-books/pfpt-it-eb-phish-in-a-barrel.pdf
Disallow: /sites/default/files/white-papers/pfpt-fr-wp-driving-real-behavior-change.pdf
Disallow: /sites/default/files/white-papers/pfpt-de-wp-driving-real-behavior-change.pdf
Disallow: /sites/default/files/analyst-reports/pfpt-jp-a4-rpt-cloud-web-security-challenges-2022.pdf
Disallow: /sites/default/files/e-books/pfpt-jp-eb-cost-of-good-enough-security.pdf
Disallow: /sites/default/files/legal-documents/pfpt-en-pt-scc-addendum-for-brazil.pdf
Disallow: /sites/default/files/legal-documents/pfpt-en-ch-scc-addendum-for-switzerland.pdf
Disallow: /sites/default/files/legal-documents/pfpt-en-gb-addendum.pdf
Disallow: /sites/default/files/legal-documents/pfpt-en-gb-modern-slavery-and-human-trafficking-statement.pdf
Disallow: /sites/default/files/legal-documents/pfpt-en-privacy-law-addendum.pdf
Disallow: /sites/default/files/legal-documents/pfpt-en-data-security-policy.pdf
Disallow: /sites/default/files/legal-documents/pfpt-en-data-transfer-assessment.pdf
Disallow: /sites/default/files/legal-documents/pfpt-en-support-services-program.pdf
Disallow: /sites/default/files/legal-documents/pfpt-en-master-subscription-agreement.pdf
Disallow: /sites/default/files/legal-documents/pfpt-en-general-terms-and-conditions.pdf
Disallow: /sites/default/files/legal-documents/pfpt-en-gb-general-terms-and-conditions.pdf
Disallow: /sites/default/files/legal-documents/pfpt-en-psat-products-support-services-program.pdf
Disallow: /sites/default/files/legal-documents/pfpt-en-evaluation-terms-and-conditions.pdf
Disallow: /sites/default/files/legal-documents/pfpt-en-security-products-exhibit.pdf
Disallow: /sites/default/files/legal-documents/pfpt-en-digital-risk-products-exhibit.pdf
Disallow: /sites/default/files/legal-documents/pfpt-en-information-and-compliance-products-exhibit.pdf
Disallow: /sites/default/files/legal-documents/pfpt-en-essentials-eula.pdf
Disallow: /sites/default/files/legal-documents/pfpt-en-hosted-services-sla.pdf
Disallow: /sites/default/files/legal-documents/pfpt-en-gb-modern-slavery%20act-and-human-trafficking-statement.pdf
Disallow: /sites/default/files/legal-documents/pfpt-en-gb-uk-modern-slavery%20act-and-human-trafficking-statement.pdf
Disallow: /sites/default/files/legal-documents/pfpt-en-gb-modern-slavery-act-and-human-trafficking-statement.pdf
Disallow: /sites/default/files/e-books/pfpt-jp-eb-phish-in-a-barrel.pdf
Disallow: /sites/default/files/e-books/pfpt-us-eb-getting-started-with-casb.pdf
Disallow: /sites/default/files/white-papers/pfpt-us-wp-gettting-started-with-dmarc.pdf
Disallow: /sites/default/files/analyst-reports/pfpt-us-ar-2023-security-awareness-study.pdf
Disallow: /sites/default/files/white-papers/pfpt-jp-wp-driving-real-behavior-change.pdf
Disallow: /sites/default/files/awareness-materials/Cybersecurity-Awareness-Kit_2023_jp.zip
Disallow: /sites/default/files/e-books/Proofpoint-Cybersecurity-ABC-Picturebook.pdf
Disallow: /sites/default/files/e-books/pfpt-br-eb-the-hidden-cost-of-mso365-security.pdf
Disallow: /sites/default/files/analyst-reports/Frost%20Radar%20-%20Email%20Security%2C%202022%2C%20ProofPoint.pdf
Disallow: /sites/default/files/threat-reports/pfpt-uk-tr-state-of-the-phish-2023.pdf
Disallow: /sites/default/files/threat-reports/pfpt-br-tr-state-of-the-phish-2023.pdf
Disallow: /sites/default/files/threat-reports/pfpt-au-tr-state-of-the-phish-2023.pdf
Disallow: /sites/default/files/threat-reports/pfpt-fr-tr-state-of-the-phish-2023.pdf
Disallow: /sites/default/files/threat-reports/pfpt-it-tr-state-of-the-phish-2023.pdf
Disallow: /sites/default/files/threat-reports/pfpt-de-tr-state-of-the-phish-2023.pdf
Disallow: /sites/default/files/misc/pfpt-uk-tr-state-of-the-phish-2023.pdf
Disallow: /sites/default/files/threat-reports/pfpt-uk-tr-sotp-2023.pdf
Disallow: /sites/default/files/threat-reports/pfpt-us-tr-sotp-2023.pdf
Disallow: /sites/default/files/threat-reports/pfpt-es-tr-sotp-2023.pdf
Disallow: /sites/default/files/threat-reports/pfpt-us-tr-state-of-the-phish-2023.pdf
Disallow: /sites/default/files/threat-reports/pfpt-uk-tr-state-of-the-phish-2023.pdf
Disallow: /sites/default/files/threat-reports/pfpt-es-tr-state-of-the-phish-2023.pdf
Disallow: /sites/default/files/threat-reports/pfpt-ko-tr-state-of-the-phish-2023.pdf
Disallow: /sites/default/files/threat-reports/pfpt-kr-tr-state-of-the-phish-2023.pdf
Disallow: /sites/default/files/e-books/PROO5660_GettingStartDMARC_eBook_A4_jp.pdf
Disallow: /sites/default/files/threat-reports/pfpt-jp-tr-state-of-the-phish-2023.pdf
Disallow: /sites/default/files/e-books/PROO5660_GettingStartDMARC_eBook_A4_jp_20230310a.pdf
Disallow: /sites/default/files/white-papers/pfpt-us-wp-beyond-zero-trust.pdf
Disallow: /sites/default/files/e-books/pfpt-us-eb-top-10-reasons-organizations-choose-pfpt-to-secure-ms365.pdf
Disallow: /sites/default/files/e-books/pfpt-us-eb-security-awareness-handbook.pdf
Disallow: /sites/default/files/white-papers/pfpt-br-wp-voice-of-the-CISO-report.pdf
Disallow: /sites/default/files/e-books/pfpt-us-eb-getting-started-with-dlp-itm.pdf
Disallow: /sites/default/files/threat-reports/pfpt-us-tr-analyzing-identity-risks-air-2022.pdf
Disallow: /sites/default/files/white-papers/pfpt-us-sb-securing-the-messenger.pdf
Disallow: /sites/default/files/threat-reports/pfpt-jp-tr-state-of-the-phish-2023_v2.pdf
Disallow: /sites/default/files/e-books/pfpt-us-eb-biggest-and-boldest-insider-threats.pdf
Disallow: /sites/default/files/e-books/pfpt-br-eb-top-10-reasons-organizations-choose-pfpt-to-secure-ms365.pdf
Disallow: /sites/default/files/threat-reports/pfpt-jp-wp-voice-of-the-CISO-report_2023.pdf
Disallow: /sites/default/files/white-papers/pfpt-us-wp-trusting-transactional-email.pdf
Disallow: /sites/default/files/legal-documents/pfpt-en-master-subscription-agreement-202112-legacy.pdf
Disallow: /sites/default/files/e-books/pfpt-it-eb-security-awareness-handbook.pdf
Disallow: /sites/default/files/e-books/pfpt-de-eb-security-awareness-handbook.pdf
Disallow: /sites/default/files/e-books/pfpt-es-eb-security-awareness-handbook.pdf
Disallow: /sites/default/files/e-books/pfpt-fr-eb-security-awareness-handbook.pdf
Disallow: /sites/default/files/e-books/pfpt-uk-eb-security-awareness-handbook.pdf
Disallow: /sites/default/files/e-books/pfpt-au-eb-security-awareness-handbook.pdf
Disallow: /sites/default/files/e-books/pfpt-br-eb-security-awareness-handbook.pdf
Disallow: /sites/default/files/legal-documents/pfpt-en-gb-general-terms-and-conditions-legacy.pdf
Disallow: /sites/default/files/legal-documents/pfpt-en-general-terms-and-conditions-legacy.pdf
Disallow: /sites/default/files/legal-documents/pfpt-en-digital-risk-products-exhibit-legacy.pdf
Disallow: /sites/default/files/legal-documents/pfpt-en-information-and-compliance-products-exhibit-legacy.pdf
Disallow: /sites/default/files/legal-documents/pfpt-en-security-products-exhibit-legacy.pdf
Disallow: /sites/default/files/legal-documents/pfpt-en-master-subscription-agreement-legacy.pdf
Disallow: /sites/default/files/e-books/pfpt-uk-eb-top-10-reasons-organizations-choose-pfpt-to-secure-ms365.pdf
Disallow: /sites/default/files/e-books/pfpt-au-eb-top-10-reasons-organizations-choose-pfpt-to-secure-ms365.pdf
Disallow: /sites/default/files/e-books/pfpt-fr-eb-top-10-reasons-organizations-choose-pfpt-to-secure-ms365.pdf
Disallow: /sites/default/files/e-books/pfpt-de-eb-top-10-reasons-organizations-choose-pfpt-to-secure-ms365.pdf
Disallow: /sites/default/files/e-books/pfpt-es-eb-top-10-reasons-organizations-choose-pfpt-to-secure-ms365.pdf
Disallow: /sites/default/files/e-books/pfpt-it-eb-top-10-reasons-organizations-choose-pfpt-to-secure-ms365.pdf
Disallow: /sites/default/files/e-books/pfpt-br-eb-getting-started-with-dlp-itm.pdf
Disallow: /sites/default/files/e-books/pfpt-de-eb-getting-started-with-dlp-itm.pdf
Disallow: /sites/default/files/e-books/pfpt-es-eb-getting-started-with-dlp-itm.pdf
Disallow: /sites/default/files/e-books/pfpt-it-eb-getting-started-with-dlp-itm.pdf
Disallow: /sites/default/files/e-books/pfpt-uk-eb-getting-started-with-dlp-itm.pdf
Disallow: /sites/default/files/e-books/pfpt-au-eb-getting-started-with-dlp-itm.pdf
Disallow: /sites/default/files/e-books/pfpt-fr-eb-getting-started-with-dlp-itm.pdf
Disallow: /sites/default/files/legal-documents/pfpt-en-us-privacy-law-addendum.pdf
Disallow: /sites/default/files/white-papers/pfpt-uk-wp-trusting-transactional-email.pdf
Disallow: /sites/default/files/white-papers/pfpt-au-wp-trusting-transactional-email.pdf
Disallow: /sites/default/files/white-papers/pfpt-de-wp-trusting-transactional-email.pdf
Disallow: /sites/default/files/white-papers/pfpt-br-wp-trusting-transactional-email.pdf
Disallow: /sites/default/files/white-papers/pfpt-fr-wp-trusting-transactional-email.pdf
Disallow: /sites/default/files/white-papers/pfpt-it-wp-trusting-transactional-email.pdf
Disallow: /sites/default/files/white-papers/pfpt-es-wp-trusting-transactional-email.pdf
Disallow: /sites/default/files/threat-reports/pfpt-kr-tr-human-factor-report.pdf
Disallow: /sites/default/files/threat-reports/pfpt-us-tr-analyzing-identity-risks-air-2023.pdf
Disallow: /sites/default/files/threat-reports/pfpt-us-tr-analyzing-identity-risks.pdf
Disallow: /sites/default/files/e-books/pfpt-uk-eb-biggest-and-boldest-insider-threats.pdf
Disallow: /sites/default/files/e-books/pfpt-au-eb-biggest-and-boldest-insider-threats.pdf
Disallow: /sites/default/files/e-books/pfpt-br-eb-biggest-and-boldest-insider-threats.pdf
Disallow: /sites/default/files/e-books/pfpt-de-eb-biggest-and-boldest-insider-threats.pdf
Disallow: /sites/default/files/e-books/pfpt-es-eb-biggest-and-boldest-insider-threats.pdf
Disallow: /sites/default/files/e-books/pfpt-fr-eb-biggest-and-boldest-insider-threats.pdf
Disallow: /sites/default/files/e-books/pfpt-it-eb-biggest-and-boldest-insider-threats.pdf
Disallow: /sites/default/files/threat-reports/pfpt-jp-tr-human-factor-report.pdf
Disallow: /sites/default/files/e-books/pfpt-br-eb-youve-got-bec.pdf
Disallow: /sites/default/files/e-books/pfpt-jp-eb-top-10-reasons-organizations-choose-pfpt-to-secure-ms365.pdf
Disallow: /sites/default/files/e-books/pfpt-jp-eb-security-awareness-handbook.pdf
Disallow: /sites/default/files/e-books/pfpt-br-eb-rethinking-dlp.pdf
Disallow: /sites/default/files/white-papers/pfpt-br-wp-driving-real-behavior-change..pdf
Disallow: /sites/default/files/white-papers/pfpt-br-wp-driving-real-behavior-change.pdf
Disallow: /sites/default/files/legal-documents/pfpt-proof-of-concept-%28poc%29-terms-of-use.pdf
Disallow: /sites/default/files/legal-documents/pfpt-proof-of-concept-terms-of-use_0.pdf
Disallow: /sites/default/files/legal-documents/pfpt-poc-terms-of-use.pdf
Disallow: /sites/default/files/e-books/pfpt-us-eb-ransomware-survival-guide.pdf
Disallow: /sites/default/files/white-papers/pfpt-jp-wp-trusting-transactional-email.pdf
Disallow: /sites/default/files/e-books/pfpt-jp-eb-youve-got-bec.pdf
Disallow: /sites/default/files/e-books/pfpt-us-eb-cloud-in-the-crosshairs.pdf
Disallow: /sites/default/files/white-papers/pfpt-fr-wp-board-perspective-report.pdf
Disallow: /sites/default/files/white-papers/pfpt-it-wp-board-perspective-report.pdf
Disallow: /sites/default/files/white-papers/pfpt-de-wp-board-perspective-report.pdf
Disallow: /sites/default/files/white-papers/pfpt-es-wp-board-perspective-report.pdf
Disallow: /sites/default/files/white-papers/pfpt-br-wp-board-perspective-report.pdf
Disallow: /sites/default/files/e-books/pfpt-jp-eb-getting-started-with-dlp-itm.pdf
Disallow: /sites/default/files/white-papers/pfpt-jp-wp-board-perspective-report.pdf
Disallow: /sites/default/files/threat-reports/pfpt-us-tr-cyber-insecurity-in-healthcare.pdf
Disallow: /sites/default/files/white-papers/pfpt-us-wp-email-security-rfp-rfi-template-sep-2023.docx
Disallow: /sites/default/files/threat-reports/pfpt-us-tr-cyber-insecurity-healthcare-ponemon-report.pdf
Disallow: /sites/default/files/data-sheets/pfpt-jp-ds-threat-response-auto-pull_2310.pdf
Disallow: /sites/default/files/e-books/pfpt-us-eb-on-thin-ices.pdf
Disallow: /sites/default/files/e-books/pfpt-us-eb-inbound-outbound.pdf
Disallow: /sites/default/files/white-papers/pfpt-en-wp-achieving-cyber-resiliance.pdf
Disallow: /sites/default/files/e-books/pfpt-uk-eb-ransomware-survival-guide.pdf
Disallow: /sites/default/files/e-books/pfpt-au-eb-ransomware-survival-guide.pdf
Disallow: /sites/default/files/e-books/pfpt-fr-eb-ransomware-survival-guide.pdf
Disallow: /sites/default/files/e-books/pfpt-it-eb-ransomware-survival-guide.pdf
Disallow: /sites/default/files/e-books/pfpt-es-eb-ransomware-survival-guide.pdf
Disallow: /sites/default/files/e-books/pfpt-de-eb-ransomware-survival-guide.pdf
Disallow: /sites/default/files/e-books/pfpt-br-eb-ransomware-survival-guide.pdf
Disallow: /sites/default/files/e-books/pfpt-br-eb-cloud-in-the-crosshairs.pdf
Disallow: /sites/default/files/e-books/pfpt-es-eb-cloud-in-the-crosshairs.pdf
Disallow: /sites/default/files/e-books/pfpt-de-eb-cloud-in-the-crosshairs.pdf
Disallow: /sites/default/files/e-books/pfpt-it-eb-cloud-in-the-crosshairs.pdf
Disallow: /sites/default/files/e-books/pfpt-fr-eb-cloud-in-the-crosshairs.pdf
Disallow: /sites/default/files/e-books/pfpt-us-eb-dmarc-key-to-email-deliverability.pdf
Disallow: /sites/default/files/e-books/pfpt-us-eb-itdr-understanding-identity-risk.pdf
Disallow: /sites/default/files/e-books/pfpt-jp-eb-ransomware-survival-guide.pdf
Disallow: /sites/default/files/e-books/pfpt-uk-eb-dmarc-key-to-email-deliverability.pdf
Disallow: /sites/default/files/e-books/pfpt-au-eb-dmarc-key-to-email-deliverability.pdf
Disallow: /sites/default/files/legal-documents/pfpt-en-federal-eula.pdf
Disallow: /sites/default/files/legal-documents/pfpt-en-sled-eula.pdf
Disallow: /sites/default/files/legal-documents/pfpt-en-customer-agreement-for-aws-marketplace.pdf
Disallow: /sites/default/files/e-books/pfpt-de-eb-dmarc-key-to-email-deliverability.pdf
Disallow: /sites/default/files/e-books/pfpt-fr-eb-dmarc-key-to-email-deliverability.pdf
Disallow: /sites/default/files/customer-stories/pfpt-jp-cs-efd-shiseido.pdf
Disallow: /sites/default/files/new-perimeters-issues/pfpt-en-new-perimeters-2023-issue-6.pdf
Disallow: /sites/default/files/new-perimeters-issues/pfpt-en-new-perimeters-2022-issue-5.pdf
Disallow: /sites/default/files/new-perimeters-issues/pfpt-en-new-perimeters-2022-issue-4.pdf
Disallow: /sites/default/files/new-perimeters-issues/pfpt-en-new-perimeters-2021-issue-3.pdf
Disallow: /sites/default/files/new-perimeters-issues/pfpt-en-new-perimeters-2021-issue-2.pdf
Disallow: /sites/default/files/new-perimeters-issues/pfpt-en-new-perimeters-2021-issue-1.pdf
Disallow: /sites/default/files/e-books/pfpt-br-eb-dmarc-key-to-email-deliverability.pdf
Disallow: /sites/default/files/e-books/pfpt-it-eb-dmarc-key-to-email-deliverability.pdf
Disallow: /sites/default/files/e-books/pfpt-es-eb-dmarc-key-to-email-deliverability.pdf
Disallow: /sites/default/files/legal-documents/%20pfpt-en-ja-customer-agreement.pdf
Disallow: /sites/default/files/legal-documents/pfpt-en-ja-master-subscription-agreement.pdf
Disallow: /sites/default/files/legal-documents/pfpt-en-ja-customer-agreement.pdf
Disallow: /sites/default/files/legal-documents/pfpt-en-dpa.pdf
Disallow: /sites/default/files/legal-documents/pfpt-de-dpa.pdf
Disallow: /sites/default/files/legal-documents/pfpt-es-dpa.pdf
Disallow: /sites/default/files/legal-documents/pfpt-it-dpa.pdf
Disallow: /sites/default/files/e-books/pfpt-fr-eb-itdr-understanding-identity-risk.pdf
Disallow: /sites/default/files/e-books/pfpt-it-eb-itdr-understanding-identity-risk.pdf
Disallow: /sites/default/files/e-books/pfpt-de-eb-itdr-understanding-identity-risk.pdf
Disallow: /sites/default/files/e-books/pfpt-es-eb-itdr-understanding-identity-risk.pdf
Disallow: /sites/default/files/e-books/pfpt-br-eb-itdr-understanding-identity-risk.pdf
Disallow: /sites/default/files/white-papers/PROO6061_jp_Ransomware_Survival_Guide_A4.pdf
Disallow: /sites/default/files/e-books/pfpt-jp-eb-ransomware-survival-guide.pdf.pdf
Disallow: /sites/default/files/e-books/pfpt-jp-eb-cloud-in-the-crosshairs.pdf
Disallow: /sites/default/files/e-books/pfpt-uk-eb-cloud-in-the-crosshairs.pdf
Disallow: /sites/default/files/e-books/pfpt-au-eb-cloud-in-the-crosshairs.pdf
Disallow: /sites/default/files/e-books/pfpt-uk-eb-itdr-understanding-identity-risk.pdf
Disallow: /sites/default/files/threat-reports/pfpt-fr-tr-state-of-the-phish-2024.pdf
Disallow: /sites/default/files/threat-reports/pfpt-uk-tr-state-of-the-phish-2024.pdf
Disallow: /sites/default/files/threat-reports/pfpt-it-tr-state-of-the-phish-2024.pdf
Disallow: /sites/default/files/threat-reports/pfpt-de-tr-state-of-the-phish-2024.pdf
Disallow: /sites/default/files/threat-reports/pfpt-es-tr-state-of-the-phish-2024.pdf
Disallow: /sites/default/files/threat-reports/pfpt-au-tr-state-of-the-phish-2024.pdf
Disallow: /sites/default/files/threat-reports/pfpt-jp-tr-state-of-the-phish-2024.pdf
Disallow: /sites/default/files/threat-reports/pfpt-br-tr-state-of-the-phish-2024.pdf
Disallow: /sites/default/files/threat-reports/pfpt-kr-tr-state-of-the-phish-2024.pdf
Disallow: /sites/default/files/threat-reports/pfpt-us-tr-state-of-the-phish-2024.pdf
Disallow: /sites/default/files/e-books/pfpt-jp-eb-dmarc-key-to-email-deliverability.pdf
Disallow: /sites/default/files/threat-reports/pfpt-us-tr-data-loss-report-2024.pdf
Disallow: /sites/default/files/threat-reports/pfpt-us-tr-data-loss-landscape-report-2024.pdf
Disallow: /sites/default/files/threat-reports/pfpt-uk-tr-data-loss-landscape-report-2024.pdf
Disallow: /sites/default/files/threat-reports/pfpt-au-tr-data-loss-landscape-report-2024.pdf
Disallow: /sites/default/files/threat-reports/pfpt-fr-tr-data-loss-landscape-report-2024.pdf
Disallow: /sites/default/files/threat-reports/pfpt-es-tr-data-loss-landscape-report-2024.pdf
Disallow: /sites/default/files/threat-reports/pfpt-it-tr-data-loss-landscape-report-2024.pdf
Disallow: /sites/default/files/threat-reports/pfpt-de-tr-data-loss-landscape-report-2024.pdf
Disallow: /sites/default/files/threat-reports/pfpt-br-tr-data-loss-landscape-report-2024.pdf
Disallow: /sites/default/files/e-books/pfpt-us-eb-cybersecuritys-ai-tidal-wave.pdf
Disallow: /sites/default/files/threat-reports/pfpt-jp-tr-state-of-the-phish-2024_v2.pdf
Disallow: /sites/default/files/legal-documents/pfpt-tessian-website-support-services-exhibit.pdf
Disallow: /sites/default/files/threat-reports/pfpt-kr-tr-data-loss-landscape-report-2024.pdf
Disallow: /sites/default/files/threat-reports/pfpt-jp-tr-data-loss-landscape-report-2024.pdf
Disallow: /sites/default/files/pfpt-a4-eb-definitive-email-security-strategy-guide-180514.pdf
Disallow: /sites/default/files/e-books/pfpt-jp-tr-data-loss-landscape-report-2024.pdf
Disallow: /sites/default/files/e-books/pfpt-jp-eb-itdr-understanding-identity-risk.pdf
Disallow: /sites/default/files/e-books/pfpt-fr-eb-cybersecuritys-ai-tidal-wave.pdf
Disallow: /sites/default/files/e-books/pfpt-it-eb-cybersecuritys-ai-tidal-wave.pdf
Disallow: /sites/default/files/e-books/pfpt-de-eb-cybersecuritys-ai-tidal-wave.pdf
Disallow: /sites/default/files/e-books/pfpt-es-eb-cybersecuritys-ai-tidal-wave.pdf
Disallow: /sites/default/files/legal-documents/pfpt-en-singapore-personal-data-protection-act.pdf
Disallow: /sites/default/files/legal-documents/pfpt-en-gramm-leach-bliley-act-safeguards-rule-new-breach-reporting-requirements-for-non-bank-financial-institutions.pdf
Disallow: /sites/default/files/legal-documents/pfpt-en-cyber-incident-reporting-for-critical-infrastructure-act.pdf
Disallow: /sites/default/files/legal-documents/pfpt-en-prc-data-privacy-framework.pdf
Sitemap: https://www.proofpoint.com/us/sitemap.xml
Sitemap: https://www.proofpoint.com/uk/sitemap.xml
Sitemap: https://www.proofpoint.com/fr/sitemap.xml
Sitemap: https://www.proofpoint.com/de/sitemap.xml
Sitemap: https://www.proofpoint.com/es/sitemap.xml
Sitemap: https://www.proofpoint.com/jp/sitemap.xml
Sitemap: https://www.proofpoint.com/au/sitemap.xml
Sitemap: https://www.proofpoint.com/it/sitemap.xml
Sitemap: https://www.proofpoint.com/br/sitemap.xml
Sitemap: https://www.proofpoint.com/kr/sitemap.xml