# Data is just the beginning

user-agent: *
Disallow: /en/12435435*
Disallow: /en/forms*
Disallow: /en/modal*
Disallow: /en/fx/forms*
Disallow: /page-layouts*
Disallow: /en/reference-components*
Disallow: /en/site-navigation.html
Disallow: /en/media-centre/press-releases/test*
Disallow: /ja/12435435*
Disallow: /ja/forms*
Disallow: /ja/reference-components*
Disallow: /ja/site-navigation.html
Disallow: /ja/fx/forms*
Disallow: /en/insights/forms
Disallow: /en/insights/reference-components
Disallow: /en/insights/page-layouts
Disallow: /en/ftse-russell/forms
Disallow: /en/ftse-russell/sustainable-investment-metrics/si-metrics-config-pages
Disallow: /en/ftse-russell/site-navigation
Disallow: /en/ftse-russell/errors
Disallow: /en/ftse-russell/12435435
Disallow: /en/ftse-russell/page-layouts
Disallow: /en/ftse-russell/reference-components
Disallow: /en/ftse-russell/thank-you
Disallow: /en/ftse-russell/market-insights/thank-you
Disallow: /en/ftse-russell/client-service-portal/thank-you
Disallow: /en/data-analytics/12435435
Disallow: /en/data-analytics/reference-components
Disallow: /en/data-analytics/forms
Disallow: /en/data-analytics/modal
Disallow: /zh/ftse-russell/forms
Disallow: /zh/ftse-russell/reference-components
Disallow: /zh/ftse-russell/12435435
Disallow: /zh/ftse-russell/errors
Disallow: /en/risk-intelligence/forms
Disallow: /en/risk-intelligence/reference-components
Disallow: /en/risk-intelligence/page-layouts
Disallow: /en/training/learning-centre/learning-paths/customer-solutions

Sitemap: https://www.lseg.com/en/sitemap-index.xml
Sitemap: https://www.lseg.com/ja/sitemap-index.xml