User-agent: *
Crawl-delay: 5
Disallow: /admin/
Disallow: */compliancenext/track/viewed/*
Disallow: */compliancenext/track/favorited/*
Disallow: */compliancenext/?next=/*
Disallow: */members/?page*
Disallow: */compliancenext/ajax/*
Disallow: */compliancenext/user/*
Noindex: */compliancenext/user/*
Disallow: /2018-ethics-compliance-virtual-conference/register
Disallow: */compliancenext/search/
Sitemap: https://www.navex.com/sitemap.xml
Sitemap: https://www.navex.com/en-us/sitemap.xml
Sitemap: https://www.navex.com/en-gb/sitemap.xml
Sitemap: https://www.navex.com/de-de/sitemap.xml
Sitemap: https://www.navex.com/it-it/sitemap.xml
Sitemap: https://www.navex.com/fr-fr/sitemap.xml
Sitemap: https://www.navex.com/es-es/sitemap.xml
Sitemap: https://www.navex.com/ja-jp/sitemap.xml
Sitemap: https://www.navex.com/sv-se/sitemap.xml
Sitemap: https://www.navex.com/fi-fi/sitemap.xml
