User-agent: *
Disallow: /*?country=*
Disallow: /*?bid=*
Disallow: /*?btag=*
Disallow: /*?bpid=*
Disallow: /*&country=*
Disallow: /*&bid=*
Disallow: /*&btag=*
Disallow: /*&bpid=*
Disallow: /*?utm*
Disallow: /*&utm*
Disallow: /*Incapsula_Resource
Disallow: /banner
Disallow: /es-es/cuenta*
Disallow: /es-es/bankid*
Disallow: /es-es/pago*
Disallow: /es-es/perfil*

Sitemap: https://www.leovegas.es/sitemap.xml
Sitemap: https://www.leovegas.es/es-es/sitemap.xml
