#
# robots.txt
#

# Excludes
User-agent: *
Disallow: /API/
Disallow: /de/API/
Disallow: /fr/API/
Disallow: /it/API/
Disallow: /es/API/
Disallow: /pt_br/API/
Disallow: /pl/API/
Disallow: /ru/API/
Disallow: /ja/API/
Disallow: /ko/API/
Disallow: /zh_cn/API/
Disallow: /AssetManager/
Disallow: /de/AssetManager/
Disallow: /fr/AssetManager/
Disallow: /it/AssetManager/
Disallow: /es/AssetManager/
Disallow: /pt_br/AssetManager/
Disallow: /pl/AssetManager/
Disallow: /ru/AssetManager/
Disallow: /ja/AssetManager/
Disallow: /ko/AssetManager/
Disallow: /zh_cn/AssetManager/
Disallow: /Dashboard/
Disallow: /de/Dashboard/
Disallow: /fr/Dashboard/
Disallow: /it/Dashboard/
Disallow: /es/Dashboard/
Disallow: /pt_br/Dashboard/
Disallow: /pl/Dashboard/
Disallow: /ru/Dashboard/
Disallow: /ja/Dashboard/
Disallow: /ko/Dashboard/
Disallow: /zh_cn/Dashboard/
Disallow: /Download/
Disallow: /de/Download/
Disallow: /fr/Download/
Disallow: /it/Download/
Disallow: /es/Download/
Disallow: /pt_br/Download/
Disallow: /pl/Download/
Disallow: /ru/Download/
Disallow: /ja/Download/
Disallow: /ko/Download/
Disallow: /zh_cn/Download/
Disallow: /Error/
Disallow: /de/Error/
Disallow: /fr/Error/
Disallow: /it/Error/
Disallow: /es/Error/
Disallow: /pt_br/Error/
Disallow: /pl/Error/
Disallow: /ru/Error/
Disallow: /ja/Error/
Disallow: /ko/Error/
Disallow: /zh_cn/Error/
Disallow: /HDView/
Disallow: /de/HDView/
Disallow: /fr/HDView/
Disallow: /it/HDView/
Disallow: /es/HDView/
Disallow: /pt_br/HDView/
Disallow: /pl/HDView/
Disallow: /ru/HDView/
Disallow: /ja/HDView/
Disallow: /ko/HDView/
Disallow: /zh_cn/HDView/
Disallow: /License/
Disallow: /de/License/
Disallow: /fr/License/
Disallow: /it/License/
Disallow: /es/License/
Disallow: /pt_br/License/
Disallow: /pl/License/
Disallow: /ru/License/
Disallow: /ja/License/
Disallow: /ko/License/
Disallow: /zh_cn/License/
Disallow: /Login/
Disallow: /de/Login/
Disallow: /fr/Login/
Disallow: /it/Login/
Disallow: /es/Login/
Disallow: /pt_br/Login/
Disallow: /pl/Login/
Disallow: /ru/Login/
Disallow: /ja/Login/
Disallow: /ko/Login/
Disallow: /zh_cn/Login/
Disallow: /MemberInfo/
Disallow: /de/MemberInfo/
Disallow: /fr/MemberInfo/
Disallow: /it/MemberInfo/
Disallow: /es/MemberInfo/
Disallow: /pt_br/MemberInfo/
Disallow: /pl/MemberInfo/
Disallow: /ru/MemberInfo/
Disallow: /ja/MemberInfo/
Disallow: /ko/MemberInfo/
Disallow: /zh_cn/MemberInfo/
Disallow: /Register/
Disallow: /de/Register/
Disallow: /fr/Register/
Disallow: /it/Register/
Disallow: /es/Register/
Disallow: /pt_br/Register/
Disallow: /pl/Register/
Disallow: /ru/Register/
Disallow: /ja/Register/
Disallow: /ko/Register/
Disallow: /zh_cn/Register/
Disallow: /RegisterGmax/
Disallow: /de/RegisterGmax/
Disallow: /fr/RegisterGmax/
Disallow: /it/RegisterGmax/
Disallow: /es/RegisterGmax/
Disallow: /pt_br/RegisterGmax/
Disallow: /pl/RegisterGmax/
Disallow: /ru/RegisterGmax/
Disallow: /ja/RegisterGmax/
Disallow: /ko/RegisterGmax/
Disallow: /zh_cn/RegisterGmax/
Disallow: /Report/
Disallow: /de/Report/
Disallow: /fr/Report/
Disallow: /it/Report/
Disallow: /es/Report/
Disallow: /pt_br/Report/
Disallow: /pl/Report/
Disallow: /ru/Report/
Disallow: /ja/Report/
Disallow: /ko/Report/
Disallow: /zh_cn/Report/
Disallow: /ReportAbuse/
Disallow: /de/ReportAbuse/
Disallow: /fr/ReportAbuse/
Disallow: /it/ReportAbuse/
Disallow: /es/ReportAbuse/
Disallow: /pt_br/ReportAbuse/
Disallow: /pl/ReportAbuse/
Disallow: /ru/ReportAbuse/
Disallow: /ja/ReportAbuse/
Disallow: /ko/ReportAbuse/
Disallow: /zh_cn/ReportAbuse/
Disallow: /Seller/
Disallow: /de/Seller/
Disallow: /fr/Seller/
Disallow: /it/Seller/
Disallow: /es/Seller/
Disallow: /pt_br/Seller/
Disallow: /pl/Seller/
Disallow: /ru/Seller/
Disallow: /ja/Seller/
Disallow: /ko/Seller/
Disallow: /zh_cn/Seller/
Disallow: /ShoppingCart/
Disallow: /de/ShoppingCart/
Disallow: /fr/ShoppingCart/
Disallow: /it/ShoppingCart/
Disallow: /es/ShoppingCart/
Disallow: /pt_br/ShoppingCart/
Disallow: /pl/ShoppingCart/
Disallow: /ru/ShoppingCart/
Disallow: /ja/ShoppingCart/
Disallow: /ko/ShoppingCart/
Disallow: /zh_cn/ShoppingCart/
Disallow: /Upload/
Disallow: /de/Upload/
Disallow: /fr/Upload/
Disallow: /it/Upload/
Disallow: /es/Upload/
Disallow: /pt_br/Upload/
Disallow: /pl/Upload/
Disallow: /ru/Upload/
Disallow: /ja/Upload/
Disallow: /ko/Upload/
Disallow: /zh_cn/Upload/
Disallow: /FullPreview/*/modified
Disallow: /de/FullPreview/*/modified
Disallow: /fr/FullPreview/*/modified
Disallow: /it/FullPreview/*/modified
Disallow: /es/FullPreview/*/modified
Disallow: /pt_br/FullPreview/*/modified
Disallow: /pl/FullPreview/*/modified
Disallow: /ru/FullPreview/*/modified
Disallow: /ja/FullPreview/*/modified
Disallow: /ko/FullPreview/*/modified
Disallow: /zh_cn/FullPreview/*/modified
Disallow: /da/
Disallow: /nl/
Disallow: /sv/
Disallow: /*ã

User-agent: TurnitinBot
Disallow: /            #Will disallow all urls on your site

User-agent: CCBot
Disallow: /

User-agent: GPTBot
Disallow: /

# XML Sitemap
Sitemap: http://www.turbosquid.com/Sitemap/Index.xml
