User-agent: *
Sitemap: http://www.weiboyiqi.com/sitemap.xml
Sitemap: http://www.weiboyiqi.com/baidunews.xml
Disallow: /plus/
Disallow: /include/
Disallow: /templets/
Disallow: /install/
Disallow: /member/
Disallow: /special/
Disallow: /style/
Disallow: /uploads/
Disallow: /*?*