User-agent: *
Disallow: /my-circle/
Disallow: /workarea/
Disallow: /WorkArea/
Disallow: /reservations/
Disallow: /templates/
Disallow: /uploadedfiles/
Disallow: /uploadedFiles/
Disallow: /search/
Disallow: /discover/
Disallow: /Workarea/
Disallow: /*javascript:void(0)*
Disallow: /*javascriptvoid(0)*
Disallow: /travel-friday/
Disallow: /*/travel-friday/
Disallow: /*/media/*
Disallow: /*/reviews/*
Disallow: /*/google-map/*
