User-agent: SemrushBot
Disallow: /

User-agent: SemrushBot-SA
Disallow: /

User-agent: SemrushBot-SI
Disallow: /

User-agent: MJ12bot
Disallow: /

User-agent: *
Allow: /

Disallow: /*?utm=*

User-agent: *
Disallow: /cache/

# Sitemap files
Sitemap: https://khoros.com/sitemap.xml
Sitemap: https://secure.vidyard.com/sitemaps/sitemap-5FPWll8xoriJXY5Yk0EaaQ.xml



# Entries
User-agent: *
Disallow: /resources/beyond-expectations-digital-customer-service
Disallow: /thank-you/lead-registration
Disallow: /thank-you/searchunify-thank-you-request-demo
Disallow: /thank-you/aws-reinvent-khoros-dcc-solution
Disallow: /thank-you/thank-you-partner
Disallow: /thank-you/bridging-in-person-and-virtual-community-events
Disallow: /thank-you/challenges-of-managing-enterprise-cx
Disallow: /thank-you/adobe-khoros-retail-ebook
Disallow: /thank-you/whats-next-for-communities
Disallow: /thank-you/rise-of-digital-commerce
Disallow: /thank-you/community-benchmarks
Disallow: /thank-you/hottakes
Disallow: /thank-you/roadmap
Disallow: /thank-you/deflect-and-contain
Disallow: /thank-you/maintaining-community-momentum
Disallow: /thank-you/community-vision-to-reality
Disallow: /thank-you/conversations-not-clicks
Disallow: /thank-you/improve-cx-podcast
Disallow: /thank-you/idc-marketscape-2021
Disallow: /thank-you/it-takes-a-village
Disallow: /thank-you/build-buy-manage
Disallow: /thank-you/defend-the-digital-frontline
Disallow: /thank-you/advanced-communities
Disallow: /thank-you/conversational-commerce
Disallow: /thank-you/keeping-it-real-with-bots
Disallow: /thank-you/back-to-the-future
Disallow: /thank-you/master-the-digital-service-funnel
Disallow: /thank-you/man-and-machine
Disallow: /thank-you/transforming-to-win
Disallow: /thank-you/contact-center-change-guide
Disallow: /thank-you/gartner-market-guide-community-platforms
Disallow: /thank-you/digital-service-funnel-guide
Disallow: /thank-you/forrester-wave-social-suites-2021
Disallow: /thank-you/ccw-customer-contact-industry-review-june-2021
Disallow: /thank-you/khoros-in-focus-community
Disallow: /thank-you/cx-center-of-excellence
Disallow: /thank-you/digital-cx-excellence
Disallow: /thank-you/khoros-in-focus-digital-care-messaging
Disallow: /thank-you/khoros-in-focus-automation-bots
Disallow: /thank-you/rise-of-community-engagements
Disallow: /thank-you/gartner-report-anz
Disallow: /thank-you/smart-social-report-volume-3-2021
Disallow: /thank-you/smart-social-report-volume-3-2021-2
Disallow: /thank-you/how-brands-can-create-a-globally-consistent-brand-experience
Disallow: /thank-you/apple-messages-for-business-tipsheet
Disallow: /thank-you/podcast-thank-you
Disallow: /thank-you/apple-messages-for-business-call-deflection
Disallow: /thank-you/cx-guide-travel-hospitality
Disallow: /thank-you/win-with-khoros
Disallow: /thank-you/understanding-tiktok-for-brands
Disallow: /thank-you/customer-experience-executive-toolkit
Disallow: /thank-you/contact-center-executive-toolkit
Disallow: /thank-you/chief-marketing-officer-executive-toolkit
Disallow: /thank-you/online-brand-communities
Disallow: /thank-you/khoros-customer-experience-insights
Disallow: /thank-you/turn-customers-into-community
Disallow: /thank-you/teleperformance-ai
Disallow: /thank-you/2021-customer-trust-guide
Disallow: /thank-you/chatbot-and-conversation-design-for-rich-messaging-channels
Disallow: /thank-you/five-new-themes-for-community-management-moderation-from-khoros
Disallow: /thank-you/future-of-the-contact-center
Disallow: /thank-you/thank-you-webinar-khoros-connect-digital-creating-digital-first-customer-engagement-in-the-new-normal-with-british-gas
Disallow: /thank-you/smart-social-report-volume-2-2020
Disallow: /thank-you/engage-expert-content-strategy
Disallow: /thank-you/how-brands-can-align-to-todays-changing-customer-behaviors
Disallow: /thank-you/the-experts-debate-fuelling-your-branded-community-to-drive-innovation-culture
Disallow: /thank-you/customer-care-finance-industry
Disallow: /thank-you/optimizing-the-customer-experience-across-digital-channels
Disallow: /thank-you/engage-customer-focused-innovation
Disallow: /thank-you/engage-unify-social-media
Disallow: /thank-you/engage-advanced-brand-communities
Disallow: /thank-you/engage-scale-messaging
Disallow: /thank-you/engage-elevate-self-service
Disallow: /thank-you/talking-community-with-esri
Disallow: /thank-you/engage-crisis-management
Disallow: /thank-you/engage-communities-and-events
Disallow: /thank-you/engage-customer-retention
Disallow: /thank-you/engage-quality-control
Disallow: /thank-you/engage-measure-roi
Disallow: /thank-you/engage-chatbot-goldilocks
Disallow: /thank-you/jawwy-doubled-digital-care
Disallow: /thank-you/fireside-chat-gu-scallen-hagerty
Disallow: /thank-you/chat-more-sell-more
Disallow: /thank-you/claimed-your-free-pizza-registered
Disallow: /thank-you/hold-the-phone-webinar
Disallow: /thank-you/community-pro-panel
Disallow: /thank-you/whats-new-demo-request
Disallow: /thank-you/community-strategies-webinar
Disallow: /thank-you/community-meetup-zurich
Disallow: /thank-you/khoros-connect-melbourne
Disallow: /thank-you/simplify-consolidate-deliver
Disallow: /thank-you/community-meetup-zurich-videos
Disallow: /thank-you/khoros-community-innovation-summit
Disallow: /lp/tour-test
Disallow: /lp/the-next-generation-of-khoros-communities-watch-three-exclusive-demos
Disallow: /platform/communities/value-analytics
Disallow: /platform/communities/forums
Disallow: /security-contact
Disallow: /security-thank-you
Disallow: /platform/engage-booth-demo
Disallow: /platform/flow-ai-upgrade
Disallow: /contact-us/thank-you-contact
Disallow: /demo/thank-you-request-demo
Disallow: /amazon-marketplace-demo
Disallow: /404
Disallow: /gift-demo
Disallow: /engage/speakers
Disallow: /engage/agenda
Disallow: /powered-by-khoros
Disallow: /demo-webinar
Disallow: /demo-webinar/thank-you-webinar
Disallow: /core
Disallow: /demo-1
Disallow: /demo-2
Disallow: /marketingden
Disallow: /demo-cxi
Disallow: /demo-cxi-cx-summit
Disallow: /demo-service-funnel
Disallow: /partners/thank-you-become-partner
Disallow: /lead-registration
Disallow: /thank-you
Disallow: /thank-you/*
Disallow: /lp/*
Disallow: /development/*
Disallow: /forms/*
Disallow: /footerNavigation/*
Disallow: /mainNavigation/*
Disallow: /secondaryNavigation/*
