User-agent: *
Allow: /
Disallow: /_backup
Disallow: /cache
Disallow: /configs
Disallow: /labo
Disallow: /lib
Disallow: /mfpnet
Disallow: /MPC
Disallow: /PEAR
Disallow: /phpMyAdmin.._._..__-
Disallow: /root
Disallow: /Smarty
Disallow: /templates
Disallow: /templates_c
Disallow: /314159265358979.php
