User-agent: *
Disallow: /testskygge/*
Disallow: /binaries/
Disallow: /en/investors/kalender/aktivitetskalender/calendar-facets/year//
Disallow: /en/investors/kalender/finanskalender/calendar-facets/year//
Disallow: /en/investor/asset-documents/csr-reports/report-facets/year//
Disallow: /en/investor/asset-documents/statutory-corporate/report-facets/year//
Disallow: /en/investor/asset-documents/remuneration-reports/report-facets/year//
Disallow: /en/investor/asset-documents/financial-presentations/report-facets/year//
Disallow: /en/investor/asset-documents/other-publications/report-facets/year//
Disallow: /en/investor/asset-documents/financial-reports/report-facets/year//
Disallow: /en/investor/asset-documents/ssfcr-summary/report-facets/year//
Disallow: /en/investor/asset-documents/risk-reports/report-facets/year//
Disallow: /en/investor/asset-documents/cdp-reports/report-facets/year//
Disallow: /en/investor/asset-documents/general-meetings/report-facets/year//
Disallow: /en/investor/asset-documents/esg-reports/report-facets/year//
Disallow: /en/investor/asset-documents/tcfd-reports/report-facets/year//
Disallow: /en/investor/asset-documents/consensus-estimates/report-facets/year//
Disallow: /en/investor/asset-documents/conference-calls/report-facets/year//
Disallow: /en/csr/report-facets/year//
Disallow: /investor/asset-documents/generalforsamling/report-facets/year//
Disallow: /investor/asset-documents/test/report-facets/year//
Disallow: /investor/asset-documents/esg-rapporter/report-facets/year//
Disallow: /investor/asset-documents/tcfd-rapporter/report-facets/year//
Disallow: /investor/asset-documents/konsensusestimater/report-facets/year//
Disallow: /investor/asset-documents/telefonkonferencer/report-facets/year//
Disallow: /investorer/meddelelser/kalender/finanskalender/calendar-facets/year//
Disallow: /investor/asset-documents/finantial-presentations/report-facets/year//
Disallow: /investor/asset-documents/other-publications/report-facets/year//
Disallow: /investor/asset-documents/csr-reports/report-facets/year//
Disallow: /investor/asset-documents/statutory-corporate/report-facets/year//
Disallow: /investor/asset-documents/remuneration-reports/report-facets/year//
Disallow: /investorer/meddelelser/kalender/aktivitetskalender/calendar-facets/year//
Disallow: /investor/asset-documents/finansielle-raporter/report-facets/year//
Disallow: /investor/asset-documents/ssfcr-summary/report-facets/year//
Disallow: /investor/asset-documents/risk-reports/report-facets/year//
Disallow: /investor/asset-documents/cdp-reports/report-facets/year//
 
