User-agent: *
Disallow: /cgi-bin/
Disallow: /api/
Sitemap: https://www.easy-cert-group.com/sitemap.xml
Sitemap: https://www.easy-cert-group.com/sitemap_de.xml
Sitemap: https://www.easy-cert-group.com/sitemap_en.xml
Sitemap: https://www.easy-cert-group.com/sitemap_fr.xml
Sitemap: https://www.easy-cert-group.com/sitemap_it.xml
Sitemap: https://www.easy-cert-group.com/sitemap_ru.xml
