User-agent: ChatGPT-User
Disallow: /
User-agent: *
Disallow: /lyric-landing-pages/yoga-mat-brand/appointment-confirmation.html
Disallow: /lyric-landing-pages/contact-lens-brand/appointment-confirmation.html
Disallow: /online-hearing-test/ohtreport-confirmation.html
Disallow: /online-hearing-test/appointment-confirmation.html
Disallow: /online-hearing-test/callback-confirmation.html
Disallow: /contact-us/contact-confirmation.html
Disallow: /find-a-hearing-care-specialist/appointment-confirmation.html
Disallow: /sign-up-newsletter/newsletter-confirmation.html
Disallow: /acm-forms/optin-confirmation.html
Disallow: /acm-forms/unsubscribe-confirmation.html
Disallow: /acm-forms/profile-enrichment-confirmation.html
Disallow: /find-a-Lyric-hearing-care-specialist/appointment-confirmation.html
Disallow: /phonak-landing-pages/phonak-songs-for-sound/article-confirmation.html
Disallow: /resources/
Disallow: /formulaires-acm/jeu-skinit.html
Disallow: /phonak-landing-pages.html
Sitemap: https://www.phonak.com/sitemap.xml
Sitemap: https://www.phonak.com/br/pt/sitemap.xml
Sitemap: https://www.phonak.com/co/es/sitemap.xml
Sitemap: https://www.phonak.com/da-dk/sitemap.xml
Sitemap: https://www.phonak.com/de-at/sitemap.xml
Sitemap: https://www.phonak.com/de-ch/sitemap.xml
Sitemap: https://www.phonak.com/de-de/sitemap.xml
Sitemap: https://www.phonak.com/en-au/sitemap.xml
Sitemap: https://www.phonak.com/en-ca/sitemap.xml
Sitemap: https://www.phonak.com/en-in/sitemap.xml
Sitemap: https://www.phonak.com/en-int/sitemap.xml
Sitemap: https://www.phonak.com/en-nz/sitemap.xml
Sitemap: https://www.phonak.com/en-sg/sitemap.xml
Sitemap: https://www.phonak.com/en-uk/sitemap.xml
Sitemap: https://www.phonak.com/en-us/sitemap.xml
Sitemap: https://www.phonak.com/es/es/sitemap.xml
Sitemap: https://www.phonak.com/fi-fi/sitemap.xml
Sitemap: https://www.phonak.com/fr-be/sitemap.xml
Sitemap: https://www.phonak.com/fr-ca/sitemap.xml
Sitemap: https://www.phonak.com/fr-ch/sitemap.xml
Sitemap: https://www.phonak.com/fr-fr/sitemap.xml
Sitemap: https://www.phonak.com/hu/hu/sitemap.xml
Sitemap: https://www.phonak.com/il/he/sitemap.xml
Sitemap: https://www.phonak.com/it/it/sitemap.xml
Sitemap: https://www.phonak.com/jp/ja/sitemap.xml
Sitemap: https://www.phonak.com/kr/ko/sitemap.xml
Sitemap: https://www.phonak.com/mx/es/sitemap.xml
Sitemap: https://www.phonak.com/nl-be/sitemap.xml
Sitemap: https://www.phonak.com/nl/nl/sitemap.xml
Sitemap: https://www.phonak.com/no-no/sitemap.xml
Sitemap: https://www.phonak.com/pl-pl/sitemap.xml
Sitemap: https://www.phonak.com/ru/ru/sitemap.xml
Sitemap: https://www.phonak.com/sv-se/sitemap.xml
Sitemap: https://www.phonak.com/tr/tr/sitemap.xml