User-Agent: *
Disallow: /*/results
Disallow: /global
Disallow: /sitecore
Disallow: /Sitecore
Disallow: /404
Disallow: /App_Browsers/
Disallow: /App_config/
Disallow: /App_Data/
Disallow: /temp/
Disallow: /upload/
Disallow: /xsl/
Disallow: /sitecore_files
Disallow: /sitecore modules/
Disallow: /*/api/
Disallow: /*/*/api/
Disallow: /*/contact-us?productName
Disallow: /*/sitecore
Disallow: /*/*/sitecore
Disallow: /*/Sitecore
Disallow: /*/*/Sitecore
Host: https://www.royalcanin.com/

Sitemap: https://www.royalcanin.com/sitemapindex/sitemap.bg-BG.xml
Sitemap: https://www.royalcanin.com/sitemapindex/sitemap.zh-CN.xml
Sitemap: https://www.royalcanin.com/sitemapindex/sitemap.hr-HR.xml
Sitemap: https://www.royalcanin.com/sitemapindex/sitemap.cs-CZ.xml
Sitemap: https://www.royalcanin.com/sitemapindex/sitemap.es-EC.xml
Sitemap: https://www.royalcanin.com/sitemapindex/sitemap.et.xml
Sitemap: https://www.royalcanin.com/sitemapindex/sitemap.et-EE.xml
Sitemap: https://www.royalcanin.com/sitemapindex/sitemap.el-GR.xml
Sitemap: https://www.royalcanin.com/hk/sitemapindex/sitemap.en-HK.xml
Sitemap: https://www.royalcanin.com/hk/sitemapindex/sitemap.zh-HK.xml
Sitemap: https://www.royalcanin.com/sitemapindex/sitemap.hu-HU.xml
Sitemap: https://www.royalcanin.com/sitemapindex/sitemap.is-IS.xml
Sitemap: https://www.royalcanin.com/sitemapindex/sitemap.is.xml
Sitemap: https://www.royalcanin.com/sitemapindex/sitemap.he-IL.xml
Sitemap: https://www.royalcanin.com/sitemapindex/sitemap.ru-KZ.xml
Sitemap: https://www.royalcanin.com/sitemapindex/sitemap.lv.xml
Sitemap: https://www.royalcanin.com/sitemapindex/sitemap.lv-LV.xml
Sitemap: https://www.royalcanin.com/sitemapindex/sitemap.lt-LT.xml
Sitemap: https://www.royalcanin.com/sitemapindex/sitemap.en-MT.xml
Sitemap: https://www.royalcanin.com/sitemapindex/sitemap.ar-MA.xml
Sitemap: https://www.royalcanin.com/sitemapindex/sitemap.fr-MA.xml
Sitemap: https://www.royalcanin.com/sitemapindex/sitemap.es-PA.xml
Sitemap: https://www.royalcanin.com/sitemapindex/sitemap.fr-RE.xml
Sitemap: https://www.royalcanin.com/sitemapindex/sitemap.ru-RU.xml
Sitemap: https://www.royalcanin.com/sitemapindex/sitemap.ar-SD.xml
Sitemap: https://www.royalcanin.com/sitemapindex/sitemap.ar-SA.xml
Sitemap: https://www.royalcanin.com/sitemapindex/sitemap.sr-Cyrl-RS.xml
Sitemap: https://www.royalcanin.com/sitemapindex/sitemap.sr.xml
Sitemap: https://www.royalcanin.com/sitemapindex/sitemap.en-SG.xml
Sitemap: https://www.royalcanin.com/sitemapindex/sitemap.sk-SK.xml
Sitemap: https://www.royalcanin.com/sitemapindex/sitemap.sl-SI.xml
Sitemap: https://www.royalcanin.com/sitemapindex/sitemap.fr-CH.xml
Sitemap: https://www.royalcanin.com/sitemapindex/sitemap.it-CH.xml
Sitemap: https://www.royalcanin.com/sitemapindex/sitemap.de-CH.xml
Sitemap: https://www.royalcanin.com/sitemapindex/sitemap.ar-001.xml
Sitemap: https://www.royalcanin.com/sitemapindex/sitemap.ar-AE.xml
Sitemap: https://www.royalcanin.com/sitemapindex/sitemap.vi-VN.xml
Sitemap: https://www.royalcanin.com/sitemapindex/sitemap.vi.xml
Disallow: /if
Disallow: /if-it
Disallow: /if-nl
Disallow: /if-no
Disallow: /if-de
Disallow: /if-at
Disallow: /if-au
Disallow: /if-nz
Disallow: /if-dk
Disallow: /if-fi
Disallow: /if-kr
Disallow: /if-pt
Disallow: /if-mx
Disallow: /if-ua
Disallow: /if-in
Disallow: /if-my
Disallow: /if-za
Disallow: /if-es
Disallow: /if-be
Disallow: /if-be/nl_be
Disallow: /if-ar
Disallow: /if-tr
Disallow: /if-ph
Disallow: /if-id
Disallow: /if-br
Disallow: /if-fr
Disallow: /if-jp
Disallow: /if-ie
Disallow: /if-uk
Disallow: /if-co
Disallow: /if-pl
Disallow: /if-cl
Disallow: /if-pr
Disallow: /if-se
Disallow: /if-th
Disallow: /if-ro
Disallow: /if-ca
Disallow: /if-tw

Sitemap: https://www.royalcanin.com/us/sitemap.xml
Sitemap: https://www.royalcanin.com/it/sitemap.xml
Sitemap: https://www.royalcanin.com/nl/sitemap.xml
Sitemap: https://www.royalcanin.com/no/sitemap.xml
Sitemap: https://www.royalcanin.com/de/sitemap.xml
Sitemap: https://www.royalcanin.com/at/sitemap.xml
Sitemap: https://www.royalcanin.com/au/sitemap.xml
Sitemap: https://www.royalcanin.com/nz/sitemap.xml
Sitemap: https://www.royalcanin.com/dk/sitemap.xml
Sitemap: https://www.royalcanin.com/fi/sitemap.xml
Sitemap: https://www.royalcanin.com/kr/sitemap.xml
Sitemap: https://www.royalcanin.com/pt/sitemap.xml
Sitemap: https://www.royalcanin.com/mx/sitemap.xml
Sitemap: https://www.royalcanin.com/ua/sitemap.xml
Sitemap: https://www.royalcanin.com/ua/ru-ua/sitemap.xml
Sitemap: https://www.royalcanin.com/in/sitemap.xml
Sitemap: https://www.royalcanin.com/my/sitemap.xml
Sitemap: https://www.royalcanin.com/za/sitemap.xml
Sitemap: https://www.royalcanin.com/es/sitemap.xml
Sitemap: https://www.royalcanin.com/be/sitemap.xml
Sitemap: https://www.royalcanin.com/be/nl-be/sitemap.xml
Sitemap: https://www.royalcanin.com/ar/sitemap.xml
Sitemap: https://www.royalcanin.com/tr/sitemap.xml
Sitemap: https://www.royalcanin.com/ph/sitemap.xml
Sitemap: https://www.royalcanin.com/id/sitemap.xml
Sitemap: https://www.royalcanin.com/br/sitemap.xml
Sitemap: https://www.royalcanin.com/fr/sitemap.xml
Sitemap: https://www.royalcanin.com/jp/sitemap.xml
Sitemap: https://www.royalcanin.com/ie/sitemap.xml
Sitemap: https://www.royalcanin.com/uk/sitemap.xml
Sitemap: https://www.royalcanin.com/co/sitemap.xml
Sitemap: https://www.royalcanin.com/pl/sitemap.xml
Sitemap: https://www.royalcanin.com/cl/sitemap.xml
Sitemap: https://www.royalcanin.com/pr/sitemap.xml
Sitemap: https://www.royalcanin.com/se/sitemap.xml
Sitemap: https://www.royalcanin.com/th/sitemap.xml
Sitemap: https://www.royalcanin.com/ro/sitemap.xml
Sitemap: https://www.royalcanin.com/ca/sitemap.xml
Sitemap: https://www.royalcanin.com/ca/fr-ca/sitemap.xml
Sitemap: https://www.royalcanin.com/tw/sitemap.xml
# Generated at 5/25/2024 2:32:52 AM