User-agent: *
Disallow: */SendToFriend-Start
Disallow: */on/demandware.store/Sites-HOKA-US-Site/
Disallow: */search/*
Disallow: /*+
Disallow: /*Account-PasswordResetDialogForm
Disallow: /*cid=
Disallow: /*dwvar
Disallow: /*icid=
Disallow: /*pid=
Disallow: /*pmax=
Disallow: /*pmin=
Disallow: /*prefn1=
Disallow: /*prefn2=
Disallow: /*prefn3=
Disallow: /*prefn4=
Disallow: /*prefn5=
Disallow: /*prefv1=
Disallow: /*prefv2=
Disallow: /*prefv3=
Disallow: /*prefv4=
Disallow: /*prefv5=
Disallow: /*Product-ShowQuickView
Disallow: /*Product-ShowQuickView?
Disallow: /*Product-SizeChart?
Disallow: /*Product-Variation?
Disallow: /*Search-UpdateGrid?
Disallow: /*srule=
Disallow: /*sz=
Disallow: */cart/*
Disallow: */checkout/*
Disallow: */mens-road-1/*
Disallow: */mens-trail-1/*
Disallow: /on/demandware.store/Sites-HOKA-US-Site/default/Account-PasswordResetDialog?
Disallow: /on/demandware.store/Sites-HOKA-US-Site/default/Account-Show/
Disallow: /on/demandware.store/Sites-HOKA-US-Site/default/Account-StartRegister/
Disallow: /on/demandware.store/Sites-HOKA-US-Site/default/Cart-MiniAddProduct?
Disallow: /on/demandware.store/Sites-HOKA-US-Site/default/Cart-Show/
Disallow: /on/demandware.store/Sites-HOKA-US-Site/default/Chat-Start/
Disallow: /on/demandware.store/Sites-HOKA-US-Site/default/Counterfeit-XML
Disallow: /on/demandware.store/Sites-HOKA-US-Site/default/EmailOptIn-Save?
Disallow: /on/demandware.store/Sites-HOKA-US-Site/default/EmailOptIn-Start?
Disallow: /on/demandware.store/Sites-HOKA-US-Site/default/PowerReviews-WriteReview?
Disallow: /on/demandware.store/Sites-HOKA-US-Site/default/Product-FormatPrices?
Disallow: /on/demandware.store/Sites-HOKA-US-Site/default/SendToFriend-Start?
Disallow: /on/demandware.store/Sites-HOKA-US-Site/default/Wishlist-Add/
Disallow: /on/demandware.store/Sites-HOKA-US-Site/default/Wishlist-Show/
Disallow: */womens-road-1/*
Disallow: */womens-trail-1/*
Disallow: /en/au/login/*
Disallow: */イエロー
Disallow: */オレンジ
Disallow: */グリーン
Disallow: */グレー
Disallow: */パープル
Disallow: */ピンク
Disallow: */ブラウン
Disallow: */ブラック
Disallow: */ブルー
Disallow: */ホワイト
Disallow: */レッド
Disallow: */lifetime-fitness/*


Sitemap: https://www.hoka.com/sitemap_index_all.xml
Sitemap: https://www.hoka.com/on/demandware.static/Sites-HOKA-US-Site/Sites/en_US/hoka-us/en_US-hreflang.xml
Sitemap: https://www.hoka.com/on/demandware.static/Sites-HOKA-CA-Site/Sites/en_CA/hoka-ca/en_CA-hreflang.xml
Sitemap: https://www.hoka.com/on/demandware.static/Sites-HOKA-EMEA-Site/Sites/de_AT/hoka-emea/de_AT-hreflang.xml
Sitemap: https://www.hoka.com/on/demandware.static/Sites-HOKA-EMEA-Site/Sites/de_DE/hoka-emea/de_DE-hreflang.xml
Sitemap: https://www.hoka.com/on/demandware.static/Sites-HOKA-GLOBALE-Site/Sites/en_BG/hoka-globale/en_BG-hreflang.xml
Sitemap: https://www.hoka.com/on/demandware.static/Sites-HOKA-GLOBALE-Site/Sites/en_CZ/hoka-globale/en_CZ-hreflang.xml
Sitemap: https://www.hoka.com/on/demandware.static/Sites-HOKA-GLOBALE-Site/Sites/en_DK/hoka-globale/en_DK-hreflang.xml
Sitemap: https://www.hoka.com/on/demandware.static/Sites-HOKA-GLOBALE-Site/Sites/en_EE/hoka-globale/en_EE-hreflang.xml
Sitemap: https://www.hoka.com/on/demandware.static/Sites-HOKA-EMEA-Site/Sites/en_ES/hoka-emea/en_ES-hreflang.xml
Sitemap: https://www.hoka.com/on/demandware.static/Sites-HOKA-GLOBALE-Site/Sites/en_FI/hoka-globale/en_FI-hreflang.xml
Sitemap: https://www.hoka.com/on/demandware.static/Sites-HOKA-UK-Site/Sites/en_GB/hoka-uk/en_GB-hreflang.xml
Sitemap: https://www.hoka.com/on/demandware.static/Sites-HOKA-GLOBALE-Site/Sites/en_GR/hoka-globale/en_GR-hreflang.xml
Sitemap: https://www.hoka.com/on/demandware.static/Sites-HOKA-GLOBALE-Site/Sites/en_HR/hoka-globale/en_HR-hreflang.xml
Sitemap: https://www.hoka.com/on/demandware.static/Sites-HOKA-GLOBALE-Site/Sites/en_HU/hoka-globale/en_HU-hreflang.xml
Sitemap: https://www.hoka.com/on/demandware.static/Sites-HOKA-GLOBALE-Site/Sites/en_IE/hoka-globale/en_IE-hreflang.xml
Sitemap: https://www.hoka.com/on/demandware.static/Sites-HOKA-EMEA-Site/Sites/en_IT/hoka-emea/en_IT-hreflang.xml
Sitemap: https://www.hoka.com/on/demandware.static/Sites-HOKA-GLOBALE-Site/Sites/en_LT/hoka-globale/en_LT-hreflang.xml
Sitemap: https://www.hoka.com/on/demandware.static/Sites-HOKA-EMEA-Site/Sites/en_LU/hoka-emea/en_LU-hreflang.xml
Sitemap: https://www.hoka.com/on/demandware.static/Sites-HOKA-EMEA-Site/Sites/en_NL/hoka-emea/en_NL-hreflang.xml
Sitemap: https://www.hoka.com/on/demandware.static/Sites-HOKA-GLOBALE-Site/Sites/en_PL/hoka-globale/en_PL-hreflang.xml
Sitemap: https://www.hoka.com/on/demandware.static/Sites-HOKA-GLOBALE-Site/Sites/en_PT/hoka-globale/en_PT-hreflang.xml
Sitemap: https://www.hoka.com/on/demandware.static/Sites-HOKA-GLOBALE-Site/Sites/en_RO/hoka-globale/en_RO-hreflang.xml
Sitemap: https://www.hoka.com/on/demandware.static/Sites-HOKA-GLOBALE-Site/Sites/en_SI/hoka-globale/en_SI-hreflang.xml
Sitemap: https://www.hoka.com/on/demandware.static/Sites-HOKA-GLOBALE-Site/Sites/en_SK/hoka-globale/en_SK-hreflang.xml
Sitemap: https://www.hoka.com/on/demandware.static/Sites-HOKA-EMEA-Site/Sites/es_ES/hoka-emea/es_ES-hreflang.xml
Sitemap: https://www.hoka.com/on/demandware.static/Sites-HOKA-EMEA-Site/Sites/fr_BE/hoka-emea/fr_BE-hreflang.xml
Sitemap: https://www.hoka.com/on/demandware.static/Sites-HOKA-EMEA-Site/Sites/fr_FR/hoka-emea/fr_FR-hreflang.xml
Sitemap: https://www.hoka.com/on/demandware.static/Sites-HOKA-EMEA-Site/Sites/it_IT/hoka-emea/it_IT-hreflang.xml
Sitemap: https://www.hoka.com/on/demandware.static/Sites-HOKA-EMEA-Site/Sites/nl_BE/hoka-emea/nl_BE-hreflang.xml
Sitemap: https://www.hoka.com/on/demandware.static/Sites-HOKA-EMEA-Site/Sites/nl_NL/hoka-emea/nl_NL-hreflang.xml
Sitemap: https://www.hoka.com/on/demandware.static/Sites-HOKA-GLOBALE-Site/Sites/en_NO/hoka-globale/en_NO-hreflang.xml
Sitemap: https://www.hoka.com/on/demandware.static/Sites-HOKA-GLOBALE-Site/Sites/en_SE/hoka-globale/en_SE-hreflang.xml
Sitemap: https://www.hoka.com/on/demandware.static/Sites-HOKA-GLOBALE-Site/Sites/en_CH/hoka-globale/en_CH-hreflang.xml
Sitemap: https://www.hoka.com/on/demandware.static/Sites-HOKA-GLOBALE-Site/Sites/en_RU/hoka-globale/en_RU-hreflang.xml
Sitemap: https://www.hoka.com/on/demandware.static/Sites-HOKA-GLOBALE-Site/Sites/en_UA/hoka-globale/en_UA-hreflang.xml
Sitemap: https://www.hoka.com/on/demandware.static/Sites-HOKA-GLOBALE-Site/Sites/en_RS/hoka-globale/en_RS-hreflang.xml
Sitemap: https://www.hoka.com/on/demandware.static/Sites-HOKA-GLOBALE-Site/Sites/en_IS/hoka-globale/en_IS-hreflang.xml
Sitemap: https://www.hoka.com/on/demandware.static/Sites-HOKA-GLOBALE-Site/Sites/en_TR/hoka-globale/en_TR-hreflang.xml
Sitemap: https://www.hoka.com/on/demandware.static/Sites-HOKA-GLOBALE-Site/Sites/en_CY/hoka-globale/en_CY-hreflang.xml
Sitemap: https://www.hoka.com/on/demandware.static/Sites-HOKA-GLOBALE-Site/Sites/en_IL/hoka-globale/en_IL-hreflang.xml
Sitemap: https://www.hoka.com/on/demandware.static/Sites-HOKA-GLOBALE-Site/Sites/en_LV/hoka-globale/en_LV-hreflang.xml
Sitemap: https://www.hoka.com/on/demandware.static/Sites-HOKA-GLOBALE-Site/Sites/en_AE/hoka-globale/en_AE-hreflang.xml
Sitemap: https://www.hoka.com/on/demandware.static/Sites-HOKA-GLOBALE-Site/Sites/en_TN/hoka-globale/en_TN-hreflang.xml
Sitemap: https://www.hoka.com/on/demandware.static/Sites-HOKA-GLOBALE-Site/Sites/en_DZ/hoka-globale/en_DZ-hreflang.xml
Sitemap: https://www.hoka.com/on/demandware.static/Sites-HOKA-GLOBALE-Site/Sites/en_QA/hoka-globale/en_QA-hreflang.xml
Sitemap: https://www.hoka.com/on/demandware.static/Sites-HOKA-GLOBALE-Site/Sites/en_BY/hoka-globale/en_BY-hreflang.xml
Sitemap: https://www.hoka.com/on/demandware.static/Sites-HOKA-GLOBALE-Site/Sites/en_MD/hoka-globale/en_MD-hreflang.xml
Sitemap: https://www.hoka.com/on/demandware.static/Sites-HOKA-GLOBALE-Site/Sites/en_MT/hoka-globale/en_MT-hreflang.xml
Sitemap: https://www.hoka.com/on/demandware.static/Sites-HOKA-GLOBALE-Site/Sites/en_SA/hoka-globale/en_SA-hreflang.xml
Sitemap: https://www.hoka.com/on/demandware.static/Sites-HOKA-GLOBALE-Site/Sites/en_ME/hoka-globale/en_ME-hreflang.xml
Sitemap: https://www.hoka.com/on/demandware.static/Sites-HOKA-GLOBALE-Site/Sites/en_AD/hoka-globale/en_AD-hreflang.xml
Sitemap: https://www.hoka.com/on/demandware.static/Sites-HOKA-GLOBALE-Site/Sites/en_KZ/hoka-globale/en_KZ-hreflang.xml
Sitemap: https://www.hoka.com/on/demandware.static/Sites-HOKA-GLOBALE-Site/Sites/en_RE/hoka-globale/en_RE-hreflang.xml
Sitemap: https://www.hoka.com/on/demandware.static/Sites-HOKA-GLOBALE-Site/Sites/en_MC/hoka-globale/en_MC-hreflang.xml
Sitemap: https://www.hoka.com/on/demandware.static/Sites-HOKA-GLOBALE-Site/Sites/en_JE/hoka-globale/en_JE-hreflang.xml
Sitemap: https://www.hoka.com/on/demandware.static/Sites-HOKA-GLOBALE-Site/Sites/en_MK/hoka-globale/en_MK-hreflang.xml
Sitemap: https://www.hoka.com/on/demandware.static/Sites-HOKA-GLOBALE-Site/Sites/en_AL/hoka-globale/en_AL-hreflang.xml
Sitemap: https://www.hoka.com/on/demandware.static/Sites-HOKA-GLOBALE-Site/Sites/en_MA/hoka-globale/en_MA-hreflang.xml
Sitemap: https://www.hoka.com/on/demandware.static/Sites-HOKA-GLOBALE-Site/Sites/en_ZA/hoka-globale/en_ZA-hreflang.xml
Sitemap: https://www.hoka.com/on/demandware.static/Sites-HOKA-GLOBALE-Site/Sites/en_BA/hoka-globale/en_BA-hreflang.xml
Sitemap: https://www.hoka.com/on/demandware.static/Sites-HOKA-AU-Site/Sites/en_AU/hoka-au/en_AU-hreflang.xml
Sitemap: https://www.hoka.com/on/demandware.static/Sites-HOKA-NZ-Site/Sites/en_NZ/hoka-nz/en_NZ-hreflang.xml
Sitemap: https://www.hoka.com/on/demandware.static/Sites-HOKA-JP-Site/Sites/ja_JP/hoka-jp/ja_JP-hreflang.xml

Sitemap: https://www.hoka.com/on/demandware.static/Sites-HOKA-US-Site/Sites/default/hokaoneoneNA.xml
Sitemap: https://www.hoka.com/on/demandware.static/Sites-HOKA-US-Site/Sites/default/hokaoneoneJP.xml
Sitemap: https://www.hoka.com/on/demandware.static/Sites-HOKA-US-Site/Sites/default/hokaoneoneEMEAv1.xml
Sitemap: https://www.hoka.com/on/demandware.static/Sites-HOKA-US-Site/Sites/default/hokaoneoneEMEAv2.xml
Sitemap: https://www.hoka.com/on/demandware.static/Sites-HOKA-US-Site/Sites/default/hokaoneoneEMEAv3.xml
Sitemap: https://www.hoka.com/en/us/sitemap-hoka-splash-page-hreflang.xml