User-agent: * 
Disallow: */ADIonline/*
Disallow: *sandbox*
Disallow: *page-not-found*
Disallow: /learn/Fragments*
Disallow: /learn/sandbox*
Disallow: *video-resources*
Disallow: /content/attbusiness/archive/
Disallow: /ceros-packages/
Disallow: /learn/5G.html
Disallow: /products/wireless/planconfig 
Disallow: /products/wireless/intent/modal 
Disallow: /products/wireless/cart 
Disallow: /products/wireless/checkout 
Disallow: /products/wireless/checkout/businessandbillinginfo 
Disallow: /products/wireless/checkout/numberselection 
Disallow: /products/wireless/checkout/deliveryinfo 
Disallow: /products/wireless/checkout/creditverification 
Disallow: /products/wireless/checkout/errorcto 
Disallow: /products/wireless/checkout/payment 
Disallow: /products/wireless/checkout/terms 
Disallow: /products/wireless/checkout/thankyou
Sitemap: https://www.business.att.com/sitemap-index.xml
