User-agent: CCBot
Disallow: /

User-agent: ChatGPT-User
Disallow: /

User-agent: GPTBot
Disallow: /

User-agent: Google-Extended
Disallow: /

User-agent: *
Disallow: /tncms/tracking/
Disallow: /_services/
Disallow: /tncms/openid2/
Disallow: /tncms/dmp/
Disallow: /tncms/weather/
Disallow: /tncms/search/
Disallow: /tncms/admin/
Disallow: /tncms/messaging/
Disallow: /tncms/block/
Disallow: /tncms/counter/
Disallow: /tncms/openweb/*
Disallow: /tncms/webservice/
Disallow: /tncms/tax/
Disallow: /tncms/media/
Disallow: /tncms/gtm/
Disallow: /tncms/track/
Disallow: /tncms/auth/
Disallow: /tncms/disqus/
Disallow: /marketplace/*action=srch
Disallow: /apartments/*?
Disallow: /tncms/calendar/
Disallow: /calendar/search/
Disallow: /calendar/academic_notifications/search/
Disallow: /calendar/arts_and_entertainment/search/
Disallow: /calendar/intramural_sports/search/
Disallow: /calendar/sporting_events/search/
Disallow: /tncms/user/
Disallow: /users/admin/
Disallow: /users/*/?
Disallow: /content/tncms/assets/v3/form/
Disallow: /content/tncms/form/

Sitemap: https://www.dailynebraskan.com/sitemap.xml
Sitemap: https://www.dailynebraskan.com/tncms/sitemap/editorial.xml
Sitemap: https://www.dailynebraskan.com/tncms/sitemap/editorial.xml?year=1970
Sitemap: https://www.dailynebraskan.com/tncms/sitemap/editorial.xml?year=1998
Sitemap: https://www.dailynebraskan.com/tncms/sitemap/editorial.xml?year=2000
Sitemap: https://www.dailynebraskan.com/tncms/sitemap/editorial.xml?year=2003
Sitemap: https://www.dailynebraskan.com/tncms/sitemap/editorial.xml?year=2004
Sitemap: https://www.dailynebraskan.com/tncms/sitemap/editorial.xml?year=2005
Sitemap: https://www.dailynebraskan.com/tncms/sitemap/editorial.xml?year=2006
Sitemap: https://www.dailynebraskan.com/tncms/sitemap/editorial.xml?year=2007
Sitemap: https://www.dailynebraskan.com/tncms/sitemap/editorial.xml?year=2008
Sitemap: https://www.dailynebraskan.com/tncms/sitemap/editorial.xml?year=2009
Sitemap: https://www.dailynebraskan.com/tncms/sitemap/editorial.xml?year=2010
Sitemap: https://www.dailynebraskan.com/tncms/sitemap/editorial.xml?year=2011
Sitemap: https://www.dailynebraskan.com/tncms/sitemap/editorial.xml?year=2012
Sitemap: https://www.dailynebraskan.com/tncms/sitemap/editorial.xml?year=2013
Sitemap: https://www.dailynebraskan.com/tncms/sitemap/editorial.xml?year=2014
Sitemap: https://www.dailynebraskan.com/tncms/sitemap/editorial.xml?year=2015
Sitemap: https://www.dailynebraskan.com/tncms/sitemap/editorial.xml?year=2016
Sitemap: https://www.dailynebraskan.com/tncms/sitemap/editorial.xml?year=2017
Sitemap: https://www.dailynebraskan.com/tncms/sitemap/editorial.xml?year=2018
Sitemap: https://www.dailynebraskan.com/tncms/sitemap/editorial.xml?year=2019
Sitemap: https://www.dailynebraskan.com/tncms/sitemap/editorial.xml?year=2020
Sitemap: https://www.dailynebraskan.com/tncms/sitemap/editorial.xml?year=2021
Sitemap: https://www.dailynebraskan.com/tncms/sitemap/editorial.xml?year=2022
Sitemap: https://www.dailynebraskan.com/tncms/sitemap/editorial.xml?year=2023
