User-Agent: *
Disallow: /admin/
Disallow: */comments*
Disallow: *user_options*
Disallow: *valorations*
#Disallow: *utm_*
Disallow: */busqueda?*
Disallow: */login?*
Disallow: *?fbclid=*
Disallow: */suscripcion/*
Disallow: *?so=*
Disallow: *?epik*
Disallow: *?KZ*
Disallow: *?back=*
Disallow: *?_se=*
Disallow: *?state=*
Disallow: *?s=*
#Disallow: *&*
Disallow: */backend/*
Disallow: */preview/*
Disallow: */pruebas/*
Disallow: */includes/*
Disallow: */includes_articulos/*
Disallow: */includes_estaticas/*
Disallow: */includes_listados/*
Disallow: */includes_metas/*
Disallow: */includes_pasos/*
Disallow: */includes_portadas/*
Disallow: */includes_recetas/* 
Sitemap: https://www.cocinatis.com/sitemap.xml
Sitemap: https://www.cocinatis.com/sitemap-recipes.xml
Sitemap: https://www.cocinatis.com/sitemap-ingredient_categories.xml
Sitemap: https://www.cocinatis.com/sitemap-categories.xml
Sitemap: https://www.cocinatis.com/sitemap-posts.xml
Sitemap: https://www.cocinatis.com/news.xml

User-agent: OpenAI
Disallow: /
User-agent: ChatGPT
Disallow: /
User-agent: GPTBot 
Disallow: /
User-agent: ChatGPT-User
Disallow: /
User-agent: CCBot
Disallow: /


