User-agent: *
Allow: /
Sitemap: https://www.lawpay.com/sitemap.xml
Disallow: /*?*
Disallow: /*/*?*
Disallow: /*/*/*?*
Disallow: /?partner=ebillity&utm_campaign=lawbillity&utm_medium=web&utm_source=banner
Disallow: /?utm_campaign=demo&utm_medium=blog&utm_source=attyslovelp&utm_content=cta
Disallow: /?utm_medium=web&utm_source=resources
Disallow: /?utmcampaign=bestpractices&utmmedium=blog
Disallow: /?utm_campaign=cashflow&utm_medium=blog&utm_content=eoy&utm_source=cta
Disallow: /thank-you/*
Disallow: /achieve-greatness/2024-legal-industry-report
Disallow: /achieve-greatness/profitable-law-firm-playbook
Disallow: /achieve-greatness/referral-worthy-client-experience
Disallow: /achieve-greatness/trust-account-technology
Disallow: /achieve-greatness/2024-legal-industry-report/
Disallow: /achieve-greatness/profitable-law-firm-playbook/
Disallow: /achieve-greatness/referral-worthy-client-experience/
Disallow: /achieve-greatness/trust-account-technology/