User-agent: *
Disallow: /bin/
Disallow: /api/
Allow: /
Disallow: /contests/frame-my-future-scholarship-2018/details.aspx*
Disallow: /contests/frame-my-future-scholarship-2018/entries.aspx*
Disallow: /contests/frame-my-future-scholarship-2018/finalists.aspx*
Disallow: /contests/frame-my-future-scholarship-contest-2009/details.aspx*
Disallow: /contests/frame-my-future-scholarship-contest-2009/entries.aspx*
Disallow: /contests/frame-my-future-scholarship-contest-2009/finalists.aspx*
Disallow: /contests/frame-my-future-scholarship-contest-2010/details.aspx*
Disallow: /contests/frame-my-future-scholarship-contest-2010/entries.aspx*
Disallow: /contests/frame-my-future-scholarship-contest-2010/finalists.aspx*
Disallow: /contests/frame-my-future-scholarship-contest-2011/details.aspx*
Disallow: /contests/frame-my-future-scholarship-contest-2011/entries.aspx*
Disallow: /contests/frame-my-future-scholarship-contest-2011/finalists.aspx*
Disallow: /contests/frame-my-future-scholarship-contest-2012/details.aspx*
Disallow: /contests/frame-my-future-scholarship-contest-2012/entries.aspx*
Disallow: /contests/frame-my-future-scholarship-contest-2012/finalists.aspx*
Disallow: /contests/frame-my-future-scholarship-contest-2013-overflow/details.aspx*
Disallow: /contests/frame-my-future-scholarship-contest-2013-overflow/entries.aspx*
Disallow: /contests/frame-my-future-scholarship-contest-2013-overflow/finalists.aspx*
Disallow: /contests/frame-my-future-scholarship-contest-2013/details.aspx*
Disallow: /contests/frame-my-future-scholarship-contest-2013/entries.aspx*
Disallow: /contests/frame-my-future-scholarship-contest-2013/finalists.aspx*
Disallow: /contests/frame-my-future-scholarship-contest-2014/details.aspx*
Disallow: /contests/frame-my-future-scholarship-contest-2014/entries.aspx*
Disallow: /contests/frame-my-future-scholarship-contest-2014/finalists.aspx*
Disallow: /contests/frame-my-future-scholarship-contest-2015/details.aspx*
Disallow: /contests/frame-my-future-scholarship-contest-2015/entries.aspx*
Disallow: /contests/frame-my-future-scholarship-contest-2015/finalists.aspx*
Disallow: /contests/frame-my-future-scholarship-contest-2016/details.aspx*
Disallow: /contests/frame-my-future-scholarship-contest-2016/entries.aspx*
Disallow: /contests/frame-my-future-scholarship-contest-2016/finalists.aspx*
Disallow: /contests/frame-my-future-scholarship-contest-2017/details.aspx*
Disallow: /contests/frame-my-future-scholarship-contest-2017/entries.aspx*
Disallow: /contests/frame-my-future-scholarship-contest-2017/finalists.aspx*
Disallow: /contests/frame-my-future-scholarship-contest-2019/details.aspx*
Disallow: /contests/frame-my-future-scholarship-contest-2019/entries.aspx*
Disallow: /contests/frame-my-future-scholarship-contest-2019/finalists.aspx*
Disallow: /contests/frame-my-proudest-moment-contest-2013/details.aspx*
Disallow: /contests/frame-my-proudest-moment-contest-2013/entries.aspx*
Disallow: /contests/frame-my-proudest-moment-contest-2013/finalists.aspx*
Disallow: /contests/frame-my-proudest-moment-contest-2014/details.aspx*
Disallow: /contests/frame-my-proudest-moment-contest-2014/entries.aspx*
Disallow: /contests/frame-my-proudest-moment-contest-2014/finalists.aspx*
Disallow: /contests/frame-my-proudest-moment-contest-2015/details.aspx*
Disallow: /contests/frame-my-proudest-moment-contest-2015/entries.aspx*
Disallow: /contests/frame-my-proudest-moment-contest-2015/finalists.aspx*
Disallow: /contests/frame-your-graduate-photo-contest-2010/details.aspx*
Disallow: /contests/frame-your-graduate-photo-contest-2010/entries.aspx*
Disallow: /contests/frame-your-graduate-photo-contest-2010/finalists.aspx*
Disallow: /contests/sports-photo-contest-2012/details.aspx*
Disallow: /contests/sports-photo-contest-2012/entries.aspx*
Disallow: /contests/sports-photo-contest-2012/finalists.aspx*
Disallow: /contests/test-contest-2017/details.aspx*
Disallow: /contests/test-contest-2017/entries.aspx*
Disallow: /contests/test-contest-2017/finalists.aspx*
Disallow: /contests/where-is-frankie-diploma-frame-contest/details.aspx*
Disallow: /contests/where-is-frankie-diploma-frame-contest/entries.aspx*
Disallow: /contests/where-is-frankie-diploma-frame-contest/finalists.aspx*
Disallow: /images/entities/insignia/v2/DenuSealGold_original.png
Disallow: /images/entities/insignia/v2/DenuSealSilver_original.png
Disallow: /images/entities/insignia/v2/med_full/DenuYmedalSilver.png
Disallow: /images/entities/insignia/v2/med_full/DenuZmedalGold.png
Disallow: /images/entities/insignia/v2/Denu25525SealDimensions_original.png
Disallow: /images/entities/insignia/v2/med_full/DenuNmedal.png
Disallow: /images/products/insignia/full/229628PID30273.png
Disallow: /images/products/insignia/full/291185PID51448.png
Disallow: /images/products/insignia/full/221383PID26483.png
Disallow: /images/products/insignia/full/221380PID26480.png
Disallow: /images/products/insignia/full/260669PID43865.png
Disallow: /images/Entities/insignia/v2/DenuYmedalSilver_220.png
Disallow: /images/Entities/insignia/v2/DenuSealGold_220.png
Disallow: /images/Entities/insignia/v2/DenuNmedal_220.png
Disallow: /images/Entities/insignia/v2/Denu25525SealDimensions_220.png
Sitemap: https://www.diplomaframe.com/sitemap-index.xml
Sitemap: https://www.diplomaframe.com/chc-blog/sitemap.xml
user-agent: Pinterestbot
crawl-delay: 2
user-agent: rogerbot
crawl-delay: 2
user-agent: AhrefsBot
crawl-delay: 2
