Sitemap: https://www.whtop.com/sitemap.xml
User-agent: *
Disallow: /photos2.acenter/*
Disallow: /photos2.aright/*
Disallow: /message.err403
Disallow: /*/message.err403
Disallow: /message.err400
Disallow: /*/message.err400
Disallow: /utils.votes/*
Disallow: /*/utils.votes/*
Disallow: /rss.*
Disallow: /directory/search/*
Disallow: /news/search/*
Disallow: /*/directory/search/*
Disallow: /*/news/search/*
Disallow: /reviews.add/*
Disallow: /*/reviews.add/*
Disallow: /*/*.htm
