User-agent: Googlebot
Allow: /go
Allow: /$
Disallow: /
Host: zakon.rada.gov.ua

User-agent: msnbot
Allow: /go
Allow: /$
Disallow: /
Host: zakon.rada.gov.ua

User-agent: Yandex
Allow: /go
Allow: /$
Disallow: /
Host: zakon.rada.gov.ua

User-Agent: *
Disallow: /

user-agent: AhrefsBot
Disallow: /

User-agent: proximic
Disallow: /

User-agent: Cliqzbot
Disallow: /

User-agent: dotbot
Disallow: /

User-agent: SemrushBot
Disallow: /

User-agent: ltx71
Disallow: /
